<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_AvaliderDIORRE</name>
   <tag></tag>
   <elementGuidId>f4805904-43c9-4cc8-a9c6-1a3d0f6632d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.enum-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namRetfinanceStatut-container']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;A valider DIORRE&quot;i >> internal:text=&quot;A valider DIORRE&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>030454f7-3ab1-4016-ac6b-35b8f858d83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A valider DIORRE</value>
      <webElementGuid>bf3c18d6-c248-47cc-8268-230cfa6613d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namRetfinanceStatut-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>a56dd4ed-7f3e-4c6a-a423-f0c07b091e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namRetfinanceStatut-container']/div/span</value>
      <webElementGuid>c4145533-74de-4401-8083-c770cfb5cb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut'])[1]/following::span[5]</value>
      <webElementGuid>a0154047-8a12-4d4b-b61f-914fdecd354a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de la demande'])[1]/following::span[5]</value>
      <webElementGuid>11db54f3-c3ab-4aca-afdd-ebb2c46d7e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volontaire'])[2]/preceding::span[3]</value>
      <webElementGuid>739c0230-f0a1-425f-9aa6-d2e7ee0c941d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeune | Jeunes'])[1]/preceding::span[4]</value>
      <webElementGuid>3e86bd11-454b-43aa-8dbb-fde6922cfc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>5d54d0d7-98f9-4308-ae04-a96745024c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A valider DIORRE' or . = 'A valider DIORRE')]</value>
      <webElementGuid>6f9ce3d3-01ed-463a-81d3-07fcd8788b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
