<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commentaire</name>
   <tag></tag>
   <elementGuidId>6af79b42-8541-47d1-9f8f-56f12625bc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namRetfinanceCmtRetenue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namRetfinanceCmtRetenue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namRetfinanceCmtRetenue</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>64bc33a8-7114-496e-b8e0-6eafec698fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>d4481849-92e3-4139-8fb9-83ab61772024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namRetfinanceCmtRetenue</value>
      <webElementGuid>dbd4e895-2ce0-451c-abe7-2e774a4eb8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namRetfinanceCmtRetenue</value>
      <webElementGuid>8f0cfc52-0a5f-42c5-8d8e-e0a39c6e880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d4be6d2f-9070-45a3-b378-eb3cded61c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>d583ca04-7199-4714-88f2-07bd6b2ed236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namRetfinanceCmtRetenue&quot;)</value>
      <webElementGuid>6541990e-f97c-4b2c-8ac9-ea3c20df695f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namRetfinanceCmtRetenue']</value>
      <webElementGuid>617ac551-7197-4eb7-8205-d7d590221d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[6]/div/div/textarea</value>
      <webElementGuid>7765d5be-bee8-4457-9379-0f4855633367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d114c79f-df7c-4614-8ac7-3fd7036c86c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namRetfinanceCmtRetenue' and @name = 'namRetfinanceCmtRetenue']</value>
      <webElementGuid>d40b36b2-0fef-4a8b-bf46-40016f76ed5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
