<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomdeAgentAccompagnant</name>
   <tag></tag>
   <elementGuidId>b36bc0f0-5f28-44b6-983a-943ad515141d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namUsrAccompRetfinanceId__usr_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namUsrAccompRetfinanceId__usr_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namUsrAccompRetfinanceId__usr_last_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fb05f74-1609-41cb-80f5-9ab6b4ec1110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>68f7fcb7-59be-48bd-a217-d4ecce651845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d7e2107-6d92-40fa-ae6f-64acd38ad136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namUsrAccompRetfinanceId__usr_last_name</value>
      <webElementGuid>62be4573-e6eb-4d99-9c08-5c7ab49959bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namUsrAccompRetfinanceId__usr_last_name</value>
      <webElementGuid>3060e397-556d-43ba-9f9d-2ba8c49e54ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9e0dfd1e-6612-4f9f-98d1-9b61e85649b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08279609-f7e4-472e-9fda-648a8bde019d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3e24766c-af60-4c83-8e35-7517fd982659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namUsrAccompRetfinanceId__usr_last_name&quot;)</value>
      <webElementGuid>0d33c702-c713-4efe-acd5-2c4c71774cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namUsrAccompRetfinanceId__usr_last_name']</value>
      <webElementGuid>3db7a053-d3fe-4945-a220-909f9bcbef8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area4']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>6ee1b4c9-c646-43a9-97ec-295d61e21af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>30fcd24b-7bcc-4786-8b6d-1abbf1aa6ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namUsrAccompRetfinanceId__usr_last_name' and @name = 'namUsrAccompRetfinanceId__usr_last_name']</value>
      <webElementGuid>d891feaf-faa0-4160-9240-2a863cbee892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
