<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomduCSMG</name>
   <tag></tag>
   <elementGuidId>82181cf7-3b25-43dd-984b-e85fa206c006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namUsrCsmgRetfinanceId__usr_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namUsrCsmgRetfinanceId__usr_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namUsrCsmgRetfinanceId__usr_last_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de3b9ca7-42ef-441d-9139-8851d3189241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>643c6aee-2755-4d2a-b34c-856782f6e431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdbd6e6d-88e3-47b9-9e25-a107346175cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namUsrCsmgRetfinanceId__usr_last_name</value>
      <webElementGuid>6eedeff3-e5af-4c00-b167-ddb339ea3ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namUsrCsmgRetfinanceId__usr_last_name</value>
      <webElementGuid>cade1788-d5ae-40e5-8d05-969a2c259cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4fe57e38-6452-4f27-9c28-401cc72cc7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd7bac1e-0be8-4944-a7e9-5160446de3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>84994666-6a32-461c-a0a5-6ce04d54cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namUsrCsmgRetfinanceId__usr_last_name&quot;)</value>
      <webElementGuid>149a3960-1aeb-4204-8d2b-7e65c89bc52b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namUsrCsmgRetfinanceId__usr_last_name']</value>
      <webElementGuid>6540e132-4f8f-47cb-b711-a3fd1578ffc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>0abf56fc-ab60-4c94-8c8c-69676dcd9410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>c9fac0e7-d373-42f5-89a7-023c5b1bfa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namUsrCsmgRetfinanceId__usr_last_name' and @name = 'namUsrCsmgRetfinanceId__usr_last_name']</value>
      <webElementGuid>c7498841-78c7-4e81-abf5-bed3eb732e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
