<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_Pedagogique</name>
   <tag></tag>
   <elementGuidId>9a550857-9a67-40b6-817f-c3c329b2d4f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fc-timeline-event.fc-h-event.fc-event.fc-event-resizable.fc-event-start.fc-event-end.fc-event-today.fc-event-future</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='absenceCalendar']/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[2]/td/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Pédagogique&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11980f73-de65-4c52-ac28-f8ae025a5f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-timeline-event fc-h-event fc-event fc-event-resizable fc-event-start fc-event-end fc-event-today fc-event-future</value>
      <webElementGuid>68155755-1e36-41a1-96dc-5f0d354d8afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5506a0b-541c-4beb-a1f7-27651628f50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pédagogique</value>
      <webElementGuid>d1e8f1d0-ec4b-45d7-970e-fe11be5fa5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>baf12e6a-a14d-4fb6-bc6b-5d44db45d94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;absenceCalendar&quot;)/div[@class=&quot;fc-view-harness fc-view-harness-passive&quot;]/div[@class=&quot;fc-resource-timeline  fc-timeline fc-timeline-overlap-disabled fc-resourceTimelineMonth-view fc-view&quot;]/table[@class=&quot;fc-scrollgrid&quot;]/tbody[1]/tr[@class=&quot;fc-scrollgrid-section fc-scrollgrid-section-body&quot;]/td[3]/div[@class=&quot;fc-scroller-harness&quot;]/div[@class=&quot;fc-scroller&quot;]/div[@class=&quot;fc-timeline-body&quot;]/table[@class=&quot;fc-scrollgrid-sync-table&quot;]/tbody[1]/tr[2]/td[@class=&quot;fc-timeline-lane fc-resource&quot;]/div[@class=&quot;fc-timeline-lane-frame&quot;]/div[@class=&quot;fc-timeline-events fc-scrollgrid-sync-inner&quot;]/div[@class=&quot;fc-timeline-event-harness&quot;]/a[@class=&quot;fc-timeline-event fc-h-event fc-event fc-event-resizable fc-event-start fc-event-end fc-event-today fc-event-future&quot;]</value>
      <webElementGuid>88f7b947-c2c8-45c9-bd6c-94da19486e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='absenceCalendar']/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[2]/td/div/div[2]/div/a</value>
      <webElementGuid>b503777c-d90a-4afb-99ea-f1736f7036ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEULE Erwann'])[1]/following::a[1]</value>
      <webElementGuid>2ed2f0d3-1dec-41d7-9079-d39a3195f6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIAKA Echat'])[1]/following::a[1]</value>
      <webElementGuid>c2ac1a34-e80e-4450-ba43-5fbcb708b824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mars 2026'])[2]/preceding::a[1]</value>
      <webElementGuid>cd6e3cd4-278d-476f-85b7-f55a22fa9988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>834852cc-2bc4-4675-9eac-cd58cba25d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Pédagogique' and (text() = 'P' or . = 'P')]</value>
      <webElementGuid>863a7945-d60f-464e-a4bc-8e171a655959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
