<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_libelle_abrege_type_absence</name>
   <tag></tag>
   <elementGuidId>0bf14864-4a47-4b0f-b86f-4119e3cb2a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAbsTypabId__namTypabShortLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namAbsTypabId__namTypabShortLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namAbsTypabId__namTypabShortLabel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78eaaa08-54f2-4afe-aa0e-0bcc55f4284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>2efde10c-67d0-4919-a41d-30427bfdfd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>420ffc73-a0a3-4274-aef2-bb3f6692d893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>0f4c3d3d-b27f-4d03-ab68-62b56ced3665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAbsTypabId__namTypabShortLabel</value>
      <webElementGuid>b2e95f9e-3db9-4f6a-b8a6-e821ee8e0170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAbsTypabId__namTypabShortLabel</value>
      <webElementGuid>b4aa6110-9a14-46b3-bead-aee557567951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2d3e7104-9515-45f3-97c6-8d7ac4756ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3afc3401-0f85-4a63-81ad-ac3bd9debaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a9c2dfb2-01d7-4857-ac21-21241ae25db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAbsTypabId__namTypabShortLabel&quot;)</value>
      <webElementGuid>35a884d2-ea57-4410-b864-847fe89e72a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namAbsTypabId__namTypabShortLabel']</value>
      <webElementGuid>88c21f14-f739-4854-9270-578cbda11b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamAbsence_the_ajax_NamAbsence_2000739']/div/div[2]/form/div/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>5ba13dbc-06f5-43ec-80b5-0c21952a5474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>7ec34fcb-4b55-4a63-a4a8-e9820db13601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namAbsTypabId__namTypabShortLabel' and @name = 'namAbsTypabId__namTypabShortLabel']</value>
      <webElementGuid>c64629bf-189f-482a-9ff5-dfe1e8a4b40c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
