<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Non_Justificatif_fourni</name>
   <tag></tag>
   <elementGuidId>ee1c8289-c053-44a3-9bd4-707084657fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAbsJustificatifFourni_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namAbsJustificatifFourni_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Non&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef126d12-df12-4c81-95c9-197059bed7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f1c1534a-1ab3-41cb-8738-01cd8d5d7c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAbsJustificatifFourni_no</value>
      <webElementGuid>3202e604-f9f1-4423-bdcd-744c9892a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAbsJustificatifFourni</value>
      <webElementGuid>2baf791d-ca67-4d44-9280-b32f76f312e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>104875e2-6561-4fa0-bb04-c19970dff085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e95f065e-0c3f-4ae3-8066-57523fb9791b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAbsJustificatifFourni_no&quot;)</value>
      <webElementGuid>d7044556-720d-4bc2-89c5-cbcd53fe22eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namAbsJustificatifFourni_no']</value>
      <webElementGuid>14626523-2c29-4baf-96aa-5dab9e38a431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamAbsence_the_ajax_NamAbsence_2000739']/div/div[2]/form/div/div/div[4]/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>c8a50f21-5942-47d2-bef0-099df059d067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>e733f704-9130-4b8e-ad8d-9f1ac44cf1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namAbsJustificatifFourni_no' and @name = 'namAbsJustificatifFourni' and @type = 'radio']</value>
      <webElementGuid>a9fa8aad-918b-4adc-9380-a9f1b2ff101d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
