<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_necess_justif</name>
   <tag></tag>
   <elementGuidId>8a701c0a-6f12-4d28-9c4c-5015cd92ce34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namTypabNecessiteJustificatif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;namTypabNecessiteJustificatif&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namTypabNecessiteJustificatif</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43ce284e-430d-45f5-be46-b807e75de353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namTypabNecessiteJustificatif</value>
      <webElementGuid>ed520891-267f-4329-b8e2-9723bcf604da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>16f44bb2-4e02-491f-b317-980ebd78739b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OuiNon</value>
      <webElementGuid>52647f82-0f3e-4ead-92ce-0528a1de426f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namTypabNecessiteJustificatif&quot;)</value>
      <webElementGuid>f3f8912e-96b8-4297-bc0e-09004213dbdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='namTypabNecessiteJustificatif']</value>
      <webElementGuid>89b0dd54-5997-4ec3-be2b-ca1ff0fbc810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamTypeAbsence_the_ajax_NamTypeAbsence']/div/div[2]/form/div/table/thead/tr[2]/th[6]/div/select</value>
      <webElementGuid>392d8ee0-e41e-46d8-90a7-928acfba64b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[2]</value>
      <webElementGuid>b16cf7a0-1e86-486f-a7ba-f857b89b874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absence irrégulière'])[1]/preceding::select[2]</value>
      <webElementGuid>b90d7f65-271f-447d-ad95-848645548470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI'])[1]/preceding::select[2]</value>
      <webElementGuid>22c0e0cc-0950-4959-9356-e8a44efbd022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/select</value>
      <webElementGuid>a6296ae4-c8b8-444b-bfa7-564b84790a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'namTypabNecessiteJustificatif' and (text() = 'OuiNon' or . = 'OuiNon')]</value>
      <webElementGuid>6edd2400-ba2a-4b04-aca5-4673f87b2429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
