<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_DemandesTransfert</name>
   <tag></tag>
   <elementGuidId>3e5c0773-c6a5-4f97-a844-8190b055c794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/nav/ul/li/ul/li[5]/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-sel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Demandes de transfert&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18f5cbce-3e71-444a-ad0b-b1b3f577c131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-obj</name>
      <type>Main</type>
      <value>NamDemandeTransfertCentre</value>
      <webElementGuid>b4be80bc-e166-4b7a-b114-3ec56d31fa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>1da9966c-067d-4384-b725-289a9f591c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-sel</value>
      <webElementGuid>f51dde9d-e343-4c19-9fc3-0512a478d93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demandes de transfert</value>
      <webElementGuid>aeb5cbdc-4c81-4291-89ff-4dc02a50c77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;main-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[6]/a[@class=&quot;menu-sel&quot;]</value>
      <webElementGuid>c9d2e3be-4634-449b-b222-c33bfa0f34c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/nav/ul/li/ul/li[5]/ul/li[6]/a</value>
      <webElementGuid>cbbea6a1-ed4f-4993-a2d3-e5665c309225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSE'])[1]/following::a[1]</value>
      <webElementGuid>092f27da-9caa-4184-85f8-bcf7bb055a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COF'])[1]/following::a[2]</value>
      <webElementGuid>884a95b0-b9d5-456c-8ee2-0b8bdd14b7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sortie du volontaire'])[1]/preceding::a[1]</value>
      <webElementGuid>f5142aa9-d331-46b9-8353-7277d888cf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[18]</value>
      <webElementGuid>b5211e54-b4ea-4a5d-9b37-4d80b79474dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[6]/a</value>
      <webElementGuid>fed79769-a9c0-46d8-98b5-4aeb87ec0a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Demandes de transfert' or . = 'Demandes de transfert')]</value>
      <webElementGuid>d9807ac0-fb23-420c-88d2-b0587c7d3ae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
