<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_VerifierAdresse</name>
   <tag></tag>
   <elementGuidId>8776dce4-4835-4544-bfab-04b1fa5341d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Vérifier l'adresse&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b611f543-a9e7-40a1-bf58-b241386fa8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>def6992f-e3db-4434-8bc0-1ff94490fd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>verifAdrBtn()</value>
      <webElementGuid>a40cc352-d644-4b2a-9348-3d3857a4cf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>461e4329-003d-41e2-90d0-1108e95aa4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vérifier l'adresse</value>
      <webElementGuid>df25d9e8-c2c5-4d93-b24f-f87785ee77fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;area7&quot;)/div[@class=&quot;alert alert-danger&quot;]/div[3]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>990690a5-b81d-4cb3-9a57-3a2d0e721c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>5c567bdb-bef7-4057-9818-c01a1580adae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area7']/div/div[3]/button</value>
      <webElementGuid>3b3e5b09-6a89-4d62-8a29-ac6b6b00e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vérifier adresse'])[1]/following::button[1]</value>
      <webElementGuid>a58f2772-a97a-4e50-84f0-5822054ab1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresse non reconnue'])[1]/following::button[1]</value>
      <webElementGuid>f1ffb5ad-3b5c-46f8-9e32-cdc062ca45a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QPV'])[2]/preceding::button[1]</value>
      <webElementGuid>f514af33-3ba0-47d1-b4d7-4ece56335ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom QPV'])[2]/preceding::button[1]</value>
      <webElementGuid>4d493738-e3c6-4da6-a173-c0e2b7c4b4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>a9b4e937-bd32-4a97-847c-866d981507b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = concat(&quot;Vérifier l&quot; , &quot;'&quot; , &quot;adresse&quot;) or . = concat(&quot;Vérifier l&quot; , &quot;'&quot; , &quot;adresse&quot;))]</value>
      <webElementGuid>c78ea0b9-0a3d-499c-ad01-8b5e8dfb351b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
