<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_StatutJeune</name>
   <tag></tag>
   <elementGuidId>ae726cd5-743d-4bfe-b031-6777aee2e270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/tbody/tr/td[8]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-left.enum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Dépôt de candidature&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94fe68a0-745f-450c-9733-3f92acadd604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left enum</value>
      <webElementGuid>17423180-2b6d-4d81-bd4a-0edba0f0272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dépôt de candidature</value>
      <webElementGuid>49ed6f8d-9cb4-4137-91a3-91511c27a402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamJeune_ref_ajax_NamJeune&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[8]/div[@class=&quot;text-left enum&quot;]</value>
      <webElementGuid>6adeb760-89c1-489a-ae55-940f1541a2d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/tbody/tr/td[8]/div</value>
      <webElementGuid>5171514e-7521-475e-a917-da5265819541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mail@gmail.com'])[1]/following::div[2]</value>
      <webElementGuid>5069f3a5-1f60-46f6-a660-2c02d70df0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRAPRENOM'])[1]/following::div[5]</value>
      <webElementGuid>a055bcb0-b3c7-4085-8ae1-354103979a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRATest'])[1]/preceding::div[1]</value>
      <webElementGuid>73df1b1b-80dc-42df-91e4-9b900098e17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traprenom'])[1]/preceding::div[2]</value>
      <webElementGuid>911e2d11-5f7f-4c5f-91c3-46d9eb764d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div</value>
      <webElementGuid>5257d106-7b15-4a27-83f2-fff107322b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dépôt de candidature' or . = 'Dépôt de candidature')]</value>
      <webElementGuid>551afc70-c1b9-45bd-83b6-06dbda9b714f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
