<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_VerificationAdresse</name>
   <tag></tag>
   <elementGuidId>d6fb3863-dbb1-4c52-b7e6-a3482713fc66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dlgmodal']/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Vérification d'adresse&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>51542527-2dd3-48cc-bbe2-808e8a8cc7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vérification d'adresse</value>
      <webElementGuid>3f5188b9-4084-4fed-bc4a-e3a90ce749cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlgmodal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h3[1]</value>
      <webElementGuid>93d14423-f7ae-44f9-b164-aa5e972a24af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgmodal']/div/div/div/h3</value>
      <webElementGuid>be937831-2174-43d6-b07c-fd3e80324585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nam hdt'])[1]/following::h3[1]</value>
      <webElementGuid>86db6022-09cb-44cb-a692-3d53a7e95e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut sur le marché du travail'])[1]/following::h3[1]</value>
      <webElementGuid>bbaf7e8b-93b5-4ea5-bd2b-0ee693135335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::h3[1]</value>
      <webElementGuid>190a4f5b-240f-49bb-8e32-b5595d613d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuler'])[1]/preceding::h3[1]</value>
      <webElementGuid>a352c2fc-53c0-4a2e-ad49-ab3be0dcd0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h3</value>
      <webElementGuid>bb57b6bf-7b12-41fc-8061-4d50a1dc7b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = concat(&quot;Vérification d&quot; , &quot;'&quot; , &quot;adresse&quot;) or . = concat(&quot;Vérification d&quot; , &quot;'&quot; , &quot;adresse&quot;))]</value>
      <webElementGuid>0699e295-1ee0-4d39-a659-2fbe0c7bfb17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
