<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Access_New_Account_Epide</name>
   <tag></tag>
   <elementGuidId>b686fbd7-c0eb-4eca-bcc2-8a69f7a6768a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherTileText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='otherTileText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Utiliser un autre compte&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73dfe62d-025b-4f4a-bc0e-09e132978dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherTileText</value>
      <webElementGuid>c3dbf3a4-5fde-49c4-88f5-1f2ee808dd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: otherTileText</value>
      <webElementGuid>fa576e9d-5c5c-462e-8221-19f8862f4b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Utiliser un autre compte</value>
      <webElementGuid>f38cb78b-5304-47c7-9eac-2c2f918cdf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherTileText&quot;)</value>
      <webElementGuid>99ec1179-7ca4-4b94-8d9f-b13983268f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='otherTileText']</value>
      <webElementGuid>5305bf49-c94c-4721-925f-9792b05de767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherTile']/div/div[2]/div</value>
      <webElementGuid>e7e156ce-2a9b-4e17-97c9-7dd26527392a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecté à Windows'])[1]/following::div[6]</value>
      <webElementGuid>471b5e9f-c9fe-4ffc-959e-118976088be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='omar.jaddour@atos.net'])[1]/following::div[7]</value>
      <webElementGuid>2f121134-a764-4f9a-8ca2-e8f48f0826ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confidentialité et cookies'])[1]/preceding::div[6]</value>
      <webElementGuid>9d629529-5f5f-46c6-b711-7c02d5c72189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Utiliser un autre compte']/parent::*</value>
      <webElementGuid>0de001cf-ca8b-437f-a18e-ad8da1390e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>d0a9cf4a-a501-402c-a53d-aa79cc6faac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'otherTileText' and (text() = 'Utiliser un autre compte' or . = 'Utiliser un autre compte')]</value>
      <webElementGuid>dec3898e-a1fa-4048-ab0e-4761bd64de12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
