<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Access_CoordonneesBancaires</name>
   <tag></tag>
   <elementGuidId>b9c69b7b-a889-4f4a-8962-bb058bdbeda5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-header.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel_create_NamJeune_the_ajax_NamJeune_27']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Coordonnées bancaires$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cfd08cd-e0b8-45c2-b051-d2c6c4bfe278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header collapsed</value>
      <webElementGuid>fa19d74f-ec2b-4fe1-a416-e0b4cc1a7071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>5fa68769-258b-4c53-a97b-8badbeda7a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse_panel_create_NamJeune_the_ajax_NamJeune_27</value>
      <webElementGuid>cb92241d-4f2f-4a52-afc5-908283c655cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coordonnées bancaires</value>
      <webElementGuid>c1b1e327-eb63-4874-81c3-801bbd042c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel_create_NamJeune_the_ajax_NamJeune_27&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header collapsed&quot;]</value>
      <webElementGuid>d7943406-2194-4bd7-95dd-327080723794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel_create_NamJeune_the_ajax_NamJeune_27']/div/div</value>
      <webElementGuid>a5fd26f6-f6a8-4cb8-8351-a2fc998e23d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom QPV'])[2]/following::div[5]</value>
      <webElementGuid>6e021557-66c6-49ca-b637-ddec13be6ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QPV'])[2]/following::div[9]</value>
      <webElementGuid>82e75f26-81eb-4ede-a2d6-15777188ead6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom de la banque'])[1]/preceding::div[7]</value>
      <webElementGuid>08aec2b6-b373-4dbe-a944-69b97c9b8b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>c054e107-8eb1-4dfe-9e0a-0b9b059888e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Coordonnées bancaires' or . = 'Coordonnées bancaires')]</value>
      <webElementGuid>a4adda58-c872-4076-bde2-829f22c26027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
