<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomCandidat</name>
   <tag></tag>
   <elementGuidId>d4fca7f6-ced4-4c70-b676-4cd32727efe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'field_namCanJenId__namNom' and @name = 'namCanJenId__namNom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namCanJenId__namNom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namCanJenId__namNom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namCanJenId__namNom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2010f3c-a95d-463f-9e6d-9c7e52efb559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>d3300427-7981-4c89-b12c-af9ddd384e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2b0c6a7-df83-428b-a179-453d93002934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namCanJenId__namNom</value>
      <webElementGuid>59515a86-51d7-42ec-9eff-00bbc0d9e842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namCanJenId__namNom</value>
      <webElementGuid>e11f4d20-b45c-4a30-9464-4b9d23f2ef7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f5c14c4d-d5b9-4801-846b-fc6351d2e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>352f8262-7423-4b9c-ae37-39dde97a7abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>dece336a-9bd7-4efe-b8c1-5dc71106f245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namCanJenId__namNom&quot;)</value>
      <webElementGuid>3c324f89-0ce0-44b9-93f9-a251728fb8de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namCanJenId__namNom']</value>
      <webElementGuid>d75a1e06-11f0-473f-9df0-e74382040280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area4']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>befadd9d-488c-4099-8425-82c58e7d5a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e3facdf9-3986-4060-a5d2-72d70f5e5c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namCanJenId__namNom' and @name = 'namCanJenId__namNom']</value>
      <webElementGuid>cd1e2657-6fac-40bd-b771-ef6388e1d2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
