<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ComplementAdresseJeuneRAA</name>
   <tag></tag>
   <elementGuidId>9e01b8d7-cdc2-4828-adb5-90ab150154ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAdresseCmpAdr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namAdresseCmpAdr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namAdresseCmpAdr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b2f0d08-2b21-4e09-bef4-7a4b152b2e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>031d6e4e-0819-49c9-9a86-d81c9193ee3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b1d1643-9a9c-4608-a41b-7340832978e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAdresseCmpAdr</value>
      <webElementGuid>c14f8a7f-1863-4bb4-80a1-11a42e68dc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAdresseCmpAdr</value>
      <webElementGuid>dc94fef7-f286-4de3-a6bd-b6f3daaa08d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4642b325-a993-4cfb-aa81-81e7b64b8e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e19f298f-2ff6-495a-8846-1e28ed4bb645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>abecca3d-e93f-4f69-ba5e-f4c5576a2efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAdresseCmpAdr&quot;)</value>
      <webElementGuid>b54df9fc-87fb-4c63-b819-bf257f9f74e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namAdresseCmpAdr']</value>
      <webElementGuid>24abca0e-b8a9-4849-a3ce-466befdae663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area2']/div/div[2]/div/div/input</value>
      <webElementGuid>c752e481-72d2-459b-9cd0-a0468ba5ce6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>031daf39-a486-41e5-8169-1c7134401eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namAdresseCmpAdr' and @name = 'namAdresseCmpAdr']</value>
      <webElementGuid>64fc3786-6dde-49a0-b61a-b116b1c32c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
