<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IBAN_CB</name>
   <tag></tag>
   <elementGuidId>84ca9e1f-0f1c-40ab-be5f-4f8115523fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJeuneIBANAtlAdm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJeuneIBANAtlAdm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJeuneIBANAtlAdm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a6a3cd-f893-4ab4-9601-deaadf5fae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>0d892054-a308-4b0c-9176-62e90a3174ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>810ecad3-ba66-48b4-b607-090743b800ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJeuneIBANAtlAdm</value>
      <webElementGuid>2f0de1f4-204e-488a-ae1e-b0448ab8c8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJeuneIBANAtlAdm</value>
      <webElementGuid>c08d4df0-ea54-4060-a410-67f0e4c2d36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2870e9ac-3f6f-41b8-8569-da063e022d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e41906bc-c0fe-4a57-b381-146e5046559a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>993fb4b7-3af2-4f2e-9a57-bb24073c36b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJeuneIBANAtlAdm&quot;)</value>
      <webElementGuid>3ea36bd5-8cf1-4f99-9594-3ad685d21145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJeuneIBANAtlAdm']</value>
      <webElementGuid>2def936d-a9d6-4e7a-b92d-750f590cb173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area27']/div/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>1d6ef22f-d5a7-4029-b3cb-7f0de3531d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>72ca9893-dbaa-4f27-a64c-8f7bd2b1ceb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJeuneIBANAtlAdm' and @name = 'namJeuneIBANAtlAdm']</value>
      <webElementGuid>16671845-2c5c-48e9-a7ac-0d1c4c8b45eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
