<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NumeroDeVoieJeuneRAA</name>
   <tag></tag>
   <elementGuidId>1914a3cd-ab4e-4ef4-99c2-0ae8694c7b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namNvoieAdr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namNvoieAdr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namNvoieAdr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>797240ce-c997-4ea1-a2eb-c47e81ad18ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>06ca8044-eed3-42b2-982b-67602328a8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0bdd0058-e5c2-4397-9bd1-0fb2637bd57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namNvoieAdr</value>
      <webElementGuid>8fe94c66-3fbf-444c-bbbf-32da26911913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namNvoieAdr</value>
      <webElementGuid>e8a502a7-f06c-4b6b-aa0a-dd7d16617e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e8b56334-46d0-447b-8264-65d966ec8719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a380927a-97e6-4842-92fb-47d31b212ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9fa56788-b360-48b2-ac84-b83f01b4a968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namNvoieAdr&quot;)</value>
      <webElementGuid>0742e0e9-adf0-4b9c-b00f-a3a83ab4ad7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namNvoieAdr']</value>
      <webElementGuid>5f1300fc-4c71-42e1-8451-879d1e70769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area2']/div/div/div/div/div/div/input</value>
      <webElementGuid>2c6caf48-db68-4545-8067-10000b88cf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d1f5c87a-ebb6-4584-8ecc-c66f6936d69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namNvoieAdr' and @name = 'namNvoieAdr']</value>
      <webElementGuid>372c88f9-f0cd-4b5d-abbd-d8e41de98b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
