<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DernierEtablissementScolaireFrequente</name>
   <tag></tag>
   <elementGuidId>a675b5b4-8e07-4537-b72a-77763ab370a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namDernierEtsFre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namDernierEtsFre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namDernierEtsFre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bbb732b-c59f-4821-b841-98737d691e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>5b53b09b-59fe-46b1-9c04-6487ca1e4784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8221261a-0e3d-47fa-a27c-d564be3f6429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namDernierEtsFre</value>
      <webElementGuid>26ff8a52-ca18-4869-9fb7-a23c60a72d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namDernierEtsFre</value>
      <webElementGuid>3ecbe827-48f0-4f49-99ee-247ec7decd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f24dda10-68d0-4895-a7d7-e0e71543935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3feb1044-620b-4588-aebc-abe384ee450c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ad568e40-3e6a-4974-9219-71170b518c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namDernierEtsFre&quot;)</value>
      <webElementGuid>0e7dac88-e257-4568-ad2e-1a174bf1201b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namDernierEtsFre']</value>
      <webElementGuid>364759ff-b630-4b69-9517-75e9dd4c2224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area9']/div/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>dea949ec-5f26-478d-bb6c-1914730146d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>42f62167-15b6-443b-badb-07e73307ddfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namDernierEtsFre' and @name = 'namDernierEtsFre']</value>
      <webElementGuid>9d17a674-c8bc-4008-bf2c-69bcba178472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
