<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmailJeune</name>
   <tag></tag>
   <elementGuidId>e3f23787-342d-48ff-bfc6-98b4576f703d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68f1ba9e-b19d-4834-a29c-aa53c25016e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62d19ff0-a28b-4afc-8b25-c52e42b1a854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2656574c-6c46-4dda-8af0-63487c07cc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namEmail</value>
      <webElementGuid>bc999ffa-b207-4a17-b5f1-38a91707fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namEmail</value>
      <webElementGuid>1d07247f-7824-4f41-859c-a38293a62a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6064215b-08b3-4754-91c7-48b6dbd80501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>98bacfcc-d1fa-4c3d-a95a-3b3e424ad359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>211dd3e9-9ff9-4eff-9920-d6051d6f02cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namEmail&quot;)</value>
      <webElementGuid>c71bf93e-71ad-419d-ba8c-6ec181c513d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namEmail']</value>
      <webElementGuid>e69983ad-744c-4928-bc58-c0f76365c3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[8]/div/div/div/div/div/input</value>
      <webElementGuid>6e302229-a6f8-41de-881b-20aee423696a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/input</value>
      <webElementGuid>cfc3e87a-e8c0-49e3-abe8-22060987ca1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namEmail' and @name = 'namEmail']</value>
      <webElementGuid>e8e78b0a-b857-48e9-923e-f03e4b7fa06c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
