<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateDeNaissanceJeune</name>
   <tag></tag>
   <elementGuidId>187ea312-db20-4c7a-85f9-23238d0ed727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namDateNaissance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namDateNaissance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namDateNaissance</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d63c9bf-5088-4aba-bfed-78d8b4d8192a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f45dce40-65bb-413b-94f2-0e202d83c4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c31f27f-1282-468b-b6b9-6ed2ac905743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namDateNaissance</value>
      <webElementGuid>8b7651d1-9150-4ca3-b302-c9d5d8cb245b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namDateNaissance</value>
      <webElementGuid>915d4ada-e162-42fa-ad23-e2ab6aec007b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a212185c-4877-46b7-a15b-4b1ff5d69b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b851ae1a-2a3b-4c6c-b79e-1aa6cc357770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>24149ecc-2a5a-403b-9954-5b9250b96664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namDateNaissance&quot;)</value>
      <webElementGuid>52e6a688-25b1-4ea6-8423-58c98d3e3116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namDateNaissance']</value>
      <webElementGuid>959d979f-cc41-475f-a0e4-257c0dca6c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>405b625f-84a0-48ff-9a0d-14dee0b53918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>f9d9a6df-acca-440b-86d6-832e76bb7206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namDateNaissance' and @name = 'namDateNaissance']</value>
      <webElementGuid>5e9a4ed9-d795-4869-ab7b-3d215fb542b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
