<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CodePostalJeuneRAA</name>
   <tag></tag>
   <elementGuidId>34cce88f-c838-4fc2-8699-68e6962d80c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namCpAdr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namCpAdr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namCpAdr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2aee10b-4562-489b-ae1f-71d2d757d2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>20185981-cded-4ff6-9c16-bd03677d5e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bad991f3-3d77-4be0-8451-a1de652fb8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namCpAdr</value>
      <webElementGuid>d7e5443f-a1f2-4104-a4f9-c580db5d092b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namCpAdr</value>
      <webElementGuid>2b40bbd8-fc94-4bb5-b7b8-8eb470722326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d2847059-7f2a-4b61-9bb2-cb84f591d9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47f10d82-a01b-41d8-a563-670e44296c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3e16f914-d14c-41fe-84e2-382ad39ce2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namCpAdr&quot;)</value>
      <webElementGuid>42a7d693-7be4-47e4-abe5-81c7e6cc81cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namCpAdr']</value>
      <webElementGuid>a1c15342-f417-40ae-9d66-9e4c28780cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area2']/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>727b8ad7-3ee2-4816-8eb7-ce6c3e1a24b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>1d629c71-fa1e-4795-b57d-df8f8c1893e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namCpAdr' and @name = 'namCpAdr']</value>
      <webElementGuid>7f13d7b2-55b2-4f6a-ba60-8980249c991c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
