<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_NationaliteJeune</name>
   <tag></tag>
   <elementGuidId>72154d3f-e7c8-49d1-b588-298e43380930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namNationalite-container > div.enum-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namNationalite-container']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nationalité française&quot;i >> internal:text=&quot;Nationalité française&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37df6f79-c94b-4e73-a4f0-104fd76b345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nationalité française</value>
      <webElementGuid>256e36c2-f71b-46c1-923f-0ff09d5d9a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namNationalite-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>b9db5ed6-9fa9-42f7-8afb-2c956bb97da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namNationalite-container']/div/span</value>
      <webElementGuid>719f0d7c-4c25-411c-a8b1-238033a47335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationalité'])[2]/following::span[5]</value>
      <webElementGuid>2edb104f-175b-47d8-982c-fd644ece4889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[2]/following::span[12]</value>
      <webElementGuid>eef86ddc-b857-4504-9222-75f94fe62804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pays de résidence'])[2]/preceding::span[3]</value>
      <webElementGuid>857c92ae-1b7d-4b1e-a79a-a8c93976c531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::span[3]</value>
      <webElementGuid>8cd80c45-2f9f-431c-8a28-c535c55d08dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/span/span/span/span/div/span</value>
      <webElementGuid>b2fb673f-5149-4d1d-8cc5-7765caf60ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nationalité française' or . = 'Nationalité française')]</value>
      <webElementGuid>492e757d-5c49-463c-94c6-d1f510e4e84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
