<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_Transmis</name>
   <tag></tag>
   <elementGuidId>9d264b4a-bdaf-490d-bdae-9e9cd40ffcad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Transmis' or . = 'Transmis')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamDocAdministrative_panel_ajax_NamDocAdministrative_namDocadminJenId']/div/div[2]/form/div/table/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.greenbg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Transmis&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>27aebba9-51a2-4c2d-acf5-c842de8f35dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>namDocadminEtatTransmission</value>
      <webElementGuid>3d240472-83cf-4e12-acd1-cb423dae7361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>greenbg</value>
      <webElementGuid>504de273-7b60-4c89-80a5-503298e82afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transmis</value>
      <webElementGuid>daddc62a-e6be-4b1e-b279-6db5eaef6b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamDocAdministrative_panel_ajax_NamDocAdministrative_namDocadminJenId&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[@class=&quot;greenbg&quot;]</value>
      <webElementGuid>be4ca990-3270-495e-bb15-973b7e1cb2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamDocAdministrative_panel_ajax_NamDocAdministrative_namDocadminJenId']/div/div[2]/form/div/table/tbody/tr/td[4]</value>
      <webElementGuid>0388e4b3-c49b-4ee1-b729-c552b1cea957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photocopie recto-verso de la CNI'])[1]/following::td[1]</value>
      <webElementGuid>ee9df8e8-7062-4c51-817f-4925ca8ca9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obligatoire'])[2]/following::td[2]</value>
      <webElementGuid>4921325a-ee3d-426f-b5e9-008ed9ff522c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 1'])[2]/preceding::td[4]</value>
      <webElementGuid>641e8b7d-7183-43cb-936e-7ec91fbafc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/table/tbody/tr/td[4]</value>
      <webElementGuid>41384eb9-264d-4167-a79d-18e78136bef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Transmis' or . = 'Transmis')]</value>
      <webElementGuid>cb350540-cef5-4054-9a0d-a89fbdda67fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
