<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_ET_Transmis</name>
   <tag></tag>
   <elementGuidId>ccaa653c-a1e6-4ca1-9714-3caa28ac2dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namDocadminEtatTransmission-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namDocadminEtatTransmission-container > div.enum-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Transmis&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd5b7d0f-9b88-4ec0-9a0a-9e7019e0cbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>2cd4392b-71a3-4ad2-bb05-2c231221a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transmis</value>
      <webElementGuid>7148f33e-1c81-4823-b138-ce3459c2bdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namDocadminEtatTransmission-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>2622c195-6d0f-4232-b0ea-eba7d291d991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namDocadminEtatTransmission-container']/div</value>
      <webElementGuid>13ba4b8d-2b16-4310-88a1-25ca252464e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etat de transmission'])[1]/following::div[1]</value>
      <webElementGuid>8a1408e8-f742-42e9-8849-864a96e4a40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de fourniture'])[1]/preceding::div[1]</value>
      <webElementGuid>45a68e5b-3a5f-4535-8d79-32be4065fe61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/span/span/span/div</value>
      <webElementGuid>6dadaa03-92e7-40d1-af07-e9ff3246c951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Transmis' or . = 'Transmis')]</value>
      <webElementGuid>19111cbd-12d8-414e-857d-8c4310ce67e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
