<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_CNI_exem</name>
   <tag></tag>
   <elementGuidId>76b19a43-ab3a-4d81-97bb-17c8d8f32c57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamTypeDocument_ref_ajax_NamTypeDocument']/div/div[2]/form/div/table/tbody/tr/td[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-left.breakword.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Photocopie recto-verso de la CNI&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ddfed76-a7fe-49ec-8407-5ac4c69737a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left breakword text</value>
      <webElementGuid>0343a281-d36c-4917-aa8f-029d3d7df8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photocopie recto-verso de la CNI</value>
      <webElementGuid>1d8d4241-fe85-4ba8-a179-1fd21160237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamTypeDocument_ref_ajax_NamTypeDocument&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[3]/div[@class=&quot;text-left breakword text&quot;]</value>
      <webElementGuid>471db5ce-429b-4ba1-b0f2-4b3da84eac24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamTypeDocument_ref_ajax_NamTypeDocument']/div/div[2]/form/div/table/tbody/tr/td[3]/div</value>
      <webElementGuid>8991bd9d-1769-4afc-8cd4-a3651c71f9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oui'])[4]/following::div[1]</value>
      <webElementGuid>ac266d9c-ad44-471a-8670-1131864f4d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[1]/following::div[5]</value>
      <webElementGuid>a3aab7a3-b365-4554-9156-e12b58e97c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obligatoire'])[4]/preceding::div[1]</value>
      <webElementGuid>915c86e3-ec5d-4672-84b8-7195581783e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oui'])[5]/preceding::div[3]</value>
      <webElementGuid>aecc1924-ee09-495d-ad70-3b2c7f7773dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Photocopie recto-verso de la CNI']/parent::*</value>
      <webElementGuid>6e4c178c-611b-4247-826d-bae37134c6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>63ba6973-35a9-4ab8-ab59-667db87cdc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Photocopie recto-verso de la CNI' or . = 'Photocopie recto-verso de la CNI')]</value>
      <webElementGuid>e7d0903e-a448-4bcb-99cc-bf5bc68cd24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
