<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Libelle_Type_Document</name>
   <tag></tag>
   <elementGuidId>d6e55c74-654e-4e7b-9ca9-7adeac618540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namTdocLibelle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namTdocLibelle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namTdocLibelle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14cc4dda-9a4e-4935-b51a-8ac7cc9aee01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>0aae4ecb-ad58-45bf-91dd-1525e3d86172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namTdocLibelle</value>
      <webElementGuid>69a5d953-c9c3-4f98-b3fb-a8456d8049bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2f54c4c-8baf-4054-a8f4-7790cc68630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namTdocLibelle&quot;)</value>
      <webElementGuid>d7780b8e-12f1-48dd-8d15-36af13099435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namTdocLibelle']</value>
      <webElementGuid>d36ecd9c-be58-480f-9f53-50812dad131f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamTypeDocument_ref_ajax_NamTypeDocument']/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>f2e591b4-f076-40db-9e77-4defef9f8f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/input</value>
      <webElementGuid>9ff7faa9-7063-488d-8f3a-16bd502d6ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namTdocLibelle']</value>
      <webElementGuid>c619ced2-de56-4d15-9efc-d931b6d34639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
