<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_COF1</name>
   <tag></tag>
   <elementGuidId>a66a015d-cc80-4b88-bae7-842b67afcd1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@data-field='namCofNumero']//div[normalize-space(text())='COF1']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-left.enum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;COF1&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8a9424d-bfcd-41fb-ab8f-d754027912a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left enum</value>
      <webElementGuid>51ce0145-350c-491d-820c-865152f4e2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COF1</value>
      <webElementGuid>6476b7d6-57e0-41ec-b13b-7ff3c41e73fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamCof_the_ajax_NamCof&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[4]/div[@class=&quot;text-left enum&quot;]</value>
      <webElementGuid>f73363a6-1094-4b15-8ebd-c3acfecf65e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamCof_the_ajax_NamCof']/div/div[2]/form/div/table/tbody/tr/td[4]/div</value>
      <webElementGuid>a09d1f79-16fa-4ca1-9ad4-d7eaab449fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bordeaux'])[1]/following::div[2]</value>
      <webElementGuid>99ab1253-79f5-44a8-8fc6-c821c4b7f4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section 1'])[1]/preceding::div[2]</value>
      <webElementGuid>9d8d229c-e469-4b38-a9e5-26a307ee7480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRATKatalonNom2'])[1]/preceding::div[3]</value>
      <webElementGuid>b603153b-a3c1-46ed-81a5-ca6ed13d8967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div</value>
      <webElementGuid>abc0fcbc-5168-471d-ac91-6b6cc8316c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'COF1' or . = 'COF1')]</value>
      <webElementGuid>13fc6557-e33f-4565-8ff3-d8638fc901df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
