<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SyntheseGlobaleCOF3</name>
   <tag></tag>
   <elementGuidId>a9a00abc-961a-425a-ae46-210b683ec323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namCofSyntheseGlobaleTr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namCofSyntheseGlobaleTr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namCofSyntheseGlobaleTr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4f2d0ec8-2786-419a-b16d-e67bcd4f7ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>341072c6-431d-4b98-891b-fa593785a122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namCofSyntheseGlobaleTr</value>
      <webElementGuid>a9f88ddc-ee43-4be8-9962-6daf4bb66d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namCofSyntheseGlobaleTr</value>
      <webElementGuid>4b7e1d01-d15c-4390-ad3f-fa4087335f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d12c80ca-3201-4d98-bf48-75e3d2745d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>820535e0-48f1-4473-8ed6-dd620a7bfb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namCofSyntheseGlobaleTr&quot;)</value>
      <webElementGuid>decb3b9c-e5a9-45be-8841-6a80ef351824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namCofSyntheseGlobaleTr']</value>
      <webElementGuid>cefeab84-95cd-4acb-a74a-3fea77e0a73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area9']/div/div/div/div/textarea</value>
      <webElementGuid>4a294e0b-2b54-404d-9b63-f6bf20cb28f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div/div/textarea</value>
      <webElementGuid>c08101cd-3817-40c7-9b84-2ddda240caa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namCofSyntheseGlobaleTr' and @name = 'namCofSyntheseGlobaleTr']</value>
      <webElementGuid>56ea10b4-3b19-414d-bd7c-2bf9cfc32b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
