<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_COF</name>
   <tag></tag>
   <elementGuidId>6cb9f41d-9ad3-4a45-a96b-062ee333b80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.sub-menu > li.active > ul.sub-menu > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/nav/ul/li/ul/li[5]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xpath=//a[normalize-space()='COF']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f67dd8b-5317-494d-9a32-ba28ddadd333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-obj</name>
      <type>Main</type>
      <value>NamCof</value>
      <webElementGuid>0ad4df0b-028b-40c4-95dc-0bc0701fbfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>e95c9c9e-5901-4ae7-bd9d-a3fed2585b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COF</value>
      <webElementGuid>e69c8c42-cf1c-42d7-a909-7e0355bfc1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;main-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>947431d8-a347-4b68-a81e-d0a95aefb139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/nav/ul/li/ul/li[5]/ul/li[4]/a</value>
      <webElementGuid>ab56b44b-7a75-4809-83b9-3e85bf65a1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réunion de section'])[1]/following::a[1]</value>
      <webElementGuid>d179a8cc-2a86-4066-8400-20966d5e4da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feuille de présence'])[1]/following::a[2]</value>
      <webElementGuid>39570477-b9d2-4801-8376-4cddb74441f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projets professionnels'])[1]/preceding::a[1]</value>
      <webElementGuid>4b0ed8d9-aec6-42b5-8af4-2baca76e7eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[18]</value>
      <webElementGuid>cd709793-8681-4dec-bea8-a0dab989b7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[4]/a</value>
      <webElementGuid>add6487d-fa5c-4f84-aa4a-c4a1bfb996e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'COF' or . = 'COF')]</value>
      <webElementGuid>467340ba-c9a4-4ce5-a314-47069c3a851a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
