<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Statut_Valide</name>
   <tag></tag>
   <elementGuidId>d46a11e1-df14-48e4-87ab-0d3f7ff79ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namCofStatut-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namCofStatut-container > div.enum-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Validé&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0934e0dd-c29e-40b1-9e7e-80678bbe6674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>d213faed-c92a-4284-a666-e5755d513ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validé</value>
      <webElementGuid>371350c5-8084-4d37-90c5-75b933b087be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namCofStatut-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>dcea9581-7927-4c31-bd91-09c2402530f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namCofStatut-container']/div</value>
      <webElementGuid>07b9bf0d-2afe-430a-b83e-a2731257cf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut du COF'])[1]/following::div[1]</value>
      <webElementGuid>fa5a9e83-5eb3-46b7-83d6-f1959f9bfb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COF2'])[2]/following::div[5]</value>
      <webElementGuid>54cf3eda-d6ce-4b50-a283-d47b4497eed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volontaire'])[1]/preceding::div[1]</value>
      <webElementGuid>18803bc8-6e40-49c4-91bc-f7401215ebaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span/span/span/span/div</value>
      <webElementGuid>e57eebf8-6430-4841-8d07-c99c0c533bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Validé' or . = 'Validé')]</value>
      <webElementGuid>57a2c382-bb0e-4472-93c6-c675c198e095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
