<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Statut_EnCours</name>
   <tag></tag>
   <elementGuidId>6067567a-1fc0-4b2c-b869-670dd899e247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namCofStatut-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namCofStatut-container > div.enum-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;En cours&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>502c81e3-9c93-4418-9c6a-d15db3c7d750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>862c3cd3-d258-40f3-8f50-da40f47515a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En cours</value>
      <webElementGuid>b1086ae1-41c0-4d2a-acbb-01108af5d003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namCofStatut-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>d4623203-5822-4b74-ab06-cd7548ed6c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namCofStatut-container']/div</value>
      <webElementGuid>ec32907f-896e-43ac-a67a-5fcf01e37071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut du COF'])[1]/following::div[1]</value>
      <webElementGuid>543243b8-8f00-414e-901c-b8bdc6f9c491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COF1'])[2]/following::div[5]</value>
      <webElementGuid>f368767c-43c8-4070-9f50-a2f83da780c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volontaire'])[1]/preceding::div[1]</value>
      <webElementGuid>23a0500f-6ab3-491d-b0aa-1e842d27e561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span/span/span/span/div</value>
      <webElementGuid>1a92f8df-13e1-4774-9330-db9eb5dcb928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'En cours' or . = 'En cours')]</value>
      <webElementGuid>9035d89b-754d-4734-a04c-34cc0308a8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
