<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AR_Selec_Prenom</name>
   <tag></tag>
   <elementGuidId>bae6c1ab-297d-4894-abd8-4177a3a1cd85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namPrenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namPrenom_searchby']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namPrenom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89e3f1a0-c0b8-4855-a017-0ae19b6cb6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>943abd84-c8e0-424c-b8e1-e1217fa91609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namPrenom</value>
      <webElementGuid>ce92fbcf-a71b-4d93-b5e8-3ce4f0df3b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TRAprenom</value>
      <webElementGuid>816bbb4f-5b89-4e89-8934-0af6e2af44e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93932ba6-1a58-4ff3-9999-1500b33e821f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namPrenom&quot;)</value>
      <webElementGuid>54c396ca-2d10-44f7-a4c5-f1bc5955b13e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namPrenom']</value>
      <webElementGuid>5cf7b5db-7989-403e-9630-cabe05abc208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>106395ed-c510-4c21-8268-dec7609f985f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>c5123f51-dd0e-4a21-b492-b174ee2ccc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namPrenom']</value>
      <webElementGuid>034f596e-33d3-40a5-8050-3565268aa5d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
