<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SoumettreDG</name>
   <tag></tag>
   <elementGuidId>01b5cce9-b54a-41bb-877e-0d985363cdab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-action.action-not-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Soumettre à la DG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efb91aa4-9802-46af-b3b8-efbc972919a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfde4173-5aca-42a4-9a63-7b85166a4e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action action-not-xs</value>
      <webElementGuid>670a555b-903d-4489-82cd-6a0d06b54b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>NAM_SOUMETTRE_DG</value>
      <webElementGuid>c2bcb4df-c1a1-47de-94ec-de8747412ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowid</name>
      <type>Main</type>
      <value>449</value>
      <webElementGuid>9f438f28-b521-49c7-b6bc-a520f7c89a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Soumettre à la DG</value>
      <webElementGuid>418ec3cf-7ace-4bf8-9227-20ffa7ee56f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_NamDemandeTransfertCentre_the_ajax_NamDemandeTransfertCentre_449&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;head&quot;]/div[@class=&quot;form-actionbar&quot;]/div[@class=&quot;actions pull-right&quot;]/button[@class=&quot;btn btn-action action-not-xs&quot;]</value>
      <webElementGuid>19399089-b1b3-451e-8c8a-d59aee94c71f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d6215683-5145-4f80-b873-09cb62f47737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamDemandeTransfertCentre_the_ajax_NamDemandeTransfertCentre_449']/div/div/div/div[2]/div/button</value>
      <webElementGuid>b9584206-ceab-49dc-af50-6caf08686e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demandes de transfert : 20/11/2025 TRATKatalonNom1 TRATKatalonPrenom1 0 08/07/20...'])[1]/following::button[1]</value>
      <webElementGuid>e1fd5b9d-77cd-4cf4-b32d-93eb6ff2886f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demandes de transfert : 20/11/2025 TRATKatalonNom1 TRATKatalonPrenom1 0 08/07/2005'])[1]/following::button[1]</value>
      <webElementGuid>d3f0a357-4c73-435b-bac3-799b3b880988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supprimer'])[1]/preceding::button[2]</value>
      <webElementGuid>203b7e33-40cf-4d71-92c8-c45dd39278b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>c8ce8f7a-4f8e-4d2c-9968-409b1b15d01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Soumettre à la DG' or . = 'Soumettre à la DG')]</value>
      <webElementGuid>8db7661f-331d-4048-9d60-50b7f6940041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
