<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_Ville_Choix</name>
   <tag></tag>
   <elementGuidId>1e800d0e-1562-4323-a7ef-d4bc35c443c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > div.text-left.breakword.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamCentre_ref_ajax_NamCentre']/div/div[2]/form/div/table/tbody/tr/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Lanrodec&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1807c7b1-1e0f-4af7-bc1b-55d4e56f3281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left breakword text</value>
      <webElementGuid>5bef6e31-0943-4dfc-a2ec-54711ef17846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanrodec</value>
      <webElementGuid>4ad75530-2ef3-4b76-923d-07313aa6c0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamCentre_ref_ajax_NamCentre&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[3]/div[@class=&quot;text-left breakword text&quot;]</value>
      <webElementGuid>308d03a5-3895-4e81-a1b9-ee43ecd4c191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamCentre_ref_ajax_NamCentre']/div/div[2]/form/div/table/tbody/tr/td[3]/div</value>
      <webElementGuid>ad559fc7-9541-4e0f-846f-d15ff15e7dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZERRAF'])[1]/following::div[1]</value>
      <webElementGuid>c9a5845e-d207-41eb-bd9f-9f86354329a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ville'])[1]/following::div[5]</value>
      <webElementGuid>b9b77bd8-e17e-478b-9ee9-94e894d0e51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LANR_VI'])[1]/preceding::div[2]</value>
      <webElementGuid>a8e2ef33-1344-499e-894b-733fe9a08ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LANRODEC'])[1]/preceding::div[6]</value>
      <webElementGuid>ea2a7270-a3b2-41b5-b296-761971f66153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanrodec']/parent::*</value>
      <webElementGuid>ad45237d-69e5-4c8e-bafa-d9664a9e13f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>285aac4c-3625-4e94-af9f-4b3046eec4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lanrodec' or . = 'Lanrodec')]</value>
      <webElementGuid>c404102c-2ec4-440b-84f9-0ae7dfa3f9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
