<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BesoinHebergement</name>
   <tag></tag>
   <elementGuidId>01884178-6792-4404-a841-aae73d5239af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namDtcBesoinHebergement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namDtcBesoinHebergement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namDtcBesoinHebergement</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1dfc7dc6-ea16-4642-aede-d0d12f5e67ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>0a61879f-94f5-4f19-94fd-64be2434b63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namDtcBesoinHebergement</value>
      <webElementGuid>7123b088-1f0c-4c45-a2ee-76ec75287b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namDtcBesoinHebergement</value>
      <webElementGuid>f959eca2-2a3a-4d12-8b88-029469668f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>dd475dac-b51c-452b-b96b-fb77ac3b180d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>58d47940-5662-4d0a-af02-f7b9b0f79f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namDtcBesoinHebergement&quot;)</value>
      <webElementGuid>e55b5855-18d3-4591-bdba-8fa88d5ae045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namDtcBesoinHebergement']</value>
      <webElementGuid>f987bf51-75c8-42ba-ad78-97f9ec841b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[6]/div/div/textarea</value>
      <webElementGuid>6388f811-00fe-4255-8fb7-1e9971c688ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>8304e611-01d1-4f81-b5ab-4f8976990b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namDtcBesoinHebergement' and @name = 'namDtcBesoinHebergement']</value>
      <webElementGuid>13ff1dc5-4f2e-489e-9f2f-4d7cd4f2d11b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
