<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BesoinPaquetage</name>
   <tag></tag>
   <elementGuidId>8f1d18f9-999e-4ddf-9f71-e2ed8b410120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namDtcBesoinPaquetage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namDtcBesoinPaquetage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namDtcBesoinPaquetage</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f9a1e9e1-b208-4617-a084-67df0fc95d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>0b5296df-d1b6-4251-95c6-5483f25757fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namDtcBesoinPaquetage</value>
      <webElementGuid>5c2f7a19-1e6b-4f8b-b043-d71c0aff94da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namDtcBesoinPaquetage</value>
      <webElementGuid>9d6eaf2c-fe36-48ae-a449-d11ed4d59bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>b63015af-e82c-457a-a876-b9d772b387ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>cc01f8e2-914c-4c50-8c94-82244fbba472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namDtcBesoinPaquetage&quot;)</value>
      <webElementGuid>244183d6-6df8-4634-a90c-0c863ecc7ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namDtcBesoinPaquetage']</value>
      <webElementGuid>9b123382-6e9d-493d-98c5-eee299ab948b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[7]/div/div/textarea</value>
      <webElementGuid>97681416-c6c4-4807-af06-08e0d86801c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/textarea</value>
      <webElementGuid>6d25e2ee-579c-41ec-888d-b0e43a0ab9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namDtcBesoinPaquetage' and @name = 'namDtcBesoinPaquetage']</value>
      <webElementGuid>05634bc8-cd59-428f-af94-9d83519f669b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
