<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selectionner_CentreEPIDE</name>
   <tag></tag>
   <elementGuidId>80f53a59-b6ca-40df-88aa-b70fe1d73a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namNomCentre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namNomCentre']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'namNomCentre' and @expectedValue = 'Lanrodec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namNomCentre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb7b7341-38b7-4a80-ad72-0d92ba222ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>8056b988-ccf6-40c4-bf62-3c1f6ae08749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namNomCentre</value>
      <webElementGuid>e150c25a-157b-41fb-991e-f90f63b2912a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f7857be-e283-4111-9664-64fc4240fbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namNomCentre&quot;)</value>
      <webElementGuid>67f3d7aa-bfe1-47ef-b712-bb7db2353576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expectedValue</name>
      <type>Main</type>
      <value>Lanrodec</value>
      <webElementGuid>b2a299bb-0c31-4cf9-a12d-d8fda6db1207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namNomCentre']</value>
      <webElementGuid>75e29683-6c97-4294-8a18-3c9333417151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamCentre_ref_ajax_NamCentre']/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>996993b8-2b60-483f-9344-c906aa3f7714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/input</value>
      <webElementGuid>b90c2917-361a-4eb2-bb71-3ab3f72de55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namNomCentre']</value>
      <webElementGuid>5fc7c3c5-0b95-43d6-9961-818d6dc446ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
