<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Avis_Observation</name>
   <tag></tag>
   <elementGuidId>fb62bf05-f84c-40a3-84df-9dd35a3c3bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAvtransfertObservation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namAvtransfertObservation']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'field_namAvtransfertObservation' and @name = 'namAvtransfertObservation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namAvtransfertObservation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e746c34d-727e-4b49-8eaa-61f6c20cf757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>822f75b8-83d7-4051-ad59-aa3797b32070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAvtransfertObservation</value>
      <webElementGuid>068a85e9-4fc7-4289-b5b5-c9f94089bd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAvtransfertObservation</value>
      <webElementGuid>888f4cec-795f-474e-a469-9c7e9f0b3f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>793bd21f-1522-4132-b321-823630750e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>18a21513-a8d7-4ae9-9109-8c60d55db110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAvtransfertObservation&quot;)</value>
      <webElementGuid>9bc79a17-1f54-4b81-8b50-04e977ee4fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namAvtransfertObservation']</value>
      <webElementGuid>7f285dab-f7f9-4c30-84db-c410c72d1b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[3]/div/div/textarea</value>
      <webElementGuid>80e5027c-fa63-476e-b0f0-8fbce3a00458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>72346f94-6a28-48c5-9f79-f92961b207de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namAvtransfertObservation' and @name = 'namAvtransfertObservation']</value>
      <webElementGuid>73325786-3a57-4952-9efa-13637482b5eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
