<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateTransfertSouhaitee</name>
   <tag></tag>
   <elementGuidId>4afd975f-087d-4322-9f76-4fc561511138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namDtcDateTransfertSouhaite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namDtcDateTransfertSouhaite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namDtcDateTransfertSouhaite</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2225793-2104-4604-8bf5-ed7965771927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0ec3dc45-d47b-4e67-9984-09dc7de0fa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>378580ea-c94c-4697-aac0-bd00092a2a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namDtcDateTransfertSouhaite</value>
      <webElementGuid>d8da6367-0034-4dc7-9d71-0d7c7a0e7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namDtcDateTransfertSouhaite</value>
      <webElementGuid>153be823-1400-4898-8ddb-4b00f619cd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>898fec55-ffaf-4688-ae3a-079e8b2b17c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd425465-63ef-47b6-8fce-5da6e60fd8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5f4e929f-f167-44bc-be8a-e8cde9217a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namDtcDateTransfertSouhaite&quot;)</value>
      <webElementGuid>3cb98db1-d4d2-41dd-a0c9-163d6fb5b794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namDtcDateTransfertSouhaite']</value>
      <webElementGuid>eff7a3a3-440a-45ff-9a28-8ee3dd0d80fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[4]/div[3]/div/div/div/div/input</value>
      <webElementGuid>64a5a9d7-b93b-4ee3-a5df-d2ad8bb048f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>e7556c6e-1b38-41e2-a43c-0849b3366bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namDtcDateTransfertSouhaite' and @name = 'namDtcDateTransfertSouhaite']</value>
      <webElementGuid>de3e247a-0aa9-4da1-825a-fe08e3e9398a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
