<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prenom_select_jeune</name>
   <tag></tag>
   <elementGuidId>d05c0859-aa3e-41ef-a247-4d2e2d4c10ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;f_list_NamJeune_ref_ajax_NamJeune&quot;] > div.container-table.table-responsive > table.table.table-striped > thead > tr.search > th:nth-of-type(3) > div.input-group.searchby.flex-nowrap > #namPrenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namPrenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;   Depuis   Jusqu'à     &quot;i] >> #namPrenom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3cdb550-102a-4be3-90c2-f393310558cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>bbd90f21-ac1c-49be-8b58-c95a16d96747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namPrenom</value>
      <webElementGuid>e72c7928-1f63-48e0-8806-b8e257c2a53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>trat*</value>
      <webElementGuid>84576d2b-8396-4090-905a-4befb86a98f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e692bfa5-2760-40f5-9877-7f637859e7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamJeune_ref_ajax_NamJeune&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/thead[1]/tr[@class=&quot;search&quot;]/th[3]/div[@class=&quot;input-group searchby flex-nowrap&quot;]/input[@id=&quot;namPrenom&quot;]</value>
      <webElementGuid>c2ac383a-9c56-4194-a884-9e68a958483e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='namPrenom'])[2]</value>
      <webElementGuid>e97a9f0c-efc6-44e1-9d98-a41ce294b416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>98920a00-db6a-415e-a6d9-88b10f7e2c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>78c172fd-2207-4990-94f7-2417c1b7f3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namPrenom']</value>
      <webElementGuid>66f9e6f0-9287-4141-bf38-13cb48afe9dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
