<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_OrganisationdesCentres</name>
   <tag></tag>
   <elementGuidId>c1592940-44b7-479d-9d5b-5e2b6ed7459c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > a.js-sub-menu-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/nav/ul/li/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xpath=//a[normalize-space()='Organisation des centres']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe6e0994-96b4-4e4d-8e3b-8f38b66702f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-domain</name>
      <type>Main</type>
      <value>NamDomaineCentre</value>
      <webElementGuid>0939ba5f-3654-4296-b031-011d86350530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-sub-menu-toggle</value>
      <webElementGuid>dd0268c8-0f4f-4946-a141-b312e3874762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organisation des centres</value>
      <webElementGuid>2b7a24a7-f1e4-481e-935c-a30fcb9997ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;main-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[8]/a[@class=&quot;js-sub-menu-toggle&quot;]</value>
      <webElementGuid>3112aa52-aabb-42ce-b730-c18e2e617fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/nav/ul/li/ul/li[8]/a</value>
      <webElementGuid>594572bd-923e-4245-867c-8927694e5cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primes'])[1]/following::a[1]</value>
      <webElementGuid>e019fb02-ac1b-4916-9383-d15b882ed27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retenues financières'])[1]/following::a[2]</value>
      <webElementGuid>07033a95-a238-4c9b-8a73-c15b3de7e458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centres'])[1]/preceding::a[1]</value>
      <webElementGuid>21f56428-81e7-4e3d-add4-f97606723f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[31]</value>
      <webElementGuid>51981dff-d399-4a99-9abb-1b0a0704e6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>efe7b10e-37f0-4f15-822e-49b50689265d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Organisation des centres' or . = 'Organisation des centres')]</value>
      <webElementGuid>51f3f0e2-2c26-47d2-9463-6ff6dbc23f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
