<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VerifierAdresse</name>
   <tag></tag>
   <elementGuidId>0ed394b4-7e24-4e59-b9d9-3849765fa390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify-address-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='verify-address-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;VÉRIFIER ADRESSE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce688263-7ee0-4ead-89c2-f178fc1c9237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify-address-btn</value>
      <webElementGuid>673bc8f6-6e9a-4d9e-95e9-2eb0d7050d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epide-button</value>
      <webElementGuid>f237976d-0697-477c-bcb2-e9f141ea1766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VÉRIFIER ADRESSE </value>
      <webElementGuid>ccd0ffda-a9ec-4d35-b336-6836b982f6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify-address-btn&quot;)</value>
      <webElementGuid>0be930d1-23a2-4a36-b7d0-f91c121c2c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='verify-address-btn']</value>
      <webElementGuid>e83964ba-c421-4ba0-a462-e5a16667a0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-contact-form[@id='epide-contact-form']/div/form/div[2]/div[7]/div/button</value>
      <webElementGuid>3955b7aa-46dc-4d59-8a7b-1793f173f99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veuillez entrer votre ville'])[1]/following::button[1]</value>
      <webElementGuid>b70d2ed2-bb58-4535-bc1a-98f11ae1b645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::button[1]</value>
      <webElementGuid>7c04917a-d0c9-431f-a909-3729227df834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FORMATION DU CANDIDAT'])[1]/preceding::button[1]</value>
      <webElementGuid>304cd876-61e3-4e46-94c6-5489394226df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VÉRIFIER ADRESSE']/parent::*</value>
      <webElementGuid>8283fdcf-47be-491a-8f10-1c789eaf812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1c2956e0-919b-49c7-be77-5ddd1a3a8133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'verify-address-btn' and (text() = ' VÉRIFIER ADRESSE ' or . = ' VÉRIFIER ADRESSE ')]</value>
      <webElementGuid>a3e46d51-4818-483d-8d1e-b7fb8b430700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
