<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_AcceptRGPD</name>
   <tag></tag>
   <elementGuidId>f2428f88-db98-4347-9ee4-985f5bd8f631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptRGPD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptRGPD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;J'accepte que ces données soient utilisées par l'EPIDE dans le cadre de mon dépôt de candidature *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0017e2c-91df-4089-9c79-48e1c2eef019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptRGPD</value>
      <webElementGuid>708363bd-05c9-456c-86d7-e6c3b75aa4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1fbfe52f-768d-46e2-bf91-9c2ffc2a1b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptRGPD</value>
      <webElementGuid>5045ef19-d252-4a26-a4ad-abc48a469ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>df675a42-32f3-4764-adde-70c2f5fa6521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptRGPD&quot;)</value>
      <webElementGuid>5f8452cf-53cf-4206-af51-32551c20b68b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptRGPD']</value>
      <webElementGuid>46717786-6515-47c2-b42c-37e44a6037ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/div/input</value>
      <webElementGuid>1c118d5f-38a0-4527-a52c-9742e17c4702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'acceptRGPD' and @type = 'checkbox']</value>
      <webElementGuid>d5ffcdc6-7568-4568-8cbd-0f724dc9c4ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
