<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateNaissance</name>
   <tag></tag>
   <elementGuidId>500441cb-ded5-4b09-85dc-c4644fd66196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;jj/mm/aaaa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94b3fc73-4587-4017-a880-64b58a37fbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday-input</value>
      <webElementGuid>07fb8eee-bd8c-4e6d-b260-efad5d36d4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>053c11dc-503c-4696-9867-ca998713263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>563ecdb5-39e2-4b49-a0fc-2b4b760bd105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>368247c1-049d-44b7-abd2-e2201cfc2eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>jj/mm/aaaa</value>
      <webElementGuid>49a2613d-eef6-4e3c-b730-9335358670ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>90e573c0-2e1e-4946-9c70-b606b3462652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>3788305a-3740-40b6-b27e-7fe7a9956b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2025-12-03</value>
      <webElementGuid>8d00e02c-4c8d-4370-b2cb-ec9ca22792f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid input-error ng-touched</value>
      <webElementGuid>f134b578-bbbc-48d2-9f63-85b01fcc9912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday-input&quot;)</value>
      <webElementGuid>c1dcbf07-b7a4-40fd-928f-52ce098cec79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday-input']</value>
      <webElementGuid>81c0ba3f-41ca-45b2-a592-ccb073fdaeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-identity-form[@id='epide-identity-form']/div/form/div[4]/div/input</value>
      <webElementGuid>df8d44e3-f960-4b7c-8065-dd4c08a404d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>16fddaa3-e6d6-4d8a-9fab-cbbf407d17cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthday-input' and @type = 'date' and @placeholder = 'jj/mm/aaaa']</value>
      <webElementGuid>a38e9575-329b-4e64-a7b3-76b05a9347b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
