<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TelephonePortable</name>
   <tag></tag>
   <elementGuidId>da98c1ae-ca0a-4315-b802-cec5912a4426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cellphone-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cellphone-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;06 32 77 90 80&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeb228ed-ca10-4009-90df-606f28f0284b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a415799c-6868-46cc-8949-3e1996a30af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cellphone-input</value>
      <webElementGuid>88005e30-cc9c-405b-9e70-fa0c2d23fa55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cellphone</value>
      <webElementGuid>44a825b0-fb8c-4670-9d84-190fe0e1830a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>06 32 77 90 80</value>
      <webElementGuid>ee231f86-7392-4afa-909c-0842d9f44b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cf887771-9b58-43df-8265-1db94d6cbeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2c4ff942-c977-49b8-a67b-a966f56347ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cellphone-input&quot;)</value>
      <webElementGuid>486f7271-2e68-4df9-826a-389292295893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cellphone-input']</value>
      <webElementGuid>579a6543-6ae3-4400-aafe-27fd019be837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-contact-form[@id='epide-contact-form']/div/form/div/div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>8f3bf202-eb98-458c-bb5b-3302e9ec62a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>d72ff99c-f8e5-4449-9898-18de9d79b2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cellphone-input' and @placeholder = '06 32 77 90 80']</value>
      <webElementGuid>bf2b08ed-4186-4306-a1e4-72fd355b2c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
