<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TelephoneFixe</name>
   <tag></tag>
   <elementGuidId>8f01abdb-6b30-43a9-bd1a-50815c76886c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homephone-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='homephone-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;02 37 88 91 77&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab9f2af7-ffbe-4be2-9d81-3fd244785ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eccb6a41-0b2a-44af-a044-ad590a5c0886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homephone-input</value>
      <webElementGuid>bd65d4e6-129e-47df-b398-7653423995fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>homephone</value>
      <webElementGuid>382a0bda-2917-4919-ac61-4dfba11bc21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>02 37 88 91 77</value>
      <webElementGuid>5b8d79d9-58b3-4296-b85a-69b8299f2d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c34a5f44-0444-46b7-a83d-ff762da7780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>833aa71c-883f-4ae5-bff0-17fe4dabf2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homephone-input&quot;)</value>
      <webElementGuid>504bff29-ef0b-47b0-b16e-31aff5c5472c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='homephone-input']</value>
      <webElementGuid>10eaa96d-de51-447f-973c-5ee965d9d1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-contact-form[@id='epide-contact-form']/div/form/div/div[3]/div/input</value>
      <webElementGuid>d2ed6296-0919-41ec-aedd-81c97dddacca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d2a6880a-c2e6-4f33-aff0-4f027525b3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'homephone-input' and @placeholder = '02 37 88 91 77']</value>
      <webElementGuid>09b51876-17c1-42cd-bf07-be349bafd572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
