<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessageConfirmationCreationCandidature</name>
   <tag></tag>
   <elementGuidId>7c4680b7-58bd-4ba3-a219-e0467ba52f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='confirmation-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Félicitations !Votre candidature a été transmise&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3923eab3-f85c-4896-b6ff-e9bb9fa89a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmation-message</value>
      <webElementGuid>efb102aa-00ce-43ca-bbf1-60254d1ba5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirmation-container</value>
      <webElementGuid>c1ed7a8e-26d3-4a72-9fdf-fb7273604000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Félicitations !Votre candidature a été transmise</value>
      <webElementGuid>284cb2c2-3eba-4595-b959-1819b4e1a2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmation-message&quot;)</value>
      <webElementGuid>e6e6267f-3814-4868-8533-09d30081d1ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='confirmation-message']</value>
      <webElementGuid>d4a2f678-9b11-4a92-ab17-7e7157bb00ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[1]</value>
      <webElementGuid>bbda69b9-c19c-40ca-81a2-a452529bd2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>04a355e2-9292-4b30-9451-1853a0bcc330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'confirmation-message' and (text() = 'Félicitations !Votre candidature a été transmise' or . = 'Félicitations !Votre candidature a été transmise')]</value>
      <webElementGuid>e1cca0a1-294f-45e9-8f3c-e610c204e63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
