<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Nationalite_HorsUnionEuropeenne</name>
   <tag></tag>
   <elementGuidId>113532e9-c14d-48cb-a0ed-6f1522dfc353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-out-side-ue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-out-side-ue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkbox-out-side-ue</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd43b2a8-2de4-4163-8006-b6626230c6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-out-side-ue</value>
      <webElementGuid>7cb81045-4fd1-47d5-9b3f-3919471d4f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationalityNotUe</value>
      <webElementGuid>d6b0d3d8-3218-4b0b-8038-da85730c0540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e91191a-d495-4d2c-8647-df99b73e9947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>nationality-label</value>
      <webElementGuid>14cf8817-539c-4e00-b216-56fc4c5c3b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>HORSUE</value>
      <webElementGuid>52e56faa-11fb-417b-a3da-dd94e72b532c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>bb0e70ee-7916-4e2d-a56c-d106428d6b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-out-side-ue&quot;)</value>
      <webElementGuid>df826554-c9af-4315-ae51-d453a37e0149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-out-side-ue']</value>
      <webElementGuid>83870149-835b-417b-875a-6a7e23c85791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-identity-form[@id='epide-identity-form']/div/form/div[6]/fieldset/div[2]/div/div[3]/input</value>
      <webElementGuid>027e2882-8192-469d-93a8-ed6e0a0fd18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>66ed2ea4-7ad4-40ed-ab4f-bb5e8e1e8c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-out-side-ue' and @type = 'checkbox']</value>
      <webElementGuid>f91e2cf5-e7df-4246-8156-e8a1daedf62a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
