<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_BacBPBT</name>
   <tag></tag>
   <elementGuidId>c274a5d8-79f2-4da5-a8bd-e252653a2da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-not-graduated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-not-graduated']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Non&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56a5b0ed-ebd7-4cb4-993e-a7c1cbfacaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-not-graduated</value>
      <webElementGuid>ad37b5d7-bbdd-45d3-9db3-fe6bcc501e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>graduatedNo</value>
      <webElementGuid>0aa94b86-187a-470e-bb39-29025d3c4c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3bd87038-28a3-4544-9622-1a82539ab320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf0c29fd-dcee-4b22-b5cc-e7ebbed0d381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d979c763-9bb7-41b6-8837-26b4589fbdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-not-graduated&quot;)</value>
      <webElementGuid>26766ead-3116-4f62-9b42-93c9ddfe2c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-not-graduated']</value>
      <webElementGuid>36065c37-b81c-4207-b594-118f0584ce62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epide-formation-form[@id='epide-formation-form']/div/form/div/fieldset/div[2]/div/div[2]/input</value>
      <webElementGuid>8dd08ed3-8420-4026-8dcb-551e66e43229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//epide-formation-form/div/form/div/fieldset/div[2]/div/div[2]/input</value>
      <webElementGuid>a2aa28db-6fdc-462e-aaa5-05cda711d9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-not-graduated' and @type = 'checkbox']</value>
      <webElementGuid>c831ffe4-1ac2-44d1-b425-aed0b9dd8509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
