<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_NomNotification</name>
   <tag></tag>
   <elementGuidId>bd49dca4-fb7e-49f1-99de-b8429cea18e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namAdmNotifNom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namAdmNotifNom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namAdmNotifNom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>480e798a-d8a5-43f8-82b7-11dc3e20fd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>107a1d8c-a203-4f55-9bdf-69338f6cfe56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namAdmNotifNom</value>
      <webElementGuid>1b177077-228d-429b-a2cb-67e1df1e481c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45612375-4692-4434-95aa-582334ad366d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namAdmNotifNom&quot;)</value>
      <webElementGuid>b855188a-d2d4-477a-a391-dfc0a33540d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namAdmNotifNom']</value>
      <webElementGuid>d74475f5-2a02-45fd-a4e2-53f08fdc969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamAdmNotification_the_ajax_NamAdmNotification']/div/div[2]/form/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>83b599d9-1f08-4579-b011-57ef0477e218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/input</value>
      <webElementGuid>832799c7-b1db-445d-b118-9ae8e3ac869b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namAdmNotifNom']</value>
      <webElementGuid>abb79788-af4f-4223-a0ca-0838393d770f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
