<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prenomduMandataire</name>
   <tag></tag>
   <elementGuidId>40bab3cd-6f7c-499f-9126-adfaadaf30cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namRolmdtToUsrId__usr_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namRolmdtToUsrId__usr_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namRolmdtToUsrId__usr_first_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86af1eee-3484-491d-bc74-fd147062fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>f3db1cb3-cf2f-4a7d-8c48-67006abd1687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namRolmdtToUsrId__usr_first_name</value>
      <webElementGuid>f840a4f6-86c5-48fd-b98c-b58e5b42b32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nom cre</value>
      <webElementGuid>ee645040-eab9-4594-9fe2-9022e2589377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>51948438-79b1-4b6b-891c-1533eae63973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namRolmdtToUsrId__usr_first_name&quot;)</value>
      <webElementGuid>a1e82d73-3b79-4012-b0ac-c21d2ca3e70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namRolmdtToUsrId__usr_first_name']</value>
      <webElementGuid>a45e54e7-0173-477b-9ad2-3db9aad81a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamRoleMandat_the_ajax_NamRoleMandat']/div/div[2]/form/div/table/thead/tr[2]/th[8]/div/input</value>
      <webElementGuid>d68ca9cf-fcbb-4b98-ad17-1fc6863dc9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/input</value>
      <webElementGuid>77162ea5-2cb4-4043-a839-b867247d59e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namRolmdtToUsrId__usr_first_name']</value>
      <webElementGuid>57f6bc69-34e7-452b-b6cf-58d7d9c96dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
