<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DatedeFin</name>
   <tag></tag>
   <elementGuidId>0265b782-237a-429a-b7dc-31e198ddb8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namRolmdtFinDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namRolmdtFinDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namRolmdtFinDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b54f71c-17da-4792-a35c-29d25af08308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80347a0b-e72f-4700-a9b7-660f11c9d262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>016cc974-26d2-4f02-9929-b31ce8404e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namRolmdtFinDate</value>
      <webElementGuid>c2d36a69-7741-433a-ad80-91afe6fc954a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namRolmdtFinDate</value>
      <webElementGuid>ea9b85fd-4986-4ec9-b38f-5f4361038061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bcddb509-515f-4ff8-8cb4-41abccb82dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5cfc7116-ead0-4717-9e15-19ed7b2c0629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3c750b54-5380-420c-b370-f7a516438bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namRolmdtFinDate&quot;)</value>
      <webElementGuid>3bf28fc5-039d-462e-aa85-7e297f6f154b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namRolmdtFinDate']</value>
      <webElementGuid>f66eb931-8b05-47f3-b98b-65d18ce8c1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d4a690f7-8f10-4a3d-a8b0-b3e0bc041def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>b20c5051-9192-4c77-912a-b1db2ceb7487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namRolmdtFinDate' and @name = 'namRolmdtFinDate']</value>
      <webElementGuid>0021c7c9-b00f-4e44-a5de-4c36e04f14ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
