<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DatedeDebut</name>
   <tag></tag>
   <elementGuidId>476edc0a-a1d9-4c8b-aec7-0ce2d6926a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namRolmdtDebDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namRolmdtDebDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namRolmdtDebDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49da6f16-b21c-46a7-ae5d-dd1c264a8462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>146b0bc7-1b7b-40ba-be54-b54d83efd0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bfd7773-a63f-4a2c-bc76-67908cb0792e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namRolmdtDebDate</value>
      <webElementGuid>ddf3c795-1b69-4f06-a29c-912b31afb1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namRolmdtDebDate</value>
      <webElementGuid>4a2627f2-bbeb-469e-a869-7e0b48e45338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6be52235-8a80-4af5-9d2f-b3023df8f1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>343ea29c-4598-4aaa-b98e-13c5b7ac943d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ed2446dc-6afc-445a-b96e-bff1b04e48b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namRolmdtDebDate&quot;)</value>
      <webElementGuid>7b59f443-c5c7-4c67-b36d-239c9ee46adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namRolmdtDebDate']</value>
      <webElementGuid>06adf5df-c3e0-4130-9861-5fa4c39e222f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>32d21a84-bb7b-4911-a314-b68e6295b217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>13321ab5-bfcb-4f09-a526-ad9696d8b569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namRolmdtDebDate' and @name = 'namRolmdtDebDate']</value>
      <webElementGuid>67aee537-fc6c-48ee-8955-2e2254fc764b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
