<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomduMandataire</name>
   <tag></tag>
   <elementGuidId>b1fe422b-d531-42c3-b122-d60482b9c535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namRolmdtToUsrId__usr_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namRolmdtToUsrId__usr_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namRolmdtToUsrId__usr_last_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9974d832-d34a-4ce6-b34e-784b71e85e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>c89923b7-bf07-46c2-a256-a890428da63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04b75cb9-7a11-4cd4-92fa-e37136aba6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namRolmdtToUsrId__usr_last_name</value>
      <webElementGuid>f6fb1520-d674-40dd-9c2f-0612519fc33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namRolmdtToUsrId__usr_last_name</value>
      <webElementGuid>29ab0d24-a125-4b3c-ba35-65fe66158b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9a5cd43e-352d-4b83-99f5-f8197bfee717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92e5fcf3-9547-4dd8-95b2-2cad14f91fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>03d10c2e-9eba-48df-abc3-b2d411ff9772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namRolmdtToUsrId__usr_last_name&quot;)</value>
      <webElementGuid>fd4dc541-f516-4e83-92e5-c23a702e5a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namRolmdtToUsrId__usr_last_name']</value>
      <webElementGuid>7203d470-c8b2-4473-893f-932650ef827a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>b59e6263-91b3-4aef-8211-6cacf3a597be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>1f499819-ad4b-431c-927f-bdca892efb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namRolmdtToUsrId__usr_last_name' and @name = 'namRolmdtToUsrId__usr_last_name']</value>
      <webElementGuid>73cdb1ae-1c23-44ed-b24c-2c18eb3378a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
