<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_EncoursdeCreation</name>
   <tag></tag>
   <elementGuidId>c91701c6-0507-4a84-a1a8-ade6ad0290f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.enum-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namConvstgStatut-container']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;En cours de création&quot;i >> internal:text=&quot;En cours de création&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0095f32-2772-4815-8ea2-6cfde6337561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En cours de création</value>
      <webElementGuid>4f5bfeac-90ea-4895-b3f0-b28b548a1738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namConvstgStatut-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>51cf1bd1-4aea-41b5-afd0-3e7a1bbeb6e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namConvstgStatut-container']/div/span</value>
      <webElementGuid>65c2d81d-39b4-41ca-ae29-edf147833e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut de la convention de stage'])[1]/following::span[5]</value>
      <webElementGuid>3e5c94e6-1d5b-41fd-b788-c3613b285a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::span[5]</value>
      <webElementGuid>bac76348-a898-4030-adc4-58cc1548b0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convention de stage signée'])[1]/preceding::span[3]</value>
      <webElementGuid>19a12ccb-b011-425c-846b-9c2050f1c555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avenant de convention de stage signé'])[1]/preceding::span[3]</value>
      <webElementGuid>42865772-35cc-4f4a-8268-a03958da4da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>e2c21433-d4b2-44d7-a759-dcf71fe768fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'En cours de création' or . = 'En cours de création')]</value>
      <webElementGuid>4baccc31-9d7d-4ea5-87ec-1483b9a23185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
