<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Metier</name>
   <tag></tag>
   <elementGuidId>45ddc8e8-4214-46a9-bf1d-c5bdcdf0b68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namConvstgNafromeId__namNafromeLabelRome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namConvstgNafromeId__namNafromeLabelRome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namConvstgNafromeId__namNafromeLabelRome</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f4d3b73-1389-4bd6-8e0a-6e8332a14f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>d1cb859b-6236-484f-bd99-bd0fbbdc3114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>300eb8d6-8371-4b57-8427-5ada7fc9766d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namConvstgNafromeId__namNafromeLabelRome</value>
      <webElementGuid>c43a767e-8ede-40d7-9270-5fb35e3aa092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namConvstgNafromeId__namNafromeLabelRome</value>
      <webElementGuid>65c114d3-b4e4-4a1e-b1a7-137e017ed02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>45c5d3a8-a788-4386-af62-8d59d2b930b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c50ef0f7-d802-427f-ba1e-f9dcbdfd5599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>3cca7c50-584e-4ae9-bb9f-ebc93aaccd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namConvstgNafromeId__namNafromeLabelRome&quot;)</value>
      <webElementGuid>3bd95878-1e26-4b16-a70c-e22fc96952fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namConvstgNafromeId__namNafromeLabelRome']</value>
      <webElementGuid>34f349be-c168-422a-a2bf-5fca330cb6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>6215179b-1c86-48a9-bdb2-93ecf6814dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>04999125-ee15-4d01-9d25-065b1859c22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namConvstgNafromeId__namNafromeLabelRome' and @name = 'namConvstgNafromeId__namNafromeLabelRome']</value>
      <webElementGuid>e20aa99c-8004-4f99-b731-130057b69b8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
