<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Observations</name>
   <tag></tag>
   <elementGuidId>2272dcd3-b6aa-43e8-b48d-32a50a3ef3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namConvstgObservation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namConvstgObservation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namConvstgObservation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e5fb7c86-5de7-4748-9650-5641906b9e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>c0c759b0-4cdb-461d-9487-8ccd7119bacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namConvstgObservation</value>
      <webElementGuid>94271155-8eab-4fc1-9c72-94cf53e08c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namConvstgObservation</value>
      <webElementGuid>192753cf-9358-4200-b3c9-01eafed246ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>58a9ae03-673e-451f-9375-804ed6d72767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>64d9c03b-838b-47f7-b16d-b1ae2e688177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namConvstgObservation&quot;)</value>
      <webElementGuid>082f9896-9d10-426f-89d5-4c61b5d5ae7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namConvstgObservation']</value>
      <webElementGuid>e1e4724b-8196-46d7-b1a2-ea7da42bc177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[8]/div/div/textarea</value>
      <webElementGuid>f2f6e78b-2636-4da8-bd64-8d07fb317748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/textarea</value>
      <webElementGuid>524a732b-b6c8-4d92-9978-b721541ca6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namConvstgObservation' and @name = 'namConvstgObservation']</value>
      <webElementGuid>4be9ef1d-4c2a-4488-96d7-14956facd5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
