<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selec_prenom</name>
   <tag></tag>
   <elementGuidId>35a7d8a9-979d-4855-829e-5e7d6b627be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usr_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usr_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#usr_first_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6ddaf7c-9d94-4adb-82d7-564497358650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>038c7b58-6895-47a1-a2c4-4c8441a38fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usr_first_name</value>
      <webElementGuid>aa8f7979-5d49-473e-b6d7-597195d4f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c39c850-530b-4ce9-a396-edc8a0dbe3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usr_first_name&quot;)</value>
      <webElementGuid>7c6751b0-392b-43b6-a7b5-e1ad86836b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usr_first_name']</value>
      <webElementGuid>b766db69-8d25-42e1-8211-8a7f651c5a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamUser_ref_ajax_NamUser']/div/div[2]/form/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>37250c29-bf9e-42d6-a9e7-a68b530ce202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/input</value>
      <webElementGuid>85a54170-efe8-4aac-9898-5fdcec76b30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'usr_first_name']</value>
      <webElementGuid>f526e93c-1a97-45fb-88fb-c1617a94e389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
