<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nom_agent</name>
   <tag></tag>
   <elementGuidId>f5c1a782-7219-4caf-a519-375dd3b8c1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namConvstgRepresentantEpide__usr_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namConvstgRepresentantEpide__usr_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namConvstgRepresentantEpide__usr_last_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7c6e2c5-9a04-4ad0-b6a4-f9e5f3d06383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>db8f8dfe-0d4d-4cf1-b8ae-0721ee307dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e872dd97-9b14-4428-b530-d7abf4753aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namConvstgRepresentantEpide__usr_last_name</value>
      <webElementGuid>2e99a8a5-f8c4-4551-9332-a2c0c5c2bdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namConvstgRepresentantEpide__usr_last_name</value>
      <webElementGuid>25911084-8bee-457a-882f-39f71c2d80cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cd46c269-8738-4f39-a47d-3a6b47c29522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e8f94e1-4733-4a59-9e76-e89976eab284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>933a8f45-fd0b-4658-adaa-f20103950baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namConvstgRepresentantEpide__usr_last_name&quot;)</value>
      <webElementGuid>dfed6ce3-b756-47cc-bce0-3f202ebafdec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namConvstgRepresentantEpide__usr_last_name']</value>
      <webElementGuid>91054b4f-90f4-48a4-8727-8692a7520669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area6']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>8eff9d09-9bbf-4a26-8580-6994ce04cc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>74c23311-abb0-468a-8d92-19ea0e015b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namConvstgRepresentantEpide__usr_last_name' and @name = 'namConvstgRepresentantEpide__usr_last_name']</value>
      <webElementGuid>8d610e5e-ec4c-48ac-a1e9-43f839cd8ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
