<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateFinAnnulation</name>
   <tag></tag>
   <elementGuidId>ed9a703a-e194-4aa6-8f22-b1c41221f502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namConvstgDateFinAnnulation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namConvstgDateFinAnnulation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namConvstgDateFinAnnulation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54c08473-f152-49d9-8033-22a52a5d08e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d01786a-5e0a-4ea4-a12f-9f262f24d020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cee80d2a-9cfc-475c-a06b-ff091da25b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namConvstgDateFinAnnulation</value>
      <webElementGuid>8407fa60-8565-4f1c-a103-03193d3e3d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namConvstgDateFinAnnulation</value>
      <webElementGuid>980d1c76-1bc4-44eb-bdbd-606388252992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>22658dbb-e3a4-416a-a682-1e097a4eafbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce80f7b6-85d2-4025-bf7b-5b3c3bf6cde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>341072da-0824-4a2f-9975-d08fadd17de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namConvstgDateFinAnnulation&quot;)</value>
      <webElementGuid>2fbeede0-8f4c-4971-84e2-4de614bc9f61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namConvstgDateFinAnnulation']</value>
      <webElementGuid>64636790-8ecd-4566-a8fd-df93946c23c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[2]/div[3]/div/div/div/div/input</value>
      <webElementGuid>2473600f-0cbf-4b59-9b9b-6c2be5b8024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>d94ac1ec-9ae1-4fae-97d6-d6e2b29c2520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namConvstgDateFinAnnulation' and @name = 'namConvstgDateFinAnnulation']</value>
      <webElementGuid>9e3cd0ab-a1f9-445a-ba10-f59a27a86950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
