<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateFinInitiale</name>
   <tag></tag>
   <elementGuidId>f64f2afd-603b-46ef-81cf-7f28ce30a352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namConvstgDateFinInitiale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namConvstgDateFinInitiale']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namConvstgDateFinInitiale</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2de01da-bc33-405f-a105-c710d31b78d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0f01bdbe-c945-4388-9676-d554c089611a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>279dd929-435c-4864-b9d5-99f1f0c553ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namConvstgDateFinInitiale</value>
      <webElementGuid>7d290411-d38b-40d4-9bbd-491c38f19f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namConvstgDateFinInitiale</value>
      <webElementGuid>959b87aa-489a-418e-9a2b-8f1ba1733e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c15968ee-1080-4321-ba32-b3c0e38544d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>053b7029-3d36-4ea9-9959-777b41e796b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e21684b0-4ea8-4e6d-aa16-7e772c595868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namConvstgDateFinInitiale&quot;)</value>
      <webElementGuid>c66f3d61-78fe-4429-8aa5-1866e0c9f5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namConvstgDateFinInitiale']</value>
      <webElementGuid>cdd3fc70-67d6-4dbe-b453-5c046246dbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>83f2ef05-3ded-4b44-ba5b-d51456ce32a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>84c61af6-1de7-4887-a3af-8814a6e4959f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namConvstgDateFinInitiale' and @name = 'namConvstgDateFinInitiale']</value>
      <webElementGuid>8ca8fd8a-8a2e-4db8-98b9-d24a82d6100c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
