<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ConventionsdeStage</name>
   <tag></tag>
   <elementGuidId>a8dd7818-0c5e-4986-91e4-2f5380bc78b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tab-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;list_NamConventionStage_panel_ajax_NamConventionStage_namConvstgJenId&quot;]/div/div[2]/form/div/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#links_NamJeune div >> internal:has-text=&quot;Conventions de stageTotal 2Statut de la convention de stageN° de convention de s&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>911a474b-48ed-41eb-8cae-51424d87ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-content</value>
      <webElementGuid>a1287325-f654-43a1-8adb-338f2d4fa343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Conventions de stageTotal 2Statut de la convention de stageN° de convention de stageType de stageStageDate de début Date de fin initialeDate de fin annulationMétierSIRET/SIRENSecteur d'activitéRaison sociale Partenaire|PartenairesNom du contactPrénom du contactFonction du contactTéléphoneEmailTélécharger la convention de stage à signerA signer123 503 398Stage découverte du monde du travailInterne11/02/202612/02/202630340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTélécharger la convention de stage à signerA signer123 503 399Stage découverte du monde du travailInterne11/02/202611/02/2026Organisation d'évènementiel30340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTotal 2</value>
      <webElementGuid>f47cd72a-d840-461c-afba-8d010b3b7fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;links_NamJeune&quot;)/div[@class=&quot;tab-content&quot;]</value>
      <webElementGuid>e37c450f-4952-4e01-9afa-a76ee136c416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='links_NamJeune']/div</value>
      <webElementGuid>03de7108-3118-4380-b98d-abf685c802c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sortie du volontaire'])[2]/following::div[1]</value>
      <webElementGuid>78662038-e062-49d7-b206-68817bf09168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Situations contractuelles'])[1]/following::div[3]</value>
      <webElementGuid>fba03e4b-ae40-4bd6-b4a9-6f715386b09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>27214076-7c61-418c-8e77-0d6d1f6c1273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Conventions de stageTotal 2Statut de la convention de stageN° de convention de stageType de stageStageDate de début Date de fin initialeDate de fin annulationMétierSIRET/SIRENSecteur d&quot; , &quot;'&quot; , &quot;activitéRaison sociale Partenaire|PartenairesNom du contactPrénom du contactFonction du contactTéléphoneEmailTélécharger la convention de stage à signerA signer123 503 398Stage découverte du monde du travailInterne11/02/202612/02/202630340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTélécharger la convention de stage à signerA signer123 503 399Stage découverte du monde du travailInterne11/02/202611/02/2026Organisation d&quot; , &quot;'&quot; , &quot;évènementiel30340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTotal 2&quot;) or . = concat(&quot;Conventions de stageTotal 2Statut de la convention de stageN° de convention de stageType de stageStageDate de début Date de fin initialeDate de fin annulationMétierSIRET/SIRENSecteur d&quot; , &quot;'&quot; , &quot;activitéRaison sociale Partenaire|PartenairesNom du contactPrénom du contactFonction du contactTéléphoneEmailTélécharger la convention de stage à signerA signer123 503 398Stage découverte du monde du travailInterne11/02/202612/02/202630340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTélécharger la convention de stage à signerA signer123 503 399Stage découverte du monde du travailInterne11/02/202611/02/2026Organisation d&quot; , &quot;'&quot; , &quot;évènementiel30340959300520Personnel polyvalent en restaurationELIOR - 92 CourbevoieTotal 2&quot;))]</value>
      <webElementGuid>d1329935-82ba-4841-8fb5-bc0a675f4009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
