<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bonnes</name>
   <tag></tag>
   <elementGuidId>0b349dac-5000-4474-9b0d-937ce970ced9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namJenRelationMere-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namJenRelationMere-container > div.enum-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-field_namJenRelationMere-container div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>675a279e-0b86-4748-a81b-40ad7669f771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>cf042411-9842-41ed-afd0-08ef06a02624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bonnes</value>
      <webElementGuid>b0753592-77cb-4d44-9227-126d2c087fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namJenRelationMere-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>3a8112d4-ef39-44d2-843b-6d04c38a5efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namJenRelationMere-container']/div</value>
      <webElementGuid>ea5b30f1-83f9-404d-abd9-cce8e17b7b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::div[1]</value>
      <webElementGuid>0e3d7acb-8e44-4005-b7fe-787a7da07e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relations avec la mère'])[1]/following::div[1]</value>
      <webElementGuid>b203f56d-9aa7-4881-8199-57407e7bb8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre de frères'])[1]/preceding::div[2]</value>
      <webElementGuid>d4cd8a65-6716-4846-a576-24d21c878c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/span/span/span/span/div</value>
      <webElementGuid>711cb6e1-5a4b-482c-a072-4c3fe64a3c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bonnes' or . = 'Bonnes')]</value>
      <webElementGuid>a96160df-0068-4cec-bddc-668cbf062f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
