<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SituationProfessionnelleMere</name>
   <tag></tag>
   <elementGuidId>be9fc299-e992-4019-9282-56577180df61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenSituationProMere']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namJenSituationProMere</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenSituationProMere</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5a6e63d-29ae-45d7-bcb0-6a74ed06d959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>2fcfbc83-184f-4466-b497-c964e5d77fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98bd2776-47cd-4424-b0cd-834d8e532892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenSituationProMere</value>
      <webElementGuid>0b106351-69e0-4d90-84e4-d8ded62c64bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenSituationProMere</value>
      <webElementGuid>aebd6ad5-da84-4e21-86ab-a2241c682a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>eb7a0199-be13-409d-9597-1c358e1a20ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb3d6c57-ac06-4a1a-996a-ecda8c613de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>32f7ab10-1a8d-489f-a620-cc6631747e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenSituationProMere&quot;)</value>
      <webElementGuid>b3d74f90-d3a8-4dae-bc3e-4c0088c9780a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenSituationProMere']</value>
      <webElementGuid>0b0d99c3-20b4-488e-a20d-00330a14452b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area12']/div/div[4]/div[2]/div/div/div/input</value>
      <webElementGuid>171c69ef-3e0c-4dd4-828b-7d0c5f31debd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div/div[4]/div[2]/div/div/div/input</value>
      <webElementGuid>b7c243cd-e7fd-4b16-91ef-c2442b51aaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJenSituationProMere' and @name = 'namJenSituationProMere']</value>
      <webElementGuid>664922fd-daf7-4db3-9225-29d85ba10e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
