<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RelationsSituationPersonnelleProfssionnelle</name>
   <tag></tag>
   <elementGuidId>6936105c-7e54-4abb-bdd3-ca0a906fdfa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenRelationSituaPerPro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namJenRelationSituaPerPro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenRelationSituaPerPro</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0226fc37-658b-4bc1-a81b-c350e3b40703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>0255140c-468c-48c0-b26e-95e015c90148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenRelationSituaPerPro</value>
      <webElementGuid>d0850459-a256-4120-b379-c4d7dcd364a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenRelationSituaPerPro</value>
      <webElementGuid>012d8b96-0466-4688-aa0d-f7b81e9a5818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f5291dcb-5822-4eb7-929b-1a7fd13cf64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>277d6081-0860-4fd7-aa04-4db57fc48335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenRelationSituaPerPro&quot;)</value>
      <webElementGuid>a39ecac8-7daa-4cfe-884e-6da4802c0f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namJenRelationSituaPerPro']</value>
      <webElementGuid>c40250c2-89cf-4aba-9b95-65fc4ce2abc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area12']/div/div[9]/div/div/textarea</value>
      <webElementGuid>646986ec-58ee-4d33-ac59-5fc7c69cdfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/textarea</value>
      <webElementGuid>7367368e-f5b3-45d7-80eb-4ab40d22101a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namJenRelationSituaPerPro' and @name = 'namJenRelationSituaPerPro']</value>
      <webElementGuid>35c04c63-60b5-4094-bb0c-4081e0855c5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
