<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FSE-DureeRechercheEmploi</name>
   <tag></tag>
   <elementGuidId>d969f2fb-005b-4dda-bb16-5e77c97b4092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenDureeRechEmploi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namJenDureeRechEmploi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenDureeRechEmploi</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23984748-51bb-4e4e-8aa4-b9bb03ff2a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric field-container</value>
      <webElementGuid>4fb5cd84-1123-4f63-a16a-180a1e5df02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c47e3f2a-4797-4ccf-b0b9-8fc48ed21772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenDureeRechEmploi</value>
      <webElementGuid>9a0bddd6-3efe-44ad-92c2-83064c46bc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenDureeRechEmploi</value>
      <webElementGuid>bdc670e5-6553-4793-81b5-65aafc780b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>547603e6-3a24-4cb2-badf-078d73554cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9c27061-b198-4798-b17e-a844ea66f623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenDureeRechEmploi&quot;)</value>
      <webElementGuid>71713d0f-9c3f-4dec-ae9d-14fca9645ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenDureeRechEmploi']</value>
      <webElementGuid>a5959f97-f8aa-42ea-95c0-77f9609ec037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area10']/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>5098f237-a584-4860-9a84-f0851a816a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>c2cc2796-fbc3-4b22-ad60-436030a9a55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJenDureeRechEmploi' and @name = 'namJenDureeRechEmploi']</value>
      <webElementGuid>45bd9847-5a01-42fd-abe0-cfbb697fc9f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
