<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TailleDeHaut</name>
   <tag></tag>
   <elementGuidId>18cc793b-6b87-4614-ba63-31bc11d68bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTailleHaut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTailleHaut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTailleHaut</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e6ba4f7-e82d-42a0-850c-7f5c13b2013e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>11b50e4b-aec7-4e95-92cd-e8fcd6a8457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae9260bc-c6ab-47ed-a9ed-2aaf2b922213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTailleHaut</value>
      <webElementGuid>3d6b4db6-7e87-415f-9613-6f658838562b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTailleHaut</value>
      <webElementGuid>844a03c7-1d58-49ff-912b-40b71e3e04e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d257496b-c646-4d1c-a2a6-962fb604314b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff27c132-9663-4e6f-8bf4-aca01c366cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>301a3551-9102-4dad-8e77-87ba83549caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTailleHaut&quot;)</value>
      <webElementGuid>05721efa-1ce1-4d76-b5bc-9e8b2294935b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTailleHaut']</value>
      <webElementGuid>fbfe4d74-ef93-45d4-9259-9b5eddc7a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area14']/div/div[3]/div/div/div/input</value>
      <webElementGuid>6bc8e82d-bf72-4ba7-bef2-5e5c1919cbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>5c99de71-93bc-4c9e-8455-07cc0de63428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJenTailleHaut' and @name = 'namJenTailleHaut']</value>
      <webElementGuid>072af3ad-ed07-47c7-be2b-14020ad10366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
