<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Montant</name>
   <tag></tag>
   <elementGuidId>eab14f5a-abc1-4278-ace5-27fda996728b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenMontantDettes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenMontantDettes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenMontantDettes</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65eda14f-81e5-4b79-b533-7bce3ead2066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric field-container</value>
      <webElementGuid>7ab9dc4b-ee6f-4fe3-ad2d-48829f8c5dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>284ae690-832e-48ec-8f58-43ec678f1592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenMontantDettes</value>
      <webElementGuid>4da128bb-4530-46f7-9d2d-206518b30f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenMontantDettes</value>
      <webElementGuid>9ffb15e6-f4aa-491a-894c-029088f04a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cd65229c-7d67-4720-bfcd-0aac68ec2f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d11dc137-0aef-4981-b163-e9563901e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenMontantDettes&quot;)</value>
      <webElementGuid>f86f9e45-12f8-4a80-ba9f-5f9fbc6e5f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenMontantDettes']</value>
      <webElementGuid>5c3bcc46-cd03-45b9-a495-94c2a7349f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>64d5562e-2d1a-470b-a794-a1a1b9a27d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>895f9efb-4ea0-421d-9f07-498c9e90a761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJenMontantDettes' and @name = 'namJenMontantDettes']</value>
      <webElementGuid>a35fd88b-539a-4af9-9c84-1e6a43adbd0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
