<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_ExisteTilDesDifficultesAuSeinDeLog</name>
   <tag></tag>
   <elementGuidId>626749cf-5738-4c3f-88d8-2b71c43d4054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenDifficulteSeinLogement_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenDifficulteSeinLogement_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenDifficulteSeinLogement_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6595721-4eef-4a19-8a82-e4d55402bf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1afd2012-d3ab-413c-9965-031d9f4dac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenDifficulteSeinLogement_no</value>
      <webElementGuid>614e7634-0f0e-4170-bc47-5ef2638b7d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenDifficulteSeinLogement</value>
      <webElementGuid>90f70680-55c0-44b8-ad26-ffd5f7105bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d5f6481c-9f30-437c-9095-6f9cb4889f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4726811f-87ec-45af-8bc1-76ca4e3f5930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenDifficulteSeinLogement_no&quot;)</value>
      <webElementGuid>d9470da2-54de-4a31-8f60-a8b675b4fa3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenDifficulteSeinLogement_no']</value>
      <webElementGuid>c988d494-e65b-4f5d-980c-d5262372a963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area13']/div/div[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>ae816a0f-e3e0-4300-850d-7fb549851b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>2a5ec3b7-f3f6-4b17-99b9-e81686254e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenDifficulteSeinLogement_no' and @name = 'namJenDifficulteSeinLogement' and @type = 'radio']</value>
      <webElementGuid>4638a531-6573-4ccf-bb5e-685df6f20dcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
