<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_TitreSejourCompatibleAvecParcoursEpide</name>
   <tag></tag>
   <elementGuidId>3a5bc397-0f03-45da-99d9-cfda8a559467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTitreSejourParcoursEpide_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTitreSejourParcoursEpide_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTitreSejourParcoursEpide_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0fe4431-bf67-4c96-a8a7-970aa733f262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ccf71c32-6f30-493a-8a8c-b63dac786752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTitreSejourParcoursEpide_no</value>
      <webElementGuid>293fb0b6-e793-40ea-a25d-c626bc26e7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTitreSejourParcoursEpide</value>
      <webElementGuid>b8cb43cb-8673-42c2-9514-cd0a2cfeb315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cc033a69-0840-421d-9eb8-b5397a742cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5f999d4-f1ef-4e2c-8c5a-b1fab45fea9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTitreSejourParcoursEpide_no&quot;)</value>
      <webElementGuid>f7ef9468-5a2a-4441-8ea1-c4e839260eb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTitreSejourParcoursEpide_no']</value>
      <webElementGuid>7ef15a5e-c558-496a-8dbe-e6d50d8bd53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[9]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>209333b4-e724-497f-9f5b-306f771ef359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>394f2c44-91d1-4224-b1ec-6d189fa5caa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenTitreSejourParcoursEpide_no' and @name = 'namJenTitreSejourParcoursEpide' and @type = 'radio']</value>
      <webElementGuid>964340f1-3bee-4749-9041-b4e784c37d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
