<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_Code</name>
   <tag></tag>
   <elementGuidId>89d4893c-d0cd-44bc-9214-c13c096475b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenCodePermis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenCodePermis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenCodePermis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b84a0262-9c65-4744-936e-3f0532763679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>dd59a747-98be-4615-8000-fd0cfed12bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenCodePermis</value>
      <webElementGuid>49b6102e-ca68-484c-bb52-3d06cd362fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenCodePermis</value>
      <webElementGuid>175771ff-f7aa-4562-99e4-7f7502cfafd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d28d812-46d7-4ffd-a54a-9310221c14db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5776a6bd-7d5b-477b-aa0e-297edc87f159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>9d793b36-78fc-4dcc-bbc3-7edfa6cfc796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenCodePermis&quot;)</value>
      <webElementGuid>8ff6fb54-c195-4aab-84b0-844692358d24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenCodePermis']</value>
      <webElementGuid>4059b4a4-8574-4210-9505-c9cbdcf0896e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area16']/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>30134073-964c-41f9-9a3b-05d5d2410ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>ce79ac01-40dc-429a-a195-f64ed13c70d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenCodePermis' and @name = 'namJenCodePermis' and @type = 'radio']</value>
      <webElementGuid>51f085a7-2229-4d61-8f74-39ccfd2c33ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
