<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_DemandePUMaEnCours</name>
   <tag></tag>
   <elementGuidId>cf2aa1d8-0f2a-429b-ae64-b78eb6f88117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenDemandePuma</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenDemandePuma']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenDemandePuma</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08bc060b-e1d8-4dbf-ad60-50621e05e9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c6d70194-d845-47d0-960b-2eeaa8fa5ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenDemandePuma</value>
      <webElementGuid>8b9242c2-2e19-44b1-a4a3-626defdd18cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenDemandePuma</value>
      <webElementGuid>804ef5ef-926b-4395-a30f-3445e3153a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>40b08929-e463-4173-bf50-390d97b8a0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3297da4-4a0b-4587-a8d0-e6083c463869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e731c625-abba-4f14-b7fe-5d485c3f3399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenDemandePuma&quot;)</value>
      <webElementGuid>cec385ac-388c-4a81-8e08-6b666c8ba82d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenDemandePuma']</value>
      <webElementGuid>286fb6c5-9386-4237-b8bf-36629a4c3d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[7]/div/div/div/div/div/div/input</value>
      <webElementGuid>ec199909-cf61-432d-8e59-93c7433eba50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/input</value>
      <webElementGuid>e4141800-d8b6-4cab-8691-003bd6d37591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenDemandePuma' and @name = 'namJenDemandePuma' and @type = 'radio']</value>
      <webElementGuid>6d2eddb9-be6c-46c4-96b0-f5e2c780b6aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
