<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio_NON_PersonneACharge</name>
   <tag></tag>
   <elementGuidId>4415b7ab-5691-4ac0-82a4-214ec234af3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenPersonneCharge_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namJenPersonneCharge_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenPersonneCharge_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f48ea953-fd4b-42d5-a40f-5a5a9f477b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>dad65d69-b5f1-4889-a3b1-077f34b68721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenPersonneCharge_no</value>
      <webElementGuid>304096a2-dcd3-4220-83a1-3d3a31d6b9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenPersonneCharge</value>
      <webElementGuid>f22a9ef9-c64c-4159-976a-aab0125052f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ff4539d4-aa77-4ef3-867b-8b25d9e3e1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0cff1d42-b4ed-4ba7-b649-802c61cddab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenPersonneCharge_no&quot;)</value>
      <webElementGuid>d248edc4-9b6f-4f13-a902-59ac67cc786e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenPersonneCharge_no']</value>
      <webElementGuid>cfabee5c-f2f9-42f4-a837-a3ec64e478bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area12']/div/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>07b38fbc-90c3-42b7-ae42-f2c188163b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>a076764f-1a1e-4bf4-a68f-284e13343223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenPersonneCharge_no' and @name = 'namJenPersonneCharge' and @type = 'radio']</value>
      <webElementGuid>b5d5fc51-1d2f-4fa3-8c7b-3a28f6e5c71a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
