<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_SuivisSocials</name>
   <tag></tag>
   <elementGuidId>629f458e-b827-4495-bc77-bd5a396444d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenSuiviSocial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenSuiviSocial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenSuiviSocial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f33bf4f8-3087-4d8d-8e93-2c1c76bead6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4e2337bd-a7c2-4799-9607-a15e2e4085ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenSuiviSocial</value>
      <webElementGuid>36659de1-99e8-4844-9d31-59c74ba3d8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenSuiviSocial</value>
      <webElementGuid>93c2bde0-f896-4f6c-be86-cf2a2fc565cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dcca0539-bab9-4cc7-bcd7-ee386e579fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>30842bac-c184-47fe-8d38-49dfce8cd40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b3e5ca6e-a8ad-4fb6-901c-22c7a4a6c9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenSuiviSocial&quot;)</value>
      <webElementGuid>61cd9f60-58e3-482a-938e-3a39e07b7c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenSuiviSocial']</value>
      <webElementGuid>d08f6a17-23b8-489a-bc38-fc436cd8651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[14]/div/div/div/div/div/div/input</value>
      <webElementGuid>6aaee586-8fe1-4fb9-8c6b-825909c949e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div/div/div/input</value>
      <webElementGuid>f1dd6534-e00b-4d16-a89f-b6e44bfce365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenSuiviSocial' and @name = 'namJenSuiviSocial' and @type = 'radio']</value>
      <webElementGuid>ce589f44-dc9c-458b-9459-8f9346e225c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
