<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio_NON_ClasseAdaptee</name>
   <tag></tag>
   <elementGuidId>031afdfb-2d25-421b-a644-4b2ac1959821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenClasseAdapte_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namJenClasseAdapte_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenClasseAdapte_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>804a95be-fd43-43f3-a258-7b813e4962f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e5d07bb8-c091-48d9-8e10-d49c8b5de30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenClasseAdapte_no</value>
      <webElementGuid>83b9bb6b-8516-47da-9706-580844835d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenClasseAdapte</value>
      <webElementGuid>a7bdfdcd-37e6-412a-b072-e363c461a44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>080b4ce9-36d2-4ab4-a8f1-c8d05c00bbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41d1eba5-5813-45c3-bea1-449fb3c47058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenClasseAdapte_no&quot;)</value>
      <webElementGuid>e5b752dc-baf2-486a-ad48-6a7fd3bd458a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenClasseAdapte_no']</value>
      <webElementGuid>0fd37201-1a33-4c56-96f5-55d2a97074fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area9']/div/div[8]/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>7f2ad0f0-629a-49d9-8d4b-1638fdbb20f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>3b8f7f73-58c6-4e08-b4f6-983ef03961fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenClasseAdapte_no' and @name = 'namJenClasseAdapte' and @type = 'radio']</value>
      <webElementGuid>c4061782-7527-464a-8740-2ad4fbb52877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
