<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_FSE_VitdansMenageMonoparental</name>
   <tag></tag>
   <elementGuidId>1f52f016-77c4-44c1-8b07-4910609a46de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenFoyerMonoparental</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenFoyerMonoparental']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenFoyerMonoparental</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2ed3199-4117-49a4-ac0d-ef8da5818f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c5d5cbd1-db90-48d5-926d-3a436f520856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenFoyerMonoparental</value>
      <webElementGuid>f165c41d-a1b2-409a-adac-d2da9a1faa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenFoyerMonoparental</value>
      <webElementGuid>79dbc699-b5d0-4c6c-ae20-117e68c19095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e49fed15-fcc5-47dd-808c-5b641c2fb9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>186e9e85-0a37-43c9-9be6-373c079c09fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e7241afa-2666-49fb-9f8a-5d018c8e62f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenFoyerMonoparental&quot;)</value>
      <webElementGuid>93609a6b-c706-4323-8164-5991c790abaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenFoyerMonoparental']</value>
      <webElementGuid>7d79a022-1b09-4539-b32b-77598e3bd534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area12']/div/div[10]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>41b946ae-3696-461e-aea7-9d27984f1e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>0336cfe5-66bf-4bad-a4ee-47936464aefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenFoyerMonoparental' and @name = 'namJenFoyerMonoparental' and @type = 'radio']</value>
      <webElementGuid>93295050-4807-4bc3-b18b-452bfc99f01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
