<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_SuiviJudiciaire</name>
   <tag></tag>
   <elementGuidId>59a4b85d-2e6f-451a-b44e-09d9337e6d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenSuiviJudiciaire_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenSuiviJudiciaire_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenSuiviJudiciaire_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c6fd94d-2544-4371-a8a0-82e37ea7fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a6665be5-da5d-425a-9e08-568b21a926e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenSuiviJudiciaire_no</value>
      <webElementGuid>3b21d50b-c1ab-4161-aa22-6bc18298c079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenSuiviJudiciaire</value>
      <webElementGuid>7ad54d96-8277-4634-bca2-1057e48bdc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>98f151e2-c464-4604-9e7a-68a3be97848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>729d20ae-16c0-4fc2-b10e-973b97061661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenSuiviJudiciaire_no&quot;)</value>
      <webElementGuid>88b249e0-afea-4897-8bb1-3e2c2afd6f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenSuiviJudiciaire_no']</value>
      <webElementGuid>23cc872b-5518-4e2d-ac94-26863a63e51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[11]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>23c55a9e-3005-43de-b2f5-ef2a45acc977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>c6f93ddb-5de0-4957-bb72-a18917596f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenSuiviJudiciaire_no' and @name = 'namJenSuiviJudiciaire' and @type = 'radio']</value>
      <webElementGuid>2f97e7d1-d9ac-4c4e-840c-4dc171e9bc2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
