<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_FSE_AllocataireMinimasSociaux</name>
   <tag></tag>
   <elementGuidId>1a2f11b4-d2cd-4e2e-b408-51382668e79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenDroitMinSociaux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenDroitMinSociaux']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenDroitMinSociaux</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e5790ea-649c-4265-8337-72dd0a3e71c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0ee58faa-3e8a-421f-9b27-3468024d9fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenDroitMinSociaux</value>
      <webElementGuid>9a15b812-e1c9-49d7-a320-29804d7dceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenDroitMinSociaux</value>
      <webElementGuid>165cc1b5-8e1a-4b43-ab4b-ca0bbc200401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7af6f7da-9b59-4526-96e8-133e7e2b3eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3f1e6ed-9eed-4f5e-8bb7-2a06121c930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a056c4d3-3bae-4a36-9d2e-14758ef33111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenDroitMinSociaux&quot;)</value>
      <webElementGuid>0ff47798-32eb-4751-a597-9a1bba959836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenDroitMinSociaux']</value>
      <webElementGuid>521b712b-3bb9-40c3-8e58-fae7cf4403e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>f6067cd2-2375-4f5b-bb3a-7b404e9b6dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>6bc061e2-4113-4a57-8c15-dba8c85b5346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenDroitMinSociaux' and @name = 'namJenDroitMinSociaux' and @type = 'radio']</value>
      <webElementGuid>2b3ac88f-7378-4b83-b5c2-52c6bb452d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
