<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_TitreSejourCompatibleAvecParcoursEpide</name>
   <tag></tag>
   <elementGuidId>3762d811-11e7-4575-a25f-a3f4f383bf27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTitreSejourParcoursEpide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTitreSejourParcoursEpide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTitreSejourParcoursEpide</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cd4ae90-057e-41af-850f-fd08c9e05a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>5201ccb7-8163-49fd-9d66-706458168d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTitreSejourParcoursEpide</value>
      <webElementGuid>94fc2636-b9a1-49ca-b626-ba555728379d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTitreSejourParcoursEpide</value>
      <webElementGuid>64cf9ea7-e567-410d-863d-3b1275dba3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>813493cd-4a52-46a4-b428-4cb7a2beede3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64ea135d-1ce8-4aeb-b191-0588a15ded23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>97740a97-aace-45eb-a884-e408ecb4b8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTitreSejourParcoursEpide&quot;)</value>
      <webElementGuid>08075c82-1a35-48f2-98b0-47995aee3daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTitreSejourParcoursEpide']</value>
      <webElementGuid>dc9b04db-dc88-4bf7-8bc3-3fd9c54d5a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area15']/div/div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>8b375c17-63a3-4a81-9bd7-e8b9c284fcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>fc2013b3-9fa3-4c3e-8ad9-09d1f69c3abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenTitreSejourParcoursEpide' and @name = 'namJenTitreSejourParcoursEpide' and @type = 'radio']</value>
      <webElementGuid>5684ed74-ad31-4359-a52b-e23bb9236cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
