<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_CarteDeReduction</name>
   <tag></tag>
   <elementGuidId>e1c3506c-9fa6-47bf-999d-2fa5ca5dd904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenCarteReduction_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenCarteReduction_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenCarteReduction_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa68b90b-149b-407c-9c41-4d48d3077c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>785ae0bc-65f8-4b8c-8da5-8e5889fdb19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenCarteReduction_no</value>
      <webElementGuid>0253ac0e-f34f-4906-b3dc-55389cdff2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenCarteReduction</value>
      <webElementGuid>bff23501-77e9-4308-9057-2aa8ac28c486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4cc1fcfa-4c75-403d-b3ce-0b64e5299d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e842a40-c00d-43af-959f-a3f91bbbc393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenCarteReduction_no&quot;)</value>
      <webElementGuid>93ef47b3-703c-4bdc-a762-8c336046557a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenCarteReduction_no']</value>
      <webElementGuid>904d7c05-d0dd-4294-819f-25e124b6a52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area16']/div/div[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>3c74f35b-2113-4e91-bd1a-3950bea7450b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>cc1aeb3f-a36d-4c45-ada8-353f996a0f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenCarteReduction_no' and @name = 'namJenCarteReduction' and @type = 'radio']</value>
      <webElementGuid>ce1b5b94-6062-43b7-9103-a83ba586aee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
