<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_Hebergement</name>
   <tag></tag>
   <elementGuidId>9492358b-c162-4557-b45a-3bf456222043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel_work_13 > div.card > div.card-header.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel_work_13']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Hébergement$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c4583d5-f391-49ae-9fbd-4505ca3cab02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header collapsed</value>
      <webElementGuid>bdb32fd3-6c51-4bd7-846e-19f8887c3e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>4b6d5bd7-8d64-4c5e-acb8-975e3db555db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse_panel_work_13</value>
      <webElementGuid>fb10d0aa-0354-4928-9e1a-fcd5598c6984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hébergement</value>
      <webElementGuid>afc777b7-5fca-460e-baf9-4a6b417e9247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel_work_13&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header collapsed&quot;]</value>
      <webElementGuid>17fd4912-a423-444a-af34-2a1d937dd4ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel_work_13']/div/div</value>
      <webElementGuid>ae477fd8-5cc1-4dca-bf33-d5d58ac6e4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non'])[19]/following::div[4]</value>
      <webElementGuid>b1e46419-5751-4fe0-975e-efbeaf5ca9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oui'])[19]/following::div[5]</value>
      <webElementGuid>3621999d-f942-4684-8df3-6b7a1785bf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hébergement actuel'])[1]/preceding::div[1]</value>
      <webElementGuid>a0e3ec9a-6c92-4a19-8b46-7cb1a34c8ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[8]/div/div/div</value>
      <webElementGuid>4fe6c4b0-74ae-488b-aa4d-305a3e5813af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hébergement' or . = 'Hébergement')]</value>
      <webElementGuid>32ed0c80-ec62-4883-83f0-216e9fe941bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
