<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SituationMatrimoniale</name>
   <tag></tag>
   <elementGuidId>f117a01d-be81-4b0b-b7a8-a1c34be73c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namJenSituationMatrimoniale-container > div.enum-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field_namJenSituationMatrimoniale&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-field_namJenSituationMatrimoniale-container div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7815f83-21c3-49e4-bf1d-24ffe62375ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>636548ad-a16a-418b-b79b-0f87353f5670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Célibataire</value>
      <webElementGuid>3ca14451-83df-4fff-98bd-f0d486df3676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namJenSituationMatrimoniale-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>3fa38fc8-7e68-49fb-a60b-9306abd50b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namJenSituationMatrimoniale-container']/div</value>
      <webElementGuid>8fb04b40-7b59-4a66-bbda-9ac570b3c92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::div[1]</value>
      <webElementGuid>785cc24d-2946-4365-bc7d-9adefaa7be29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Situation matrimoniale'])[1]/following::div[1]</value>
      <webElementGuid>eeec97a6-0b25-4caf-bea6-84966981061b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div/div/div/div/div/div/span/span/span/span/div</value>
      <webElementGuid>8326c154-f5c2-4b4d-a9e0-e548442473ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Célibataire' or . = 'Célibataire')]</value>
      <webElementGuid>d6260d98-2387-45f6-b687-a38c42f0400d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
