<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Heber_Condition</name>
   <tag></tag>
   <elementGuidId>084601b5-9a08-45e3-b5a6-ce11954f0b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namJenConditionHebergement-container > div.enum-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namJenConditionHebergement-container']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;×Chambre individuelle&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d152a75-fb72-4a73-99b8-a46ed4fe2059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>28bc5bb5-7148-4848-a7a8-0271baca5c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chambre individuelle</value>
      <webElementGuid>e0403dc5-3253-45d3-a556-a3d860dc336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namJenConditionHebergement-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>c3e0b9d9-50e7-4fbb-b554-8a88c017aaf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namJenConditionHebergement-container']/div</value>
      <webElementGuid>b07505a4-dbcb-448c-812c-f747036a5cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[9]/following::div[1]</value>
      <webElementGuid>72437ff9-3fae-4534-a158-92792130264a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condition'])[1]/following::div[1]</value>
      <webElementGuid>5357ed80-498a-4644-af39-d552129c587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Précision si autre'])[3]/preceding::div[1]</value>
      <webElementGuid>0f2357d5-a0c3-4aa2-9238-79f7755cf2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div[6]/div/div/div/div/span/span/span/span/div</value>
      <webElementGuid>874d9f5c-fa0d-404b-b214-17634b6f640f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Chambre individuelle' or . = 'Chambre individuelle')]</value>
      <webElementGuid>76213883-e227-498e-acdf-8daeed1acc92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
