<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_QPV</name>
   <tag></tag>
   <elementGuidId>27cad121-7dcb-47fe-98cc-7e20b9327bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namQpv-container > div.enum-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field_namQpv&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;×Non renseigné&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69c5fc56-d344-469e-a8f2-dc3d093b5da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>9e930e0b-fa07-43bc-aad8-a383a8fa0344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non renseigné</value>
      <webElementGuid>e222a638-7dc2-4365-8460-87dee8daa992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namQpv-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>059f0e5b-839b-4213-9875-faced97888be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namQpv-container']/div</value>
      <webElementGuid>6923fd70-f419-416e-ac49-2ae3db5e5aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[1]</value>
      <webElementGuid>6cb0a3ed-cc9b-4f04-b938-d0879d8605fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QPV'])[1]/following::div[1]</value>
      <webElementGuid>b90aba22-9e05-4739-969e-b80216cb927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom QPV'])[1]/preceding::div[1]</value>
      <webElementGuid>438a00fe-572f-4900-922a-3c459c5fb788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span/span/span/span/div</value>
      <webElementGuid>e2b4f3f1-4485-4f95-a8aa-243dd4142d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Non renseigné' or . = 'Non renseigné')]</value>
      <webElementGuid>bb40ab33-6981-4396-91e2-069944622d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
