<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Creer</name>
   <tag></tag>
   <elementGuidId>f09cc789-8d0d-4976-9ab9-743beb5299b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-create</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamEntretienIndividuel_panel_ajax_NamEntretienIndividuel_namEiJenId']/div/div/div/div[3]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Créer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf480ed2-78b7-44e3-b574-f7527c388d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-create</value>
      <webElementGuid>dcddc234-9572-4085-8c09-6deb8447efd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77029f83-6f7c-4992-b61a-591527eea442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>9b795381-7272-4652-b3e3-9a5d0c4615f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Créer</value>
      <webElementGuid>b5c923f3-a638-47f3-b61f-b7665f1f3ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamEntretienIndividuel_panel_ajax_NamEntretienIndividuel_namEiJenId&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;head&quot;]/div[@class=&quot;list-actionbar&quot;]/div[@class=&quot;actions pull-right&quot;]/button[@class=&quot;btn btn-primary btn-create&quot;]</value>
      <webElementGuid>192ea804-d99f-4dd0-b774-ac7fba2ff765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>b4856ca9-05fa-4cd3-b8c5-c9a96f91a1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamEntretienIndividuel_panel_ajax_NamEntretienIndividuel_namEiJenId']/div/div/div/div[3]/div/button</value>
      <webElementGuid>c53d7a6d-637f-46c4-8810-40099a848721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 0'])[5]/following::button[1]</value>
      <webElementGuid>9d2019c1-5de9-4f71-b777-c79163e72c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entretiens Individuels'])[2]/following::button[1]</value>
      <webElementGuid>0307beb5-471c-4f1c-a622-c4eb9c0ee90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>2118d6b8-8be8-423a-80a2-fb8af5f3fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Créer' or . = 'Créer')]</value>
      <webElementGuid>8d6391be-b06a-414c-b4dc-6bb581cb55f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
