<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_FSE_Type</name>
   <tag></tag>
   <elementGuidId>ae77d7fc-c138-4658-aec8-ae063425b198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@data-field='namFseType']//div&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(10)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Haydar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c3fb9e37-7adc-4ad5-bc85-8eab1c9f32a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>namFseJenId__namPrenom</value>
      <webElementGuid>60ec215d-89d5-4f6d-8d16-9c3cccf6e06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Haydar</value>
      <webElementGuid>89111146-ad25-40ae-a0c3-05382f1bde05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamFse_the_ajax_NamFse&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[10]</value>
      <webElementGuid>1184f4f2-4f4f-4f76-9bc7-cb3bd5cb2bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamFse_the_ajax_NamFse']/div/div[2]/form/div/table/tbody/tr/td[10]</value>
      <webElementGuid>7b0f1e31-010b-4c43-b512-9dc9d1c2edd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIDDICK'])[1]/following::td[1]</value>
      <webElementGuid>075cf5a7-a542-4988-a367-67b358a8bad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section 2'])[1]/following::td[2]</value>
      <webElementGuid>2b227b33-babe-45ef-8cff-24cf4862d4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRA'])[1]/preceding::td[3]</value>
      <webElementGuid>7ce9d4cd-2cf8-4606-b154-021d1e7d86e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]</value>
      <webElementGuid>71d1aa1a-aea4-4299-94da-bc5beed0d243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Haydar' or . = 'Haydar')]</value>
      <webElementGuid>9ceefe7e-976d-40bf-9305-f04c3c35dcca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
