<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateProchainRDV</name>
   <tag></tag>
   <elementGuidId>6216ecfb-ca67-453a-bca6-400e1b73cedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namEiDateProchainRdv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namEiDateProchainRdv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namEiDateProchainRdv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>572c2ff7-d06f-499d-acdd-76904f107852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>26ba7d9a-0aff-4387-95fd-a19de19b22f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25d9bbd8-66d5-4db2-9ef2-a882adc3348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namEiDateProchainRdv</value>
      <webElementGuid>14920275-f601-4edc-ae9f-acc0a9e8dacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namEiDateProchainRdv</value>
      <webElementGuid>76803466-1a88-42ea-a257-5e5e2c7a2824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>30471cc9-9ac4-454b-a2ab-3aadbbfb9faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61e70b7c-7e44-48da-b384-fed8123bf6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>adc4624a-90a8-447c-889b-88c15ec8b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namEiDateProchainRdv&quot;)</value>
      <webElementGuid>1290a810-3a15-473e-a128-0cfc9df644d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namEiDateProchainRdv']</value>
      <webElementGuid>6fcabd29-c1c9-4957-badb-88c67b9c533e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>f29d4bf6-a8bd-44b3-b997-8af6529bca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/input</value>
      <webElementGuid>df42eaef-3af2-4ee1-9214-b5e8021effc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namEiDateProchainRdv' and @name = 'namEiDateProchainRdv']</value>
      <webElementGuid>162f78fe-6dc9-46dd-984d-098764d51f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
