<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CommentaireGeneral</name>
   <tag></tag>
   <elementGuidId>e16300ed-b1eb-4eef-bdfa-2242ff96f65c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namEiCommentaireGeneral</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namEiCommentaireGeneral']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namEiCommentaireGeneral</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8d332bb5-ef16-4984-a5d9-e2b717a0d663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>215e07f7-a56f-4d2e-8271-ebe9509de108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namEiCommentaireGeneral</value>
      <webElementGuid>ca8e6cb6-5f2e-4564-b5cf-a94ca5267b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namEiCommentaireGeneral</value>
      <webElementGuid>5148b37f-4b73-46e0-9e3f-f9bff36d55f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d9eb2e8d-628d-4fd2-b1af-26c19c6033f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>7df72f3d-a91e-44a3-87c8-fdd80ee2c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namEiCommentaireGeneral&quot;)</value>
      <webElementGuid>beb66dce-3f5f-477f-a4f9-692b3e1ed879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namEiCommentaireGeneral']</value>
      <webElementGuid>8adf81a4-91fa-4109-b68e-7185f1b3c82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[4]/div/div/textarea</value>
      <webElementGuid>22b6d968-c21d-4210-8dcb-e56a87c8c8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>458f0e64-58ff-45e1-b5b9-a0a040369795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namEiCommentaireGeneral' and @name = 'namEiCommentaireGeneral']</value>
      <webElementGuid>85e38b85-76a6-4400-a081-63d555883a98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
