<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commentaire</name>
   <tag></tag>
   <elementGuidId>621c1d9f-e983-4a87-afcf-f9e1929b523e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namSrtvntCommentaire</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namSrtvntCommentaire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namSrtvntCommentaire</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>10974c38-981f-4e53-8a45-cf55e4e68ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>3299eb1b-9eab-46fe-80b4-8bfe00321aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namSrtvntCommentaire</value>
      <webElementGuid>ba993053-15ff-48be-97af-c9ce03ce78ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namSrtvntCommentaire</value>
      <webElementGuid>95a0c860-3360-4ba7-845a-8bbd0e1b98c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>53fffce6-741d-498b-800a-a439e90c3dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>c6f51452-01b4-4356-b430-d78e86894e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namSrtvntCommentaire&quot;)</value>
      <webElementGuid>12715fea-7573-4b73-9c3c-3320453091be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namSrtvntCommentaire']</value>
      <webElementGuid>807dc4ad-ad54-412d-bf24-e41fb536068b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[10]/div/div/textarea</value>
      <webElementGuid>f17a6c80-d062-4098-bc7a-db58b89f2fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/textarea</value>
      <webElementGuid>23099999-0671-4728-aee2-b4f7ccce6c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namSrtvntCommentaire' and @name = 'namSrtvntCommentaire']</value>
      <webElementGuid>02a7b6b1-73ea-4b65-827c-0b6d5d3a102c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
