<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Non_enRechecheEmploi</name>
   <tag></tag>
   <elementGuidId>52b89243-f716-4348-a632-582ecc387bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namSrtvntRechercheEmploi_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namSrtvntRechercheEmploi_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Non&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd741328-58c1-4f5a-8f60-bd31b5e5271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>27608159-79d0-4ce9-a462-0acf69666963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namSrtvntRechercheEmploi_no</value>
      <webElementGuid>7492c9c4-a090-4bbb-9dcc-37abee4f6619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namSrtvntRechercheEmploi</value>
      <webElementGuid>24a9c07c-4c23-495f-bcac-d667406fdfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>58091de4-2573-4160-aaae-6ab4c33df87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d01de061-3bd7-4199-8da4-18f4fcc0051d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namSrtvntRechercheEmploi_no&quot;)</value>
      <webElementGuid>18b86f29-b2d4-4366-8557-4709e1fc4069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namSrtvntRechercheEmploi_no']</value>
      <webElementGuid>d9e96b6c-1931-4089-a218-3f12e94ff491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[3]/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>12d7de29-ca6a-4be4-aefc-4d056f2d9922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>5fdf7711-a4e0-4b62-990b-51d012a35a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namSrtvntRechercheEmploi_no' and @name = 'namSrtvntRechercheEmploi' and @type = 'radio']</value>
      <webElementGuid>a5cda7a7-25f0-464c-8243-1bf7f9a22c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
