<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TypedeSortie</name>
   <tag></tag>
   <elementGuidId>dbf0407c-46ab-4b2c-9638-cfb5e5935c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap.select2-container--focus > span.selection > span.select2-selection.select2-selection--single</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field_namSrtvntTypeSortie&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>992db01f-a6c9-41b9-a655-4da6c7d142db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>75dc51e5-913a-46df-a55e-baabd45e9497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2c927e2b-1a19-4ebd-a8bb-a34f3328bcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>326f5d11-e2fa-4116-9e9c-fd854a4175bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8eb33b24-38f9-44ab-b696-88816a8f046a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>efcc756b-0dbf-4d8b-a74d-dec17517dec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3c3094b-2a8e-4db9-b0b0-2c568b69b5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-field_namSrtvntTypeSortie-container</value>
      <webElementGuid>9a7bef2c-edc8-499a-89cf-08cb8f988f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;area1&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;field field-enum&quot;]/div[@class=&quot;form-group field-enum required updatable&quot;]/div[@class=&quot;control-group&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]</value>
      <webElementGuid>3018831b-1b5f-4c4a-8588-741fb8bd2057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[3]/div/div/div/div/span/span/span</value>
      <webElementGuid>92c2ca74-f8de-4ae2-ae55-61b964f9683e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type de sortie'])[1]/following::span[3]</value>
      <webElementGuid>aa27a47e-af4f-4c64-bc86-4fb189921b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion nam srtvnt jen id'])[1]/following::span[3]</value>
      <webElementGuid>719e25c8-8058-4cba-903d-384ff59a4843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motif sortie anticipée'])[1]/preceding::span[5]</value>
      <webElementGuid>aac0a2a6-89c8-4862-9577-85f70bf585d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/span</value>
      <webElementGuid>a4261bfc-69b4-4967-8276-59ea540b7c03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
