<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statut_Encours</name>
   <tag></tag>
   <elementGuidId>4a917bb1-056d-4c9c-9b15-9156a32f53e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.enum-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namSrtvntStatutSortie-container']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;En cours&quot;i >> internal:text=&quot;En cours&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a599aec-a9a8-470b-aa49-483ef6950166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En cours</value>
      <webElementGuid>d1ac5878-084a-4bd9-8515-610537d1c990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namSrtvntStatutSortie-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>df02eb9c-f9ff-443a-91b2-57568034a13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namSrtvntStatutSortie-container']/div/span</value>
      <webElementGuid>f8be9a7f-7afb-44f6-8047-cb9ecafadb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut'])[1]/following::span[5]</value>
      <webElementGuid>949666d4-474f-4b81-8eee-8be969586ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::span[5]</value>
      <webElementGuid>158b3988-ea9f-416e-a3b6-792c20987025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de sortie'])[1]/preceding::span[3]</value>
      <webElementGuid>a7d9a185-f6c2-4a53-bf83-9a8cec4bb7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>a5790857-735c-4d30-acae-4474933ed5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'En cours' or . = 'En cours')]</value>
      <webElementGuid>d2e1caba-bf7e-4064-9594-0ecfd456cc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
