<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_promotion_Choix1</name>
   <tag></tag>
   <elementGuidId>494fb173-696d-4e11-832e-d23e69bdcd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;f_list_NamPromotion_ref_ajax_NamPromotion&quot;] > div.container-table.table-responsive > table.table.table-striped > tbody > tr.list-clickable.js-resizable > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamPromotion_ref_ajax_NamPromotion']/div/div[2]/form/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;012019&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e8f063d6-9677-419a-b5fa-7d0a5d45fa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>namProLibelle</value>
      <webElementGuid>5a4fc388-85f0-48e0-842d-67655023d204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>012019</value>
      <webElementGuid>bb722de1-038c-40b3-b97e-a9d405228c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamPromotion_ref_ajax_NamPromotion&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[3]</value>
      <webElementGuid>ebd49f11-4f99-41fc-9d38-0dd526276ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamPromotion_ref_ajax_NamPromotion']/div/div[2]/form/div/table/tbody/tr/td[3]</value>
      <webElementGuid>38658e12-d116-4869-b10e-bac70956def8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bordeaux'])[1]/following::td[1]</value>
      <webElementGuid>5db3182a-0227-423e-987a-976e16afddf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 1'])[6]/preceding::td[2]</value>
      <webElementGuid>d420c5a4-3ed8-4637-ae02-5e2f6367ed65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/form/div/table/tbody/tr/td[3]</value>
      <webElementGuid>279407a1-5eec-453d-a1a7-5b53280ab634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '012019' or . = '012019')]</value>
      <webElementGuid>a337ae9f-b520-43f9-8320-078269428aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
