<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_printer</name>
   <tag></tag>
   <elementGuidId>acc8810b-f778-422f-adcf-5b750bac6c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-print.action-not-xs > img.icon</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-action='print_DL_MODEL_CONTRAT_INSERTION']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Générer contrat insertion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a5420e0-8adc-497f-b844-ec8bfd0512e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://preprod.name.epide.fr/resource?type=ICO&amp;code=printer&amp;d=responsive5_epide&amp;_=5_1_66_20251112155152&amp;_ajaxkey=drvFMYerWZLPIHBHZvVf</value>
      <webElementGuid>63538ef2-e4d7-405a-a5c8-c22d7211e166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>9d79c67b-c6ee-4380-b13a-87390c4feadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamAdmissible_the_ajax_NamAdmissible&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[@class=&quot;col-action actions&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;btn btn-secondary btn-print action-not-xs&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>10f42878-2ab1-42ec-8205-b13fee62b332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamAdmissible_the_ajax_NamAdmissible']/div/div[2]/form/div/table/tbody/tr/td/div/button/img</value>
      <webElementGuid>8fc1aab2-ecb6-4c6b-9c3d-b7a0923c4a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://preprod.name.epide.fr/resource?type=ICO&amp;code=printer&amp;d=responsive5_epide&amp;_=5_1_66_20251112155152&amp;_ajaxkey=drvFMYerWZLPIHBHZvVf')])[2]</value>
      <webElementGuid>860ed612-aebc-46e8-b0f5-611f96918c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/button/img</value>
      <webElementGuid>7ed188a6-533d-4ec0-8bab-8318a40f07ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://preprod.name.epide.fr/resource?type=ICO&amp;code=printer&amp;d=responsive5_epide&amp;_=5_1_66_20251112155152&amp;_ajaxkey=drvFMYerWZLPIHBHZvVf']</value>
      <webElementGuid>71bdf02e-e0f1-4beb-94af-ba4f4b93c178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
