<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promotion_DateArrive-Jusqua</name>
   <tag></tag>
   <elementGuidId>437a9cd7-e509-42cd-8e6c-80134ed1129f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dmax__namProDateArrive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dmax__namProDateArrive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dmax__namProDateArrive</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e773f5d1-0acd-4f41-81aa-baf234f0174d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dmax__namProDateArrive</value>
      <webElementGuid>600ccaa3-7cd5-477f-acb8-3c3dae70ff76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>b90bddd3-30d5-4423-808f-db3a6511ddeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmax__namProDateArrive&quot;)</value>
      <webElementGuid>0c693315-7fd1-48e4-8798-f9ef9d8c9d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dmax__namProDateArrive']</value>
      <webElementGuid>d818e7cb-63f7-4aca-b694-1daf6255fd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamPromotion_ref_ajax_NamPromotion']/div/div[2]/form/div/table/thead/tr[2]/th[4]/div/div[2]/input</value>
      <webElementGuid>adf08d5e-d1b1-4639-af61-4c66500bc2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/div[2]/input</value>
      <webElementGuid>ba004849-27e5-46f2-ac14-a85bce4333f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dmax__namProDateArrive']</value>
      <webElementGuid>c2b34b8a-742d-47ba-8aa0-6f42afabbc11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
