<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Popup_ConfEditContr_DateDebut</name>
   <tag></tag>
   <elementGuidId>15d3ecba-b75d-41d2-955c-ae1ddbc33f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>354c5393-c007-4284-99f6-588a959f1190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a954662-8b7d-4aa6-a7d1-5003f48393e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f965489-969a-44e8-8b37-a8562f87d854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16/11/2025</value>
      <webElementGuid>333141b2-1190-42bb-a811-faeeb1bfda01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION</value>
      <webElementGuid>c6136314-74ff-44c4-8496-55b4d1393f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION</value>
      <webElementGuid>320c7237-af1d-40ce-b1e7-eaf8260b9760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8125c015-8f8d-4582-8f8a-2ea9a4150b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd006ed5-0929-4c1a-8a80-cf9a77db44f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>03c2a49b-5780-485a-8db4-1ae347679778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION&quot;)</value>
      <webElementGuid>03f44809-0cef-4a05-a5cf-82c7abe79f6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION']</value>
      <webElementGuid>20ede28a-13a5-4d31-892f-879bab59c0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgmodal_confirm']/div/div/div[2]/div/div/div[3]/div/div/input</value>
      <webElementGuid>b42fb079-5cfd-4799-882e-d56b22d58221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f5fb19a6-434a-4f15-a0ec-068ba37d02f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION' and @name = 'namAdmActionContratInsertionDebDate_idNAM_ADM_CREER_CONTRAT_INSERTION']</value>
      <webElementGuid>9d03a58c-77cb-45e9-8ba4-2d1c9c8bc72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
