<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_popup_MessageErreur</name>
   <tag></tag>
   <elementGuidId>f2d22d03-a935-476a-a8ab-35d8863ce349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dlgmodal']/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Le jeune TRATKatalonNom4 TRATKatalonPrenom4 n'est pas rattaché à une promotion&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf1511c-20c4-4253-8315-1d1a842c9993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger</value>
      <webElementGuid>690b5bb7-578f-4252-9dee-fdf07ff22047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Le jeune TRATKatalonNom4 TRATKatalonPrenom4 n'est pas rattaché à une promotion  </value>
      <webElementGuid>c903c8fd-565f-4b88-b11a-435e7280ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlgmodal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;alert alert-danger&quot;]</value>
      <webElementGuid>2cd62214-799f-4be1-aa12-a1be31e656c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgmodal']/div/div/div[2]/div</value>
      <webElementGuid>d6290640-6211-4a69-bc51-e815d33a7df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Erreur'])[1]/following::div[2]</value>
      <webElementGuid>3ac7c2af-090e-46b7-bd26-eb71a7c129dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fermer'])[1]/following::div[6]</value>
      <webElementGuid>b5349a4b-a5f1-4dd0-b545-043c044dd969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[1]</value>
      <webElementGuid>f7adf5da-cf26-4100-8735-66837b31be18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>73151e29-3881-4675-99f3-0b561e8d4a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Le jeune TRATKatalonNom4 TRATKatalonPrenom4 n&quot; , &quot;'&quot; , &quot;est pas rattaché à une promotion  &quot;) or . = concat(&quot;Le jeune TRATKatalonNom4 TRATKatalonPrenom4 n&quot; , &quot;'&quot; , &quot;est pas rattaché à une promotion  &quot;))]</value>
      <webElementGuid>3efba764-2059-439c-9ce9-aa3514bff054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
