<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_prenom_select_jeune</name>
   <tag></tag>
   <elementGuidId>c55a0fee-b75d-4a02-a2b6-29dcbfaf1af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.list-clickable.js-resizable > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;TRATKatalonPrenom&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>87429f29-4d93-445d-8d8a-9c6ff9d9ce37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>namPrenom</value>
      <webElementGuid>baf27caa-9c42-4d99-a2b7-b292356df912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRATKatalonPrenom6</value>
      <webElementGuid>91d20310-34ae-4a17-9c27-00862310749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamJeune_ref_ajax_NamJeune&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[3]</value>
      <webElementGuid>ba9bc768-bee4-4775-b3d8-3c3f019c329c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamJeune_ref_ajax_NamJeune']/div/div[2]/form/div/table/tbody/tr/td[3]</value>
      <webElementGuid>6a2e9968-aeb9-4572-8bb8-19ed0a84887f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRATKatalonNom6'])[1]/following::td[1]</value>
      <webElementGuid>ac454a88-3471-41c8-ad03-9d13a3621028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalontest@email.com'])[1]/preceding::td[3]</value>
      <webElementGuid>890b33da-2fdf-4578-a51e-fc73925ff687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/table/tbody/tr/td[3]</value>
      <webElementGuid>94028b33-e26a-4f02-a029-6a1e917f4969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'TRATKatalonPrenom6' or . = 'TRATKatalonPrenom6')]</value>
      <webElementGuid>a329afc9-67fd-4290-bb37-eb6175a2d22c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
