<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duree</name>
   <tag></tag>
   <elementGuidId>901830ed-4938-4217-bdc4-bdecd2177712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namExaDuree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namExaDuree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namExaDuree</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e66f0ac-3e76-49b4-9ed5-9f8de5fb0d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric field-container</value>
      <webElementGuid>f223d9c7-8777-4c4c-820d-64dac7d6b71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4b44fc3-c2b8-4b69-baed-34f6b7f9bcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namExaDuree</value>
      <webElementGuid>be3f2df3-467f-449a-a466-3246a8c374da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namExaDuree</value>
      <webElementGuid>76448ffd-3bda-49dd-926d-4dc71534ac09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1e98c873-4bf5-463d-bd89-83ce16d75251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7fc1184-08b5-40d9-b3d9-31fa1e0cdf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namExaDuree&quot;)</value>
      <webElementGuid>30586c4a-b545-4596-bea1-e56ef2e06060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namExaDuree']</value>
      <webElementGuid>acfb8d1f-f4a7-4fca-9a27-6d315416be17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamExamen_the_ajax_NamExamen_0']/div/div[2]/form/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>873fbad1-f6ef-4d35-ba32-51ec46c1c27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>a5fbc653-d3c6-4a20-acca-ae6856e549ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namExaDuree' and @name = 'namExaDuree']</value>
      <webElementGuid>658ad369-9c11-47d2-a13b-c6eeeb0f0462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
