<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SIRET_SIREN</name>
   <tag></tag>
   <elementGuidId>328691e2-0971-436f-afc0-8bf7f7203208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namPrtSirent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namPrtSirent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namPrtSirent</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f394f923-303f-47d5-a570-7e8a71d6a0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>e3854663-a217-402c-870e-1aa5a3602dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namPrtSirent</value>
      <webElementGuid>2c36aa6d-d137-468c-bffd-17a1f25e9be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0028349b-a3d9-4558-8ab6-b49238a903fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namPrtSirent&quot;)</value>
      <webElementGuid>4df0c765-865c-4c34-b9dd-7a0dfb37850b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namPrtSirent']</value>
      <webElementGuid>9722c140-6249-46e0-81c7-bdbeee4f1df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamPartenaire_ref_ajax_NamPartenaire']/div/div[2]/form/div/table/thead/tr[3]/th[4]/div/input</value>
      <webElementGuid>762bc201-6ebc-479e-9de6-d197f9e591ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/input</value>
      <webElementGuid>029f945a-23d9-4fab-ae33-9481a59846dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namPrtSirent']</value>
      <webElementGuid>87e48684-2ae3-49bc-ae23-02f09e19d636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
