<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_Obtenu</name>
   <tag></tag>
   <elementGuidId>78196917-835f-4425-9003-d06911f8506d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namInexObtenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namInexObtenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Oui&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bd85709-c9bb-493c-943c-c1108c9e9192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>cee678b7-08ca-45ad-8263-e3e87cacce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namInexObtenu</value>
      <webElementGuid>fabcf9ec-8db2-4060-ab3a-e1524b071cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namInexObtenu</value>
      <webElementGuid>2b58e552-3da4-4c04-8af7-af3faba81a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>772bfcef-e4ba-42f1-b030-66692fb3203a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9299d1fc-9b17-4e0e-b10c-c0ce4cf82aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>00953d43-18e5-477d-bedc-a74258ebdbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namInexObtenu&quot;)</value>
      <webElementGuid>45a3ee5e-73b8-4a67-afb9-6189e2bb2050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namInexObtenu']</value>
      <webElementGuid>79eecab4-9e9e-41af-99d2-3b16cf38f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>d9470975-3a79-46af-8346-1960461affbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>57e288f2-ae24-45bc-807b-28698a9658f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namInexObtenu' and @name = 'namInexObtenu' and @type = 'radio']</value>
      <webElementGuid>24856297-72dc-4a81-9785-3271dfc30ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
