<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrganismedeFormation</name>
   <tag></tag>
   <elementGuidId>45a00243-8b31-414d-a301-bfc4bdfd597c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namExaPrtId__namPrtRaisonSocial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namExaPrtId__namPrtRaisonSocial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namExaPrtId__namPrtRaisonSocial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>263eeb33-0c14-4f32-a2c8-40af27f3a96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>692f56dc-a2dc-42cc-a573-712e55d163ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9f426fc-3ee6-4d4d-bf2b-10744a98f8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namExaPrtId__namPrtRaisonSocial</value>
      <webElementGuid>fd516545-1132-420d-8603-0b2746fcccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namExaPrtId__namPrtRaisonSocial</value>
      <webElementGuid>6813a5ab-13af-41e1-9628-ea15d301eb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a8eeccd3-78f5-4da5-9994-7443a560fa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>adae76a1-75ec-436e-8c9c-7305e090db53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e0d7f685-b429-47f4-b916-4ea544748ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namExaPrtId__namPrtRaisonSocial&quot;)</value>
      <webElementGuid>bf2cfdd8-a30a-4938-81e8-29cedb6c213b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namExaPrtId__namPrtRaisonSocial']</value>
      <webElementGuid>afbbf9e3-69ac-4317-8f85-aae3bff30a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area2']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>a506c285-d822-46d9-97a7-f3b1f52a15a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>179267c7-91d8-4e94-9d8c-a515ef7cd62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namExaPrtId__namPrtRaisonSocial' and @name = 'namExaPrtId__namPrtRaisonSocial']</value>
      <webElementGuid>0ae501b9-8e74-4234-a73a-b712f3893065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
