<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_type_exam</name>
   <tag></tag>
   <elementGuidId>1fc8d154-c872-4df1-a4e7-88d614c01436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namExaTypexId__namTypexIntitule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namExaTypexId__namTypexIntitule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namExaTypexId__namTypexIntitule</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69d16ce3-51a9-4650-919e-eeb4993f77a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>0b83ba33-9fff-41d4-a234-c85fd8707278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abd6a2d6-caae-42cc-ba99-495ce658bc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namExaTypexId__namTypexIntitule</value>
      <webElementGuid>c546e690-8335-404d-b7f8-b60741723e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namExaTypexId__namTypexIntitule</value>
      <webElementGuid>edda5a42-fcef-4a45-90ce-01c5eae1ae0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1db8560d-5fa4-4052-b9db-7a2d643ad6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>172b038b-2900-4e02-b190-91f7ad31513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>484ec6ec-c99e-419f-964f-ce7ff5d9247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namExaTypexId__namTypexIntitule&quot;)</value>
      <webElementGuid>3edb3984-13c5-4c2d-93ed-3f68550567f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namExaTypexId__namTypexIntitule']</value>
      <webElementGuid>caedf74a-a6dc-4f5b-8ea3-2d4958eedb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamExamen_the_ajax_NamExamen_0']/div/div[2]/form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>94f32c20-3e25-4fad-bd06-b52736285607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0efd4e88-d5dd-4b14-8d01-dd67a3f7cd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namExaTypexId__namTypexIntitule' and @name = 'namExaTypexId__namTypexIntitule']</value>
      <webElementGuid>7ec07a5e-b280-4ebc-83a2-ee0990230c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
