<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NbModValid_InscriptionExam</name>
   <tag></tag>
   <elementGuidId>c34f5e3e-7618-4469-a2b2-14153c1f1b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_naminexNombreModuleValide_id60862</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[starts-with(@id,'field_naminexNombreModuleValide')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_naminexNombreModuleValide_id60862</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cd066d2-fd4b-449f-8a9a-338ce82868e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric field-container</value>
      <webElementGuid>2de63c0c-3600-46f5-8c9c-28d6e86c396c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd01d3ca-bd91-489a-870f-32e88ae2f847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_naminexNombreModuleValide_id60862</value>
      <webElementGuid>356469bf-c2a3-4696-91c2-18c56e2d610d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>naminexNombreModuleValide_id60862</value>
      <webElementGuid>b94b9ce5-5328-4c4d-a18a-f37c6448b94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8d72a21a-73b1-4f8c-a4ae-932f0867f579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fee40f23-ef38-423a-ae78-85893c0b7068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_naminexNombreModuleValide_id60862&quot;)</value>
      <webElementGuid>21d3d52a-b895-4f76-8555-f470eee4eb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_naminexNombreModuleValide_id60862']</value>
      <webElementGuid>983c1df4-d7c6-45ce-9e27-1f8437422b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamInscriptionExam_the_ajax_NamInscriptionExam']/div/div[2]/form/div/table/tbody/tr/td[24]/div/div/input</value>
      <webElementGuid>b7e41452-e3e0-4a15-9497-5e315af32e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[24]/div/div/input</value>
      <webElementGuid>6dfe3200-4cbc-4109-b992-0ed293ccbb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_naminexNombreModuleValide_id60862' and @name = 'naminexNombreModuleValide_id60862']</value>
      <webElementGuid>f26c1386-2d3d-40ca-ae94-65e527c2db29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
