<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non_Obtenu</name>
   <tag></tag>
   <elementGuidId>0456ce09-6c0a-4527-831d-6242c4910e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namInexObtenu_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namInexObtenu_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Non&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c913f064-d425-42d4-935e-dc240eefde96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f005b3e8-d6a6-4701-ad1c-912b974cbf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namInexObtenu_no</value>
      <webElementGuid>50b7a6b8-d45b-4bc7-8461-89283b73040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namInexObtenu</value>
      <webElementGuid>f817633d-59f5-49c3-8c2b-7c23ca8a60c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>11f216b6-385e-4e4c-a793-e41ed2544ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a42579c-70a1-43cf-b5da-7c6ebd70278e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namInexObtenu_no&quot;)</value>
      <webElementGuid>030d2baa-72f6-41fd-a8da-28755ff80175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namInexObtenu_no']</value>
      <webElementGuid>4a5f481c-cfbc-4c46-8350-cb3cb98e55f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area3']/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d20c403b-bfc1-4147-ac44-3ba1f9dbd2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>00578919-5046-42bb-98f2-08f888d6b68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namInexObtenu_no' and @name = 'namInexObtenu' and @type = 'radio']</value>
      <webElementGuid>fecac412-d12d-4f90-8db0-4bc3092def97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
