<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateHeure</name>
   <tag></tag>
   <elementGuidId>e328ef45-15f7-4060-862c-ba9c0ea6f775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namExaDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namExaDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namExaDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a38a1b6a-d0d7-40e6-90fb-ad83b664cf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92b0940e-56e5-4dbf-bfef-c46c77254769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26ee2f8d-7711-46ea-a61e-18f8701ccac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namExaDate</value>
      <webElementGuid>90e51888-f8f3-4e6a-b41a-d3d93e7fdadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namExaDate</value>
      <webElementGuid>c8f6f601-e7fb-44f3-a118-a02649a184a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3acc5b20-f62a-4afb-a054-decac741afc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa59a622-c43e-4106-a804-e881370ca18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>5c8e1849-3f16-44e7-968e-fef9fbd6139a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namExaDate&quot;)</value>
      <webElementGuid>526f7131-fa61-4ffa-b644-589d7e7402e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namExaDate']</value>
      <webElementGuid>e9191dc4-4e60-42f8-a1f3-b3f6e64591b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamExamen_the_ajax_NamExamen_0']/div/div[2]/form/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>6ea5f3ec-ccf1-4e54-8940-be883d4c8052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>8fa46bfc-291b-4a89-9806-107271258e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namExaDate' and @name = 'namExaDate']</value>
      <webElementGuid>fbc1e732-146a-47d7-8463-3d590d9cff11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
