<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_Etat_EnCoursDeCreation</name>
   <tag></tag>
   <elementGuidId>4a715df1-bbb9-4891-8af8-14edfa2b07c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namCavenantStatut-container']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namCavenantStatut-container > div.enum-item > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;En cours de création&quot;i >> internal:text=&quot;En cours de création&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39f8c354-46a3-4cec-8a6e-4e0b400f883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En cours de création</value>
      <webElementGuid>b1a7a7c7-cc17-4628-8dc3-46401f374797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namCavenantStatut-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>95a39250-b668-44f0-a503-acf3f9b6fbc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namCavenantStatut-container']/div/span</value>
      <webElementGuid>f06a56be-a962-47fa-a20a-929d58447242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut'])[1]/following::span[5]</value>
      <webElementGuid>a9815265-fce7-4531-96b5-89d0668ffbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avenant de transfert de centre'])[2]/following::span[7]</value>
      <webElementGuid>b645f4e2-1df9-484c-b644-ae88b89455d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro de contrat'])[1]/preceding::span[3]</value>
      <webElementGuid>bbcfb20a-34fa-4f48-9264-226a03880a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro d’avenant'])[1]/preceding::span[3]</value>
      <webElementGuid>c4683248-eb08-49b5-8877-e096c5b8b496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/span/span/span/div/span</value>
      <webElementGuid>bf9cd240-5f41-4f0d-800f-50f77e7232f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'En cours de création' or . = 'En cours de création')]</value>
      <webElementGuid>3a336fb9-a2b2-4359-a8ae-45687ab56236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
