<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DocumentSignFile</name>
   <tag></tag>
   <elementGuidId>4ed27114-988c-4781-bdd6-5022de2cd559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file_field_namCavenantFichier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file_field_namCavenantFichier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#file_field_namCavenantFichier</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92fbf87d-4cd8-44b7-9bd6-5c007d3973ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>5bb664a6-7974-4714-9469-b03554a7fcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>497e123c-7d42-4fd2-9d10-9dbb7c3692f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_field_namCavenantFichier</value>
      <webElementGuid>8d9f025a-f262-4d16-b270-1f22457365d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file_field_namCavenantFichier&quot;)</value>
      <webElementGuid>f8aea2c7-324b-4b7f-9b89-c5a4a82f2749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file_field_namCavenantFichier']</value>
      <webElementGuid>876756cc-b8db-4eb5-ab10-fbd9af676065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_NamContratAvenant_the_ajax_NamContratAvenant_55158']/div/div[2]/form/div/div/div[2]/div[4]/div/div/div/div/div/input[3]</value>
      <webElementGuid>383ce803-64da-4da9-95e0-6ded0f1b529f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>ae8c8b03-ddd9-4e6c-b88b-56f4812e0694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file_field_namCavenantFichier']</value>
      <webElementGuid>ad9d4516-6a07-4873-801c-25f4eab1399e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
