<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CentreEpideSouhaite</name>
   <tag></tag>
   <elementGuidId>414d0f75-5fd8-4f40-a95f-8344f301a430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namCavenantNomCntDestination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bde41b8-7e91-4932-9118-edf71c313fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2412bc9d-a880-44ea-8a46-38e06a025a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>764e4884-f36c-4aa4-a8ee-e53a0f903f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lanrodec</value>
      <webElementGuid>041be408-d75e-43fd-a3a8-0dbbd2ea77c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      <webElementGuid>9d049138-c2ea-4f06-b6e8-5e55dd80f6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      <webElementGuid>3c7039b9-9fee-4cf8-8569-abedd2524721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a50fcf9e-81dd-41bd-96bc-4337a3f9b5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>98e3cdfb-c3f3-4853-a9b7-a9aafd767d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>400a8e7c-1200-483b-b183-40bd0f2ae396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre&quot;)</value>
      <webElementGuid>41502b8a-0c20-47a1-a22d-58dece0d438a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre']</value>
      <webElementGuid>0dd28ec2-e976-4dd7-bed4-0113a3aebbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>2e7a82bd-5245-4b5a-9465-7c84627f16de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>f11bf555-beef-434a-ba32-48703f1edfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre' and @name = 'NamDemandeTransfertCentre_NamCentre_fk__namNomCentre']</value>
      <webElementGuid>d9439ceb-8ee8-4bca-8207-e1119b6e1908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
