<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CentreEpideSouhaite</name>
   <tag></tag>
   <elementGuidId>414d0f75-5fd8-4f40-a95f-8344f301a430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb2bfcaf-c227-4363-b670-410db275073c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6d8b55b3-8f68-4e37-8108-150663b96333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf4abe9f-a0bf-4a78-9af0-2d192c284aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lanrodec</value>
      <webElementGuid>46882328-f73c-46d9-9d0d-574e3a28489b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      <webElementGuid>fbb826ef-a12c-4767-959a-2c69ae77cd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamDemandeTransfertCentre_NamCentre_fk__namNomCentre</value>
      <webElementGuid>83a760f2-f1c5-401e-8db5-8d9fe5ddd247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>48d0fed7-af62-4220-a5e4-d2061f83bf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>31a468e0-c973-4e87-a127-e8a4f9f9b750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c3696596-6541-48c5-bf0e-c21e312ba6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre&quot;)</value>
      <webElementGuid>54c71e54-a8fb-437d-85b7-668dd55c151e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre']</value>
      <webElementGuid>fdf037d1-9a07-44e4-aff9-5803811e6435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>1f82c2fe-8afb-4e8c-81c6-46a3fba682b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0b4131dc-588a-49c2-a907-b081b24b82f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_NamDemandeTransfertCentre_NamCentre_fk__namNomCentre' and @name = 'NamDemandeTransfertCentre_NamCentre_fk__namNomCentre']</value>
      <webElementGuid>9c3e1db6-61c2-4539-bd9d-6722e71c87db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
