<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_Volontaires</name>
   <tag></tag>
   <elementGuidId>c7da7502-6e2d-40f4-b3a5-72032a623ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/nav/ul/li/ul/li[6]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub-menu > li.active > ul.sub-menu > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Volontaires&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4025e67b-93ae-4634-a8fd-4c7329a3f6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-obj</name>
      <type>Main</type>
      <value>NamVolontaire</value>
      <webElementGuid>f08da38f-43cd-4a42-bce1-efd2d0c7526d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>f87e15c7-5dcb-4c19-a624-cf77c2c1c85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Volontaires</value>
      <webElementGuid>67d7c4d5-7f51-4843-98fa-aaba15d644dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;main-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>ccaa0293-a8ab-481d-bf9b-ac0e87747c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/nav/ul/li/ul/li[6]/ul/li/a</value>
      <webElementGuid>2eaeea8e-37c1-4132-aedf-f95e37b17929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des volontaires'])[1]/following::a[1]</value>
      <webElementGuid>7109f2ac-69d8-4da7-96b6-320dfe480919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissibles'])[1]/following::a[2]</value>
      <webElementGuid>a97c8ed9-9aa0-47a3-b7ca-13f37997c850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feuille de présence'])[1]/preceding::a[1]</value>
      <webElementGuid>ea5946f2-a3b9-4c8a-9e93-92e3b7755477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[15]</value>
      <webElementGuid>8ac85e30-68b5-4c83-b49e-e4f82c28130d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>2880538b-76c6-4f87-a8ad-f1e53b7861d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Volontaires' or . = ' Volontaires')]</value>
      <webElementGuid>29d4388f-62a6-4db5-a0b2-04db6b59ad13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
