<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CommentaireSurEtatBucco-Dentaire</name>
   <tag></tag>
   <elementGuidId>8270a339-1884-48b2-92e7-b9f79f94eb50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenComtBuccoDentaire</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenComtBuccoDentaire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenComtBuccoDentaire</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>492b5a45-b58f-45af-bd68-5baf82ed3577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-container</value>
      <webElementGuid>2485f9d5-99a2-4237-8239-d0b5f460b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>604c480b-e920-445b-9228-fb5a5b28fe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenComtBuccoDentaire</value>
      <webElementGuid>127a58e0-3041-46de-bdfd-f38cb08ca0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenComtBuccoDentaire</value>
      <webElementGuid>00f6fc44-edba-41c9-8218-d2beb31b8013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>498cf546-f757-4244-a1ee-2420516b5260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ed372b8-9436-489c-b0a5-5515b869ff0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>15d1d010-2c14-46a7-b781-1241f68ba6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenComtBuccoDentaire&quot;)</value>
      <webElementGuid>64f1bfc7-d1d9-4b88-adc0-56afcb47dd4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenComtBuccoDentaire']</value>
      <webElementGuid>c935c951-6320-4025-bbe2-4b334c8759f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area22']/div[2]/div[3]/div/input</value>
      <webElementGuid>b8efc240-d097-4f44-ac5a-4769bf486285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>e5e8b7aa-bc96-4b96-b463-4866b941d273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namJenComtBuccoDentaire' and @name = 'namJenComtBuccoDentaire']</value>
      <webElementGuid>00e7c24b-5438-46f0-80f6-c50278e06aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
