<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_AntecedentsFamiliaux</name>
   <tag></tag>
   <elementGuidId>a612b2a0-8497-4467-887a-434ca731a99d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenAntOrdreFamiliaux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenAntOrdreFamiliaux']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenAntOrdreFamiliaux</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0663fea-66a2-4098-b4d9-b3a11fa11c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7312843a-99b4-4c07-816e-381b8de50d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenAntOrdreFamiliaux</value>
      <webElementGuid>a4c8ab32-168a-470e-a5b6-1325ac4bf3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenAntOrdreFamiliaux</value>
      <webElementGuid>b160650e-c2ca-4142-8680-8736bf9c2b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cd104df3-4e27-40b8-9a27-ed2411967468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bc1fa89e-01e0-4e35-a48f-8176a6a0c81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1743dea4-36fb-46c6-a607-dcf2df235cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenAntOrdreFamiliaux&quot;)</value>
      <webElementGuid>93b053b0-35c8-465e-9840-c0651eb000bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenAntOrdreFamiliaux']</value>
      <webElementGuid>3840df14-8434-42b8-b83a-3ad540816071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c32f52a2-db63-439d-b1b3-5f2f9c671959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c1918bff-7d99-4b59-8c3e-1372f0a6dd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenAntOrdreFamiliaux' and @name = 'namJenAntOrdreFamiliaux' and @type = 'radio']</value>
      <webElementGuid>a986850e-12b0-4a7c-b8b6-aa95d0cebeb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
