<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_PrisUnTraitementPendantPlusDunMois</name>
   <tag></tag>
   <elementGuidId>ee6c9157-8aef-4f22-b257-5db87d734b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTraitementPlusMois</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTraitementPlusMois']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTraitementPlusMois</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>472e80c8-9c0f-491b-a3c7-af1aa718542f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d3116f75-257f-43e8-a9ad-7af8805a13ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTraitementPlusMois</value>
      <webElementGuid>3f4997b5-d9e7-45ee-97ba-da269c5466d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTraitementPlusMois</value>
      <webElementGuid>4c215b89-b330-4f72-9c62-2ca4726a9ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8b438a9a-23b5-4464-8815-7d8a019a88f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0954a98c-9cc8-43f6-a388-df0e67cc4cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b31bff50-c590-428e-94eb-eba93131ff25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTraitementPlusMois&quot;)</value>
      <webElementGuid>3a9bb667-4397-43de-a4d7-547b7ec3573c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTraitementPlusMois']</value>
      <webElementGuid>a7a8177a-fedd-4b55-87cf-1a03b26ae91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div[2]/div[8]/div/div/div/input</value>
      <webElementGuid>37bdd437-612a-4e49-bc08-3ea0aba9bf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>4bcfc601-e85d-4ae3-9f09-e3fae6f512c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenTraitementPlusMois' and @name = 'namJenTraitementPlusMois' and @type = 'radio']</value>
      <webElementGuid>4acf85ca-f59f-418c-91ae-aa311160cdc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
