<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_Avez-vousDejaEuUneEntorseGrave</name>
   <tag></tag>
   <elementGuidId>42622ab5-2bb5-4f2a-a5ec-7436136b06f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenSubitEntorseGrave_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenSubitEntorseGrave_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenSubitEntorseGrave_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dfa721a-3fe6-4226-9400-d315e001ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>09ca1b82-f7af-4e44-8a32-1ac5d0ee8db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenSubitEntorseGrave_no</value>
      <webElementGuid>ffe2a7b4-8cbd-484d-85da-96198f1cac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenSubitEntorseGrave</value>
      <webElementGuid>698b4790-ad86-42c3-a0e1-4fb3792aad9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>51739427-6209-4bb0-b1ed-7284b73212e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8af7af4-3e5e-4c60-8093-04287983f462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenSubitEntorseGrave_no&quot;)</value>
      <webElementGuid>2f14ac98-1bd2-4dfe-a9f9-f193cd08e09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenSubitEntorseGrave_no']</value>
      <webElementGuid>42137f23-d462-440f-b940-eca724722367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div[2]/div[15]/div/div/div[2]/input</value>
      <webElementGuid>a50b1a52-f3ad-4107-b68f-fc15464a0bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div[2]/input</value>
      <webElementGuid>2c5d5fcb-5568-441f-b91e-051fa5689dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenSubitEntorseGrave_no' and @name = 'namJenSubitEntorseGrave' and @type = 'radio']</value>
      <webElementGuid>ea2b6de4-536e-43fe-af0a-e4f4943ed7b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
