<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_NecessiteUneConsultationOphtalmologique</name>
   <tag></tag>
   <elementGuidId>009c8cf8-9506-4d76-9b98-3fc69d6a3237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenNecessiteConsulterOphta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenNecessiteConsulterOphta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenNecessiteConsulterOphta</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb3473b4-679f-43e7-b773-64a427dd1ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2d06e19f-b172-482b-92c6-252a96952364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenNecessiteConsulterOphta</value>
      <webElementGuid>a137f103-b201-4d6a-9a48-954121b67164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenNecessiteConsulterOphta</value>
      <webElementGuid>079db1fb-1c9f-4332-b9c1-956e9f1dafdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ff6130da-2de2-4959-8627-907dddfcf998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>88b4dea3-ae09-48dd-9eea-c8b430d8705c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>53db7dbd-989b-4af4-974f-9130aa443980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenNecessiteConsulterOphta&quot;)</value>
      <webElementGuid>a8e85ed7-0fc1-47e4-8709-7acb5f695cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenNecessiteConsulterOphta']</value>
      <webElementGuid>3920418c-81e9-4982-bff9-583673963d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area21']/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>dcb96083-e13d-4bef-9175-e14c920a2edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>dc423b2c-061a-4324-9dec-47266d2f05fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenNecessiteConsulterOphta' and @name = 'namJenNecessiteConsulterOphta' and @type = 'radio']</value>
      <webElementGuid>2268add0-f5dc-4a3e-9e10-addb0f1e253e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
