<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_DTPPrevoir</name>
   <tag></tag>
   <elementGuidId>bb94cd05-10da-4091-92bd-73565d18e546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenPrevoirVaccinDtp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenPrevoirVaccinDtp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenPrevoirVaccinDtp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>639f278e-fa57-4c8a-a369-3f93f8090055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f2d75da4-2658-4ab6-9a63-4a4dcf223cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenPrevoirVaccinDtp</value>
      <webElementGuid>8232c3ab-1e0d-4697-b263-64a9b9872d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenPrevoirVaccinDtp</value>
      <webElementGuid>f56baba2-bf1a-48d9-ae76-674618c4bbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>79293ecc-f23a-4b47-99cf-e318c5720876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0cbb9cd0-3c99-4f4c-a6cb-a5be6c34a800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b7537f29-04f1-477e-a430-9a4519f2dbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenPrevoirVaccinDtp&quot;)</value>
      <webElementGuid>fd961ce9-3700-4013-b0c9-e83bd741db63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenPrevoirVaccinDtp']</value>
      <webElementGuid>5e45303e-5cd3-401e-836d-bc7cc9efc005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area17']/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>6a9fe51c-e5c4-4b97-8fc7-77e828cb6eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>e86b889e-e844-4826-af96-ac5f866e98a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenPrevoirVaccinDtp' and @name = 'namJenPrevoirVaccinDtp' and @type = 'radio']</value>
      <webElementGuid>6433ba2f-74ff-46e3-8fb2-33d020c80c68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
