<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_NecessiteUneConsultationDentaire</name>
   <tag></tag>
   <elementGuidId>25b312ab-b92d-44ed-87ab-0c93e44b3086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenNecessiteConsulterDentaire_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenNecessiteConsulterDentaire_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenNecessiteConsulterDentaire_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d80bafc8-9ca1-4bac-b76f-9bb2fe07e787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e6e705c6-7ffd-4355-9f4c-31d6e20b140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenNecessiteConsulterDentaire_no</value>
      <webElementGuid>90775824-1f73-4543-98e8-c41294922a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenNecessiteConsulterDentaire</value>
      <webElementGuid>d2f21e81-c710-4c24-bbf4-fc4431c34862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>969283f7-d2bd-4465-8c19-000cc39dfa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af6157f0-a95d-4b08-b486-400c1ea89de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenNecessiteConsulterDentaire_no&quot;)</value>
      <webElementGuid>9c1be102-e90c-4bd0-bd6f-bffa8617d66b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenNecessiteConsulterDentaire_no']</value>
      <webElementGuid>2b75aa98-56c3-4765-87b2-88b81a5f3f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area22']/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>583b92f9-edf3-4b19-be73-c477e9f94830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>c5ba0a52-72c3-4f40-be72-f8e613b90524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenNecessiteConsulterDentaire_no' and @name = 'namJenNecessiteConsulterDentaire' and @type = 'radio']</value>
      <webElementGuid>7004a801-da9f-45e5-8119-190d19f52c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
