<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_Avez-vousDejaFaitUneTentativeDeSuicide</name>
   <tag></tag>
   <elementGuidId>e5448008-a320-452d-a8a3-a32e6b5266a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTentativeSuicide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTentativeSuicide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTentativeSuicide</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fcfe1da-c66d-4dd5-a10d-dc3e75415418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fdac1cd1-c427-4143-8ac4-b8c3c0958fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTentativeSuicide</value>
      <webElementGuid>9d436f5f-bb8e-42b2-8e32-7daa2705b33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTentativeSuicide</value>
      <webElementGuid>ccf9ea6e-4103-4886-a132-b94175fba13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>51794f15-a9ac-462e-aaf2-d62324cd21c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c1616e8-8c7a-4363-81c3-a5db233378b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>775c4d71-196d-4b6a-927b-d4e28a0d1542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTentativeSuicide&quot;)</value>
      <webElementGuid>30d9c758-df82-4029-ae88-3180ee46ca14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTentativeSuicide']</value>
      <webElementGuid>e44c004c-fc20-4e41-9fa4-b4edd828b0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div[2]/div[20]/div/div/div/input</value>
      <webElementGuid>982115f5-89bf-436c-9574-ce0625f58b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/input</value>
      <webElementGuid>9bbcbb07-9339-4c55-a270-2890ebcb0e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenTentativeSuicide' and @name = 'namJenTentativeSuicide' and @type = 'radio']</value>
      <webElementGuid>ab9e170c-eafd-432a-af02-5460d432485c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
