<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_Avez-vousDejaEtEconduitAuxUrgences</name>
   <tag></tag>
   <elementGuidId>d2b75a0b-31f1-44d3-b9b0-44268d33361a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenHospitaliserUrgence_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenHospitaliserUrgence_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenHospitaliserUrgence_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5092088-9a10-4ea1-b3a0-8700a6c7cb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e9838c96-de52-4ad0-8c67-9d76518df724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenHospitaliserUrgence_no</value>
      <webElementGuid>e398a113-08bc-44c9-b475-1d6c3fd282c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenHospitaliserUrgence</value>
      <webElementGuid>58a0cf9d-9dad-4c97-8dbe-0488905c6ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b422f64d-a37d-4aed-bff1-352917043a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d5dc05f-4807-41be-b91d-6324efd57f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenHospitaliserUrgence_no&quot;)</value>
      <webElementGuid>6868f3b3-b667-47c0-880d-5bb23011c4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenHospitaliserUrgence_no']</value>
      <webElementGuid>73caaa26-6865-4469-902a-c134f1835a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div/div[6]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>0c489aa5-adbc-4925-affa-465a3b86f236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/div/div[6]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>658c662b-464d-4a3c-846c-9b18908a1b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenHospitaliserUrgence_no' and @name = 'namJenHospitaliserUrgence' and @type = 'radio']</value>
      <webElementGuid>d016a14b-f027-45e5-95d4-cfa17c0d7597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
