<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_Avez-vousDejaPerduConnaissance</name>
   <tag></tag>
   <elementGuidId>1145e167-f092-4fa0-8371-2663e69cec32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenPerduConnaissance_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenPerduConnaissance_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenPerduConnaissance_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca3d14b1-7240-4bec-989f-98ffb510c78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b05499de-1d43-4153-a527-b9d4309a35bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenPerduConnaissance_no</value>
      <webElementGuid>30902ebe-b504-4f0a-9e49-70839d8dafe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenPerduConnaissance</value>
      <webElementGuid>25118bae-45aa-4ebc-a008-abc58e4025c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a9177415-ccaa-4e0f-8152-37e056258d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af9de7b5-e848-42f9-bb7c-be84491c1197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenPerduConnaissance_no&quot;)</value>
      <webElementGuid>7a616ee2-6cbf-4198-a272-c1c4c238c92b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenPerduConnaissance_no']</value>
      <webElementGuid>df6a0f1a-03eb-45c6-8b5e-8686c8df9d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div[2]/div[10]/div/div/div[2]/input</value>
      <webElementGuid>f274b108-f6b3-4692-9ab2-43348508d363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/input</value>
      <webElementGuid>7b6b7915-3992-4723-91d2-e2746a404ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenPerduConnaissance_no' and @name = 'namJenPerduConnaissance' and @type = 'radio']</value>
      <webElementGuid>b6bf8189-6f3d-40d1-a7c7-a7af4b7ab479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
