<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_OUI_Utilisez-vousUnMoyenDeContraception</name>
   <tag></tag>
   <elementGuidId>54779791-342a-4df2-bb09-285b664b311e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenMoyenContraception</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenMoyenContraception']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenMoyenContraception</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3282fd37-96a6-4b85-b439-a92e04087df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>393ffc9b-9eb4-4912-bbf1-7968c3be81f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenMoyenContraception</value>
      <webElementGuid>df22ef32-95a1-45be-90d9-b8fefd06990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenMoyenContraception</value>
      <webElementGuid>c22d73aa-e016-45b8-8e5d-66c0a7ebbc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9c52ad36-954b-422b-8390-f700e6f9c532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fbb413be-a2d8-4a2f-9d02-e2e5539eedd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>fd8880f4-fa6f-4b19-a3de-37cab1e19023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenMoyenContraception&quot;)</value>
      <webElementGuid>3186f18d-3c94-41f2-90d9-35503e42645e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenMoyenContraception']</value>
      <webElementGuid>d6e0c6ed-43a9-4584-a69f-7637991376b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area19']/div[2]/div/div/div/div/input</value>
      <webElementGuid>c25fa141-4bde-42a5-bd81-3235fa2323b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>be090a45-46dc-46e7-abcd-02fde8acb05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenMoyenContraception' and @name = 'namJenMoyenContraception' and @type = 'radio']</value>
      <webElementGuid>b2d89540-be8e-46ee-a0ac-5f1675c30c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
