<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_NON_Avez-vousDejaFaitUneTentativeDeSuicide</name>
   <tag></tag>
   <elementGuidId>1ba27cbf-f5a9-4a75-8230-cd1651055b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namJenTentativeSuicide_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namJenTentativeSuicide_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namJenTentativeSuicide_no</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04097418-be6b-4198-9316-f0cf4727e241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>30723ad2-ec13-43f3-9fb1-5916bd4cb3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namJenTentativeSuicide_no</value>
      <webElementGuid>32f5c9f2-0283-4cb7-8191-4cb78bc1766d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namJenTentativeSuicide</value>
      <webElementGuid>e7d168bb-1f6a-4a95-8c29-b0dffe9c108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>988bae3b-5218-466b-bccd-92850ef846cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78c2b930-bc1a-4509-9d4a-a96590af8dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namJenTentativeSuicide_no&quot;)</value>
      <webElementGuid>3a28845f-6cc6-4d74-acf7-749d71f199b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namJenTentativeSuicide_no']</value>
      <webElementGuid>259cead2-42ef-4f05-971e-18c7966731c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area18']/div[2]/div[20]/div/div/div[2]/input</value>
      <webElementGuid>5b9af9e4-2038-4f72-8570-1b3098a68127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div[2]/input</value>
      <webElementGuid>eb388009-740a-45f6-a166-cce08cad8ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field_namJenTentativeSuicide_no' and @name = 'namJenTentativeSuicide' and @type = 'radio']</value>
      <webElementGuid>c71e8a63-222e-417d-86e7-1f2f4d7f2a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
