<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_AcuiteVisuelle</name>
   <tag></tag>
   <elementGuidId>6a4e7746-a1a0-4209-b8a2-100052f0fef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel_work_21 > div.card > div.card-header.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel_work_21']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Acuité visuelle$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ac7f1cf-f66c-4aa1-a9ee-97ff7007227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header collapsed</value>
      <webElementGuid>7bbb0bfc-db1e-4626-a203-cd020374cb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>3161e980-d5df-4e1b-9e56-73744ec6bfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse_panel_work_21</value>
      <webElementGuid>edb2b4f2-4d50-4ff6-b4e5-d678b9ae4200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acuité visuelle</value>
      <webElementGuid>4cdc7523-f4b5-4d08-9292-fd4b738033a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel_work_21&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header collapsed&quot;]</value>
      <webElementGuid>e0fe8bf6-c323-4d63-b06d-c91895ad267e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel_work_21']/div/div</value>
      <webElementGuid>ea1ce6ce-601b-4d21-b85f-334a5dd6c2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pouls'])[1]/following::div[4]</value>
      <webElementGuid>d0473f8d-0d01-4292-8d8d-d17a78de093c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TA'])[1]/following::div[6]</value>
      <webElementGuid>92e3bed3-083e-49e4-802f-d2165830563e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portez-vous des lunettes ?'])[1]/preceding::div[1]</value>
      <webElementGuid>d1b70818-e155-40a0-a190-94d99b879c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div</value>
      <webElementGuid>e90f3fcc-b621-49eb-af04-b1de14ba4030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Acuité visuelle' or . = 'Acuité visuelle')]</value>
      <webElementGuid>2bb500d6-0f0c-44af-8b76-2b3c7118dc4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
