<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_Antecedents</name>
   <tag></tag>
   <elementGuidId>249b8701-778a-4ae6-93dc-3c0b37fc41a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel_work_18 > div.card > div.card-header.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel_work_18']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Antécédents$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6fe095e-7018-4714-9bff-755a3fbffcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header collapsed</value>
      <webElementGuid>a1430134-6801-48f1-9e2f-be97b09266ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>60516a06-d31c-4291-8ce1-181c3f0066fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse_panel_work_18</value>
      <webElementGuid>ba150501-8af2-456e-8973-9eb3aa783f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d563c37-1526-483c-b31d-22b2fcb569c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Antécédents</value>
      <webElementGuid>3e10f1f2-345f-481b-a58e-74062c5482b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel_work_18&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header collapsed&quot;]</value>
      <webElementGuid>9f9351a4-403a-4d1b-bd09-78c32ff91c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel_work_18']/div/div</value>
      <webElementGuid>a49dc195-d70e-46ef-b05a-34aedeca627a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autres vaccins'])[1]/following::div[4]</value>
      <webElementGuid>4ddc3189-1e1d-47df-8af7-f06ed95185a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROR'])[1]/following::div[6]</value>
      <webElementGuid>8ba7703b-19c1-4d02-b6a9-dd9c1af05884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oui'])[55]/preceding::div[1]</value>
      <webElementGuid>e3ceb3e0-b3ed-4e1d-bd88-5a5c68a762fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[13]/div/div/div</value>
      <webElementGuid>d61422f5-d0bf-47aa-83eb-2e95d1dc0764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Antécédents' or . = 'Antécédents')]</value>
      <webElementGuid>9ac41b2a-e750-43ba-9851-1d1cfe5947ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
