<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_ContratInsertion</name>
   <tag></tag>
   <elementGuidId>817cb299-b27d-4717-928b-5f9d57746e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-left.enum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_NamContratAvenant_panel_ajax_NamContratAvenant_namCavenantScoId']/div/div[2]/form/div/table/tbody/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Contrat d'insertion&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>848a92bc-a485-4996-83db-e3687070a3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left enum</value>
      <webElementGuid>24880a31-5d70-4ad7-b376-e35759143e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contrat d'insertion</value>
      <webElementGuid>9eed9290-e060-4fc3-85a2-3714270d25b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamContratAvenant_panel_ajax_NamContratAvenant_namCavenantScoId&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;container-table table-responsive&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;list-clickable js-resizable&quot;]/td[2]/div[@class=&quot;text-left enum&quot;]</value>
      <webElementGuid>cbd32131-b337-43b5-b79c-492e24921ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamContratAvenant_panel_ajax_NamContratAvenant_namCavenantScoId']/div/div[2]/form/div/table/tbody/tr/td[2]/div</value>
      <webElementGuid>e50625dd-12cd-46c7-8bd3-bacfd731c631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Générer document'])[1]/following::div[1]</value>
      <webElementGuid>dfa2c1b5-0b1f-44e6-a3e0-d7315d7dd5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom du centre EPIDE'])[1]/following::div[6]</value>
      <webElementGuid>219f8509-5e70-4407-a496-a121c41c9aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A signer'])[1]/preceding::div[1]</value>
      <webElementGuid>f1fc2e2f-2a90-41d7-97e4-bc2587e83ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bordeaux'])[1]/preceding::div[7]</value>
      <webElementGuid>a7e30249-025f-4bc6-9aff-de4f7cf0eef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>0bbaffd1-6d10-4187-ab8e-dc9125c580b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Contrat d&quot; , &quot;'&quot; , &quot;insertion&quot;) or . = concat(&quot;Contrat d&quot; , &quot;'&quot; , &quot;insertion&quot;))]</value>
      <webElementGuid>21f57912-8618-43e6-96e8-dbc48babc920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
