<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Creer</name>
   <tag></tag>
   <elementGuidId>584c2127-2697-4a6a-a2f5-015f79d2a26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_NamAvisCandidat_panel_ajax_NamAvisCandidat_namAviscanJenId > div.card.panel-list > div.card-header > div.head > div.list-actionbar > div.actions.pull-right > button.btn.btn-secondary.btn-create</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Créer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d19b47b6-2e22-455f-82db-783dfc2077ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-create</value>
      <webElementGuid>123b9178-520c-4b91-9d4a-80c82cdbd893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc1e1fb4-f8a1-452c-ab2d-72d40568510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>bcaa6d9a-b806-4574-b673-3d9f39e00261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Créer</value>
      <webElementGuid>532a6b7d-5e0a-4f64-bf15-fcab049a3461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_NamAvisCandidat_panel_ajax_NamAvisCandidat_namAviscanJenId&quot;)/div[@class=&quot;card panel-list&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;head&quot;]/div[@class=&quot;list-actionbar&quot;]/div[@class=&quot;actions pull-right&quot;]/button[@class=&quot;btn btn-secondary btn-create&quot;]</value>
      <webElementGuid>4e0b9ee4-45e7-4873-967d-0197b80ab796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>f41b7222-3b93-41e9-ac91-2f124ac325f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamAvisCandidat_panel_ajax_NamAvisCandidat_namAviscanJenId']/div/div/div/div[3]/div/button</value>
      <webElementGuid>1bc90a9c-91cd-4aae-b123-c0b1bcd47b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 0'])[3]/following::button[1]</value>
      <webElementGuid>bc5f8292-cbbf-4076-b361-015f717e9fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avis sur les candidats'])[1]/following::button[1]</value>
      <webElementGuid>d77c5097-27c3-4c72-bfe7-44f499c39372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div[2]/div/div/div/div/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>02438949-d585-4d88-a2a0-03a2badc82a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Créer' or . = 'Créer')]</value>
      <webElementGuid>d6979b5a-544a-49b0-a1ef-0145d0bd9777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
