<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prenom_candidats</name>
   <tag></tag>
   <elementGuidId>3f8370c0-d859-426c-b3a3-4febf85d2936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namPrenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namPrenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namPrenom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf32ec66-b4e4-4341-ab7f-026301a4cb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>98814d75-019f-41f3-b854-f22bbf11e920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namPrenom</value>
      <webElementGuid>e11379e8-5023-4a4c-8738-a3957b5c25f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c65f8652-b183-4307-9d2c-2fdf701610fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namPrenom&quot;)</value>
      <webElementGuid>b9546d43-b295-4fbe-a7aa-351155670c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namPrenom']</value>
      <webElementGuid>c8f64267-9b6a-4a22-abc0-97ea0943cae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamCandidat_the_ajax_NamCandidat']/div/div[2]/form/div/table/thead/tr[3]/th[4]/div/input</value>
      <webElementGuid>4d413afc-93a0-4597-b41d-9f4e8a6daff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/input</value>
      <webElementGuid>9b1eef42-f854-494e-a325-6c9707bc146b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namPrenom']</value>
      <webElementGuid>c0404b23-7805-424a-82bf-e5a8251f325d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
