<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CommentaireGeneralAvis</name>
   <tag></tag>
   <elementGuidId>58d88b35-04c8-4d48-8290-ba749f218711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namAviscanComGeneral</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namAviscanComGeneral']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namAviscanComGeneral</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ddc18927-5b00-478c-ab83-bc00650ac4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>4f82bb39-81b5-4ef6-88fc-df72d3bad629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namAviscanComGeneral</value>
      <webElementGuid>7fc0d276-aff3-46ba-9e27-00af1753f2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namAviscanComGeneral</value>
      <webElementGuid>d599e8b3-f90c-4119-9693-7412429564e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b645be8d-a772-49a5-b1ff-3731bbbe4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>877ebfaf-9972-4867-b069-5b109c43285e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namAviscanComGeneral&quot;)</value>
      <webElementGuid>9b318ec0-7163-474f-80e6-d4b51e7065fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namAviscanComGeneral']</value>
      <webElementGuid>a4f9af96-1d57-4e7c-b081-0a830ee2643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[3]/div/div/textarea</value>
      <webElementGuid>d69f5b05-0138-4f30-93dc-4024f9bbc065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6b0054cb-6baf-43d8-9f41-ed6e2e2ba234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namAviscanComGeneral' and @name = 'namAviscanComGeneral']</value>
      <webElementGuid>64a1f242-09ae-4e2e-b779-68037a7ddbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
