<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prenom_candidatures</name>
   <tag></tag>
   <elementGuidId>bc436a59-83e5-41c3-a517-130128ea22ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namCanJenId__namPrenom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namCanJenId__namPrenom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namCanJenId__namPrenom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1dca35d-164a-4a23-86df-86f188b5d090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>da077fc2-c168-4dc2-890e-d709b028b5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namCanJenId__namPrenom</value>
      <webElementGuid>14ed644d-1fbd-42b3-94a2-4df762900f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5b7a2765-da26-469a-a6d4-9c6ce53ac82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namCanJenId__namPrenom&quot;)</value>
      <webElementGuid>a37fff0c-76c0-4754-9d7c-d5c2ec639cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namCanJenId__namPrenom']</value>
      <webElementGuid>260d92f3-0cfa-46a5-998c-8d4c873ce293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamCandidature_the_ajax_NamCandidature']/div/div[2]/form/div/table/thead/tr[2]/th[8]/div/input</value>
      <webElementGuid>05ae185c-d5d0-4241-bee0-10b69ad01883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/input</value>
      <webElementGuid>7f0f2e8f-9a54-48f9-a7f4-1d46da2d1b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namCanJenId__namPrenom']</value>
      <webElementGuid>77f06e4b-0fc4-48dc-b466-db4c8db0920e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
