<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_CreationFSE</name>
   <tag></tag>
   <elementGuidId>856bf5b1-925a-44e5-b367-a569997cab9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namFseStatut-container > div.enum-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namFseStatut-container']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Création FSE&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0080519c-0211-4379-b00c-aa49fdafc428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>e9139353-3d27-4878-bcfc-af10845b93b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Création FSE</value>
      <webElementGuid>53f5ec45-b413-40c7-8e61-534d8f299dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namFseStatut-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>c09a8264-4461-43b2-9da7-ee5a37716979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namFseStatut-container']/div</value>
      <webElementGuid>1620511b-ca86-4473-938e-1de411505606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut de FSE'])[1]/following::div[1]</value>
      <webElementGuid>2e9c811b-6467-48ec-858c-5126c2c5fc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observation'])[2]/following::div[5]</value>
      <webElementGuid>1b8d5df5-d47e-49c3-a77d-8e887e8b504e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rédacteur'])[1]/preceding::div[1]</value>
      <webElementGuid>31020d5d-1e2b-4853-8d11-17fdc9953995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/span/span/span/span/div</value>
      <webElementGuid>1d7569d2-7d5b-4023-835f-0e37befa335a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Création FSE' or . = 'Création FSE')]</value>
      <webElementGuid>1feebe95-68fe-40a5-a17b-51c3fc1cd492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
