<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Elem_ValidationConseilD1</name>
   <tag></tag>
   <elementGuidId>949e0bd3-7b47-4434-8bf3-f592da7369da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-field_namFseStatut-container > div.enum-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-field_namFseStatut-container']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Validation conseil D1&quot;i >> internal:text=&quot;Validation conseil D1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67b853ac-b02a-4426-b33a-17d463fba96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validation conseil D1</value>
      <webElementGuid>455f2bd9-a406-4a08-b259-51ebcf86beff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namFseStatut-container&quot;)/div[@class=&quot;enum-item&quot;]/span[1]</value>
      <webElementGuid>c063f270-8207-4652-afbc-18e4d863b10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namFseStatut-container']/div/span</value>
      <webElementGuid>d5e63b0c-7a5d-472b-a6f3-3c7f43da9685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut de FSE'])[1]/following::span[5]</value>
      <webElementGuid>f4f8969b-9ff4-4b9b-9bbc-cabc914f4b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retard/Absence'])[2]/following::span[7]</value>
      <webElementGuid>21628edf-2748-44a7-8261-7ea4224847ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rédacteur'])[1]/preceding::span[3]</value>
      <webElementGuid>301167f9-f882-4a3e-9a4c-3d9c6edb0adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/span/span/span/span/div/span</value>
      <webElementGuid>c80fc5ad-f3a6-4ef1-8d52-286ba6303ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Validation conseil D1' or . = 'Validation conseil D1')]</value>
      <webElementGuid>9bb6a4ec-2a98-4dc3-ad56-4943f28d89bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
