<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EcheanceDexecutionDeLaSanction</name>
   <tag></tag>
   <elementGuidId>4f05abd3-d32c-469f-aac6-ad816a551372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namFseEntCecEcheanceSanction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namFseEntCecEcheanceSanction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseEntCecEcheanceSanction</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cb76e2f-c46c-4c7b-809d-5b4bf80a26ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2de400f9-8641-429d-903e-da642f80bc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>770977f0-58a3-415a-8c8f-98f6aeb3892c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseEntCecEcheanceSanction</value>
      <webElementGuid>70ac648c-d1a3-4a5f-b508-fae4eec30ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseEntCecEcheanceSanction</value>
      <webElementGuid>008fa5b2-76a6-43d1-8b1b-1011cbd636bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3db56474-e7c4-4484-922b-bdfad1552f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8dcc8cf6-5854-4ca7-bbfa-3348594eb0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>53daae2e-84bc-4978-aea6-fb968e4c238a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseEntCecEcheanceSanction&quot;)</value>
      <webElementGuid>7b0dbcc3-47ec-4ed7-8eff-cd15c2f5a87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namFseEntCecEcheanceSanction']</value>
      <webElementGuid>891dc7b2-7de3-4860-b245-beece6b525c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area4']/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>927903c7-6d46-453b-93af-455955ecf4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>d2cb95f2-9d7b-4463-865a-1c9c43f18168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namFseEntCecEcheanceSanction' and @name = 'namFseEntCecEcheanceSanction']</value>
      <webElementGuid>e9c142cc-4c6a-48ac-99fb-438261e3df11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
