<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AvisduConseildeDiscipline</name>
   <tag></tag>
   <elementGuidId>fbc06511-7219-4e3c-b343-3370aa955be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namFseConseilDiscAvis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namFseConseilDiscAvis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseConseilDiscAvis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ae3cd132-7ca9-499d-9465-3a1047fce968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>d84fb048-7f59-46c9-a8ad-67bca6e73a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseConseilDiscAvis</value>
      <webElementGuid>704bce11-b243-4749-8ee0-b941b4f593c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseConseilDiscAvis</value>
      <webElementGuid>90c09bdc-e12a-494a-98a9-57aac6b90400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>ea9a1cf3-b9a4-4c30-9bc3-50a42cddb511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>bb52f619-e547-4ebd-b762-dd708ee1ec28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseConseilDiscAvis&quot;)</value>
      <webElementGuid>37defd38-d18a-46af-8517-bc592517310f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namFseConseilDiscAvis']</value>
      <webElementGuid>0b1c4c6f-da40-4aae-ae6d-3f5d71233d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area7']/div/div[6]/div/div/textarea</value>
      <webElementGuid>5f6e7ce0-e6f2-46c0-9b37-257295b09f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div[6]/div/div/textarea</value>
      <webElementGuid>dd862575-c8f3-49b6-bc55-6bae1bad03cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namFseConseilDiscAvis' and @name = 'namFseConseilDiscAvis']</value>
      <webElementGuid>5f7ac7de-7c4f-473e-8549-d10c13068a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
