<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FSE</name>
   <tag></tag>
   <elementGuidId>ac532afe-6d80-43b0-b917-038b2e702de9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namFseJenId__namPrenom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namFseJenId__namPrenom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namFseJenId__namPrenom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0e78a6c-ce8f-406d-83c3-ddf0a529fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-control</value>
      <webElementGuid>d1e33f2c-a19e-41b8-a7dc-605c6949c9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namFseJenId__namPrenom</value>
      <webElementGuid>6ec1e85f-a786-45a3-93e0-3305eda6431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e245d68d-577d-487e-b83a-12f1ba48ef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namFseJenId__namPrenom&quot;)</value>
      <webElementGuid>d6e872b5-e1bf-4601-bcf4-6c629f1a10ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namFseJenId__namPrenom']</value>
      <webElementGuid>9a09c98a-c24c-46b4-b862-c5ab9b419749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_NamFse_the_ajax_NamFse']/div/div[2]/form/div/table/thead/tr[3]/th[10]/div/input</value>
      <webElementGuid>379a8fbf-3c02-46d8-93f0-e201bff5aede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/input</value>
      <webElementGuid>eaee3da0-54c9-4549-a9f5-413771d6ebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namFseJenId__namPrenom']</value>
      <webElementGuid>575b2662-46df-41ef-96db-5be402dd38a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
