<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reactions</name>
   <tag></tag>
   <elementGuidId>e26bc25a-7723-4205-9ba8-3d271ff8e9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namFseReaction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namFseReaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseReaction</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8957b788-e995-46b0-b529-ec6322116f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>4292daff-eefd-4ae0-a158-9eac99397cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseReaction</value>
      <webElementGuid>3aa3915c-edc3-44dd-9733-7a7bb279de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseReaction</value>
      <webElementGuid>4e04e15d-03c7-400a-a734-fd5f4d72ffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>44eee178-c59a-4127-bf12-085eeab5bb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>5490a3a2-51c3-4156-b642-40eff1d2e494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseReaction&quot;)</value>
      <webElementGuid>cae49ba8-4ab0-4d70-83fc-aff30ebe4c78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namFseReaction']</value>
      <webElementGuid>6a5b44eb-86f0-4288-97f7-701bc258aacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area1']/div/div[10]/div/div/textarea</value>
      <webElementGuid>172f22a5-51f9-4f9c-a1ba-7e1edf13a7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/textarea</value>
      <webElementGuid>62749762-9c87-4084-b52c-f59aac381f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namFseReaction' and @name = 'namFseReaction']</value>
      <webElementGuid>ddea8531-7428-4737-921a-617704498d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
