<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomduRapporteur</name>
   <tag></tag>
   <elementGuidId>ee1663f5-5a99-4311-b52d-5358f27dbe98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namFseUserRapporteur__usr_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field_namFseUserRapporteur__usr_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseUserRapporteur__usr_last_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87c4c888-e130-4ad6-8429-fcc9948a10c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ref-picker</value>
      <webElementGuid>b53ff61b-ffcc-4ca9-aa90-3ade9baf472c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45baa955-b2d6-4754-bc75-74d303a80ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseUserRapporteur__usr_last_name</value>
      <webElementGuid>44799e33-720a-48fe-a248-846a3789f832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseUserRapporteur__usr_last_name</value>
      <webElementGuid>6420c958-2179-479f-b576-2dff591c2408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0fd20d29-a4f1-42d9-846b-be005ede73b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>085f8033-d684-4c8a-bdc6-c9a50156befe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>47722362-b0db-4d9a-bfdc-441bc209c5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseUserRapporteur__usr_last_name&quot;)</value>
      <webElementGuid>fac428f1-2410-4d3f-a7d6-281ece33d12c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field_namFseUserRapporteur__usr_last_name']</value>
      <webElementGuid>b9ef33d0-d2a0-47dd-81ef-db47d9c28926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area8']/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>7ae26c05-2383-490b-b77e-9a71a5e205c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/input</value>
      <webElementGuid>74927dbc-01b9-4f91-9674-e5cf00312c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field_namFseUserRapporteur__usr_last_name' and @name = 'namFseUserRapporteur__usr_last_name']</value>
      <webElementGuid>db84807d-106e-4fd2-a447-4420a3901ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
