<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CommentaireVI</name>
   <tag></tag>
   <elementGuidId>a717d174-6273-452a-a122-a2d8efc2e26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namFseEntCecCommentaire']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_namFseEntCecCommentaire</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseEntCecCommentaire</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>87857709-fdfc-4a1b-89f2-bd7e27d03128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>13e3db67-975c-49af-bfd7-e307ba5f9130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseEntCecCommentaire</value>
      <webElementGuid>28687000-3bd6-4a3f-a8c2-24b20d605bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseEntCecCommentaire</value>
      <webElementGuid>3c334a62-a52d-4207-b82d-808a6b018530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>1434468e-4570-4802-a603-312fe5a3a39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>46d42353-0b47-43c5-a516-b554dea876f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseEntCecCommentaire&quot;)</value>
      <webElementGuid>88440f29-6b3e-493c-a987-97c4627c7d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namFseEntCecCommentaire']</value>
      <webElementGuid>f1030d5f-52d3-4491-82b6-ac84557f8f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area4']/div/div[6]/div/div/textarea</value>
      <webElementGuid>b7e02f8e-db6c-484c-b24b-082033b4495d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>4dc93166-0905-425d-9e5c-4fc6a65bed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namFseEntCecCommentaire' and @name = 'namFseEntCecCommentaire']</value>
      <webElementGuid>465c1328-483f-4918-826e-40c6ae4e003a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
