<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rub_FSE</name>
   <tag></tag>
   <elementGuidId>4f74f100-0d4a-4ba0-8aae-5953e8fe490c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.menu-sel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/nav/ul/li/ul/li[6]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xpath=//a[normalize-space()='FSE']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25fd8c6d-1334-4083-838d-fceb16b72a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-obj</name>
      <type>Main</type>
      <value>NamFse</value>
      <webElementGuid>83212481-3ae7-45aa-9749-68cbe1f986cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>b328b131-04e6-4c52-867a-5dd260f88e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-sel</value>
      <webElementGuid>f8e0cb77-4e70-40bf-8987-a78740109558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FSE</value>
      <webElementGuid>df901f02-4eb6-47e9-97ab-cfd29b1f538e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;main-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;sub-menu&quot;]/li[9]/a[@class=&quot;menu-sel&quot;]</value>
      <webElementGuid>3c9e95f8-d0c2-4594-8632-d6572d981ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/nav/ul/li/ul/li[6]/ul/li[9]/a</value>
      <webElementGuid>7d5915e7-100b-4377-a3d0-501284114354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Examens'])[1]/following::a[2]</value>
      <webElementGuid>dfed5a26-3142-41d4-8dce-5869bfb2217a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demandes de transfert'])[1]/preceding::a[1]</value>
      <webElementGuid>368866ab-864a-4059-8282-61e855a28c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[23]</value>
      <webElementGuid>85dca14b-d6d8-4a7e-81d8-fcc86c4b3699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[9]/a</value>
      <webElementGuid>79856ec5-eb9e-4930-9414-cdfa85113c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'FSE' or . = 'FSE')]</value>
      <webElementGuid>e19e56f3-8782-4e38-9101-bd9d27aa86fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
