<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TypedeFSE</name>
   <tag></tag>
   <elementGuidId>a57562e8-4355-4d6f-b810-142dc76df5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.enum-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field_namFseType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Observation&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bd89635-f030-4c23-a5f8-6da662bf2139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enum-item</value>
      <webElementGuid>19743231-cb08-4b18-be2f-e49ef89a60fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Observation</value>
      <webElementGuid>b8d9665d-6c13-4af8-8d2b-2b4de42c74ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-field_namFseType-container&quot;)/div[@class=&quot;enum-item&quot;]</value>
      <webElementGuid>881984b5-599a-4383-a114-a936935df550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-field_namFseType-container']/div</value>
      <webElementGuid>1c05bfb6-b987-4d33-b00e-4051464d2d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type de FSE'])[1]/following::div[1]</value>
      <webElementGuid>ceb13bb1-aecf-4e43-bf02-2359a860427f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statut de FSE'])[1]/preceding::div[1]</value>
      <webElementGuid>8d307ee2-78b1-4796-a52b-e09b5583302c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>78134136-8fe5-4f9e-a2db-5f40f15e097c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Observation' or . = 'Observation')]</value>
      <webElementGuid>2f87db04-f11c-4d5a-9f0d-5024ae211291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
