<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_CirconstancesConseilDiscipline</name>
   <tag></tag>
   <elementGuidId>75bd73f0-66c3-4045-b0ff-fbd8f22aab28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field_namFseConseilDiscCirconstance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_namFseConseilDiscCirconstance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#field_namFseConseilDiscCirconstance</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aa6aa340-57b4-457c-9a98-6ced81534fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autosize field-container</value>
      <webElementGuid>c8c04398-85d3-4f6e-b333-ba917cbff1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_namFseConseilDiscCirconstance</value>
      <webElementGuid>eb33d07e-a8f2-43c5-b96a-a1cae356aa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namFseConseilDiscCirconstance</value>
      <webElementGuid>73d6b91c-2ca3-47d1-be45-30afc19791bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>12503a1c-132d-4044-aab1-6015ff78065e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>d0e137da-334d-497f-9c72-caab19173d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_namFseConseilDiscCirconstance&quot;)</value>
      <webElementGuid>48463e28-c911-4b24-b6bd-0e2639e96598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_namFseConseilDiscCirconstance']</value>
      <webElementGuid>6f4e7f17-1c5f-4359-897c-4127c1954668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area7']/div/div[3]/div/div/textarea</value>
      <webElementGuid>71ffd0ce-8c81-4607-a702-189655a37cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div[3]/div/div/textarea</value>
      <webElementGuid>a098f2e5-39de-4e47-867d-05361907b9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_namFseConseilDiscCirconstance' and @name = 'namFseConseilDiscCirconstance']</value>
      <webElementGuid>fe9ad73c-b36c-469e-b32f-830d96a3d953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
